import { describe, expect, it } from "vitest";
import { createBackendServiceReadinessReport } from "./backendService";
import {
  backendRuntimeBootstrapDeferredDependencies,
  createBackendRuntimeBootstrapContract,
} from "./backendRuntimeBootstrap";
import { resolveApiServerRuntimeContract } from "./serverRuntime";

const secretFragments = [
  "auth-secret",
  "bearer sample",
  "mnemonic sample",
  "object-key-sample",
  "postgres://db.invalid/campaign-os",
  "private-key-sample",
  "queue-pass",
  "queue-secret",
  "queue-user",
  "raw-signature-sample",
  "scheduler-pass",
  "scheduler-secret",
  "scheduler-token-sample",
  "scheduler-user",
  "seed phrase sample",
  "signed-url",
];

const expectNoSecretLeak = (value: unknown) => {
  const serialized = JSON.stringify(value).toLowerCase();

  for (const fragment of secretFragments) {
    expect(serialized).not.toContain(fragment);
  }
};

const createLocalBootstrap = () => {
  const contract = resolveApiServerRuntimeContract({
    env: {},
    startedAt: "2026-07-06T18:00:00.000Z",
  });
  const backendReadiness = createBackendServiceReadinessReport({
    generatedAt: "2026-07-06T18:00:00.000Z",
  });

  return createBackendRuntimeBootstrapContract({
    backendReadiness,
    contract,
    now: new Date("2026-07-06T18:00:02.500Z"),
  });
};

describe("backend runtime bootstrap contract", () => {
  it("composes deterministic local-review bootstrap metadata without live side effects", () => {
    const bootstrap = createLocalBootstrap();

    expect(bootstrap).toMatchObject({
      id: "campaign-os-backend-runtime-bootstrap",
      profileId: "local-review",
      runtimeVersion: "0.2.0-local",
      status: "ready",
      supportMode: "local_seeded",
      valid: true,
      startup: {
        allowedOriginCount: 2,
        attachPointCount: expect.any(Number),
        blockedAttachPointCount: expect.any(Number),
        corsEnabled: true,
        host: "127.0.0.1",
        port: 5174,
        runtimeVersion: "0.2.0-local",
        startedAt: "2026-07-06T18:00:00.000Z",
      },
      activation: {
        deploymentHandoff: {
          contractsEndpoint: "/api/contracts",
          healthEndpoint: "/api/health",
          runtimeTarget: "api_service",
          shutdown: {
            idempotentStop: true,
            shutdownTimeoutMs: 5_000,
          },
          smokeCommand: "npm run server:smoke",
          startCommand: "npm run server:start",
        },
        id: "campaign-os-backend-runtime-activation",
        liveSideEffectsEnabled: false,
        productionReady: false,
        runtimeTarget: "node-http-api-service",
      },
      tracePolicy: {
        failureEnvelopeTraceId: true,
        startupLogIncludesTracePolicy: true,
        successEnvelopeTraceId: true,
        traceHeaderName: "x-campaign-os-trace-id",
      },
      requestGuard: {
        guardedFailureEnvelope: true,
        maxBodyBytes: 1_048_576,
        traceHeaderName: "x-campaign-os-trace-id",
      },
      shutdown: {
        activeRequestCount: 0,
        shutdownTimeoutMs: 5_000,
        state: "running",
      },
      readiness: {
        authSession: {
          status: "local_seeded",
          valid: true,
          verificationMode: "local_only",
        },
        backend: {
          entrypointId: "campaign-os-backend-service",
          valid: true,
        },
        databaseAdapterRuntime: {
          liveConnectionAttempted: false,
          liveQueryExecutionEnabled: false,
          status: "active_local",
          valid: true,
        },
        persistenceRuntime: {
          liveConnectionAttempted: false,
          liveExecutionEnabled: false,
          status: "active_local",
          valid: true,
        },
        providerClientReadiness: {
          activationStatus: "disabled",
          blockerCount: 0,
          diagnosticCodes: [],
          liveProviderCallsAttempted: false,
          productionReady: false,
          providerHttpRuntime: {
            activationStatus: "disabled",
            endpointCount: 13,
            endpointRollout: {
              deferredCount: 2,
              enabledCount: 11,
              providerFamilies: expect.arrayContaining(["aefinder", "aelfscan"]),
              valid: true,
            },
            liveHttpCallsAttempted: false,
            productionReady: false,
            runtimeId: "campaign-os-provider-http-client-runtime",
            status: "disabled",
            transportProvided: false,
            valid: true,
          },
          providerClientsEnabled: false,
          providerClientsProvided: false,
          queueHandoff: {
            consumeReadinessStatus: "disabled",
            queueId: "verification-jobs",
            workerJobId: "task-verification-worker",
          },
          redacted: true,
          registryClientCount: 0,
          registryProviderGroups: expect.arrayContaining([
            "aefinder-aelfscan-indexers",
            "dapp-api-adapters",
            "manual-review",
            "social-api-adapters",
            "wallet-auth-session",
          ]),
          requiredConfigKeys: expect.arrayContaining([
            "CAMPAIGN_OS_PROVIDER_CLIENT_ENABLEMENT",
            "CAMPAIGN_OS_PROVIDER_REGISTRY_URL",
            "CAMPAIGN_OS_PROVIDER_ENDPOINT_REF",
            "CAMPAIGN_OS_PROVIDER_CREDENTIAL_REF",
            "CAMPAIGN_OS_PROVIDER_CLIENT_SEAM",
            "CAMPAIGN_OS_PROVIDER_CONSUME_READINESS_HANDOFF",
            "CAMPAIGN_OS_PROVIDER_REDACTION_POLICY",
          ]),
          status: "disabled",
          valid: true,
        },
        queueRuntimeFoundation: {
          blockerCount: 0,
          diagnosticCodes: [],
          dryRunEnqueueEnabled: true,
          id: "campaign-os-queue-runtime-foundation",
          liveCronExecutionEnabled: false,
          liveQueueConsumptionEnabled: false,
          liveQueueConsumingReadiness: {
            activationStatus: "disabled",
            ackAttempted: false,
            blockerCount: 0,
            consumeAttemptPolicy: "disabled_no_live",
            consumeRequestEvaluated: false,
            consumeResultStatus: "not_requested",
            consumerId: "not_configured",
            consumerProvided: false,
            deadLetterAttempted: false,
            diagnosticCodes: [],
            handlerRegistryProvided: false,
            liveConsumeAttempted: false,
            liveQueueConsumptionEnabled: false,
            nackAttempted: false,
            productionReady: false,
            requiredConfigKeys: expect.arrayContaining([
              "CAMPAIGN_OS_LIVE_QUEUE_CONSUME_ENABLEMENT",
              "CAMPAIGN_OS_LIVE_QUEUE_CONSUMER",
            ]),
            retryScheduled: false,
            status: "disabled",
          },
          liveQueuePublishingEnabled: false,
          liveQueuePublishingReadiness: {
            activationStatus: "disabled",
            blockerCount: 0,
            diagnosticCodes: [],
            livePublishAttempted: false,
            liveQueuePublishingEnabled: false,
            noLiveSideEffects: expect.objectContaining({
              ack: false,
              deadLetter: false,
              queueConsumption: false,
              retry: false,
              schedulerExecution: false,
              telemetryExport: false,
              workerExecution: false,
            }),
            productionReady: false,
            publishAttemptPolicy: "disabled_no_live",
            publishRequestEvaluated: false,
            publishResultStatus: "not_requested",
            publisherId: "not_configured",
            publisherProvided: false,
            requiredConfigKeys: expect.arrayContaining([
              "CAMPAIGN_OS_LIVE_QUEUE_PUBLISHING_ENABLEMENT",
              "CAMPAIGN_OS_LIVE_QUEUE_PUBLISHER",
              "CAMPAIGN_OS_PAYLOAD_REFERENCE_POLICY",
              "CAMPAIGN_OS_PUBLISHER_REDACTION_POLICY",
            ]),
            status: "disabled",
          },
          liveSchedulerExecutionEnabled: false,
          liveWorkerExecutionEnabled: false,
          productionReady: false,
          providerAdapter: {
            adapterId: "local-dry-run-queue-provider-adapter",
            blockerCount: 0,
            diagnosticCodes: [],
            disabledLiveOperationCount: 8,
            driverActivationGateSatisfied: false,
            driverBlockerCount: 0,
            driverDiagnosticCodes: [],
            driverDisabledLiveOperationCount: 8,
            driverId: "local-fake-queue-provider-driver",
            driverLiveQueueConsumptionEnabled: false,
            driverLiveQueuePublishingEnabled: false,
            driverLiveWorkerExecutionEnabled: false,
            driverMode: "dry_run",
            driverOperationCount: 8,
            driverProductionReady: false,
            driverProviderId: "local-fake",
            driverConsumeAttemptPolicy: "disabled_no_live",
            driverConsumeRequestEvaluated: false,
            driverConsumeResultStatus: "not_requested",
            driverConsumingActivationStatus: "disabled",
            driverConsumingBlockerCount: 0,
            driverConsumingConsumerId: "not_configured",
            driverConsumingConsumerProvided: false,
            driverConsumingHandlerRegistryProvided: false,
            driverConsumingLiveConsumeAttempted: false,
            driverConsumingLiveQueueConsumptionEnabled: false,
            driverConsumingStatus: "disabled",
            driverPublishAttemptPolicy: "disabled_no_live",
            driverPublishDiagnosticCodes: [],
            driverPublishRequestEvaluated: false,
            driverPublishResultStatus: "not_requested",
            driverPublishingActivationStatus: "disabled",
            driverPublishingBlockerCount: 0,
            driverPublishingLivePublishAttempted: false,
            driverPublishingLiveQueuePublishingEnabled: false,
            driverPublishingNoLiveSideEffects: expect.objectContaining({
              ack: false,
              deadLetter: false,
              queueConsumption: false,
              retry: false,
              schedulerExecution: false,
              telemetryExport: false,
              workerExecution: false,
            }),
            driverPublishingPublisherId: "not_configured",
            driverPublishingPublisherProvided: false,
            driverPublishingRequiredConfigKeys: expect.arrayContaining([
              "CAMPAIGN_OS_LIVE_QUEUE_PUBLISHING_ENABLEMENT",
              "CAMPAIGN_OS_LIVE_QUEUE_PUBLISHER",
              "CAMPAIGN_OS_PAYLOAD_REFERENCE_POLICY",
              "CAMPAIGN_OS_PUBLISHER_REDACTION_POLICY",
            ]),
            driverPublishingStatus: "disabled",
            driverRequiredConfigKeys: expect.arrayContaining([
              "CAMPAIGN_OS_QUEUE_PROVIDER_DRIVER",
              "CAMPAIGN_OS_QUEUE_PROVIDER_ENDPOINT",
              "CAMPAIGN_OS_LIVE_QUEUE_ENABLEMENT",
            ]),
            driverSdkBindingBlockerCount: 0,
            driverSdkBindingDiagnosticCodes: [],
            driverSdkBindingDisabledLiveOperationCount: 8,
            driverSdkBindingId: "local-stub-queue-provider-sdk-binding",
            driverSdkBindingLiveProviderCallAttempted: false,
            driverSdkBindingLiveQueuePublishingEnabled: false,
            driverSdkBindingLiveWorkerExecutionEnabled: false,
            driverSdkBindingMode: "dry_run",
            driverSdkBindingOperationCount: 8,
            driverSdkBindingProductionReady: false,
            driverSdkBindingProviderKind: "local-stub",
            driverSdkBindingRequiredConfigKeys: expect.arrayContaining([
              "CAMPAIGN_OS_QUEUE_PROVIDER_SDK_PACKAGE",
              "CAMPAIGN_OS_QUEUE_PROVIDER_BINDING",
              "CAMPAIGN_OS_LIVE_QUEUE_ENABLEMENT",
            ]),
            driverSdkBindingSdkClientConstructed: false,
            driverSdkBindingSdkPackageRef: "local-stub-sdk-package",
            driverSdkBindingStatus: "local_ready",
            driverSdkBindingValid: true,
            driverStatus: "local_ready",
            driverValid: true,
            liveQueuePublishingEnabled: false,
            liveWorkerExecutionEnabled: false,
            mode: "dry_run",
            operationCount: 8,
            productionReady: false,
            providerId: "local-dry-run",
            requiredConfigKeys: expect.arrayContaining([
              "CAMPAIGN_OS_QUEUE_PROVIDER",
              "CAMPAIGN_OS_QUEUE_PROVIDER_ENDPOINT",
            ]),
            status: "local_ready",
            valid: true,
          },
          queuePlanCount: 9,
          status: "local_ready",
          valid: true,
        },
        workerLeaseStoreFoundation: {
          adapterId: "local-dry-run-worker-lease-store-adapter",
          blockerCount: 0,
          diagnosticCodes: [],
          disabledLiveOperationCount: 8,
          id: "campaign-os-worker-lease-store-foundation",
          liveQueuePublishingEnabled: false,
          liveWorkerExecutionEnabled: false,
          mode: "dry_run",
          operationCount: 8,
          productionReady: false,
          requiredConfigKeys: expect.arrayContaining([
            "CAMPAIGN_OS_WORKER_LEASE_STORE",
            "CAMPAIGN_OS_WORKER_LEASE_STORE_URL",
            "CAMPAIGN_OS_WORKER_LEASE_CREDENTIALS",
            "CAMPAIGN_OS_CLOCK_SOURCE",
            "CAMPAIGN_OS_WORKER_LEASE_HEARTBEAT_SECONDS",
            "CAMPAIGN_OS_WORKER_LEASE_TTL_SECONDS",
            "CAMPAIGN_OS_WORKER_LEASE_RELEASE_POLICY",
            "CAMPAIGN_OS_WORKER_LEASE_STALE_RECOVERY_POLICY",
            "CAMPAIGN_OS_WORKER_LEASE_FENCING_POLICY",
            "CAMPAIGN_OS_IDEMPOTENCY_STORE_URL",
            "CAMPAIGN_OS_OBSERVABILITY_EXPORTER_URL",
          ]),
          status: "local_ready",
          storeId: "local-dry-run",
          valid: true,
        },
        workerIdempotencyStoreFoundation: {
          adapterId: "local-dry-run-worker-idempotency-store-adapter",
          blockerCount: 0,
          diagnosticCodes: [],
          disabledLiveOperationCount: 8,
          id: "campaign-os-worker-idempotency-store-foundation",
          keySchemaVersion: "v1",
          liveIdempotencyExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveWorkerExecutionEnabled: false,
          mode: "dry_run",
          namespace: "campaign-os-workers",
          operationCount: 8,
          productionReady: false,
          requiredConfigKeys: expect.arrayContaining([
            "CAMPAIGN_OS_IDEMPOTENCY_STORE",
            "CAMPAIGN_OS_IDEMPOTENCY_STORE_URL",
            "CAMPAIGN_OS_IDEMPOTENCY_STORE_CREDENTIALS",
          ]),
          status: "local_ready",
          storeId: "local-dry-run",
          valid: true,
        },
        schedulerRuntimeFoundation: {
          blockerCount: 0,
          diagnosticCodes: [],
          dryRunTriggerEnabled: true,
          id: "campaign-os-scheduler-runtime-foundation",
          liveCronExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveSchedulerExecutionEnabled: false,
          liveWorkerExecutionEnabled: false,
          productionReady: false,
          registrationCount: 9,
          scheduleIds: expect.arrayContaining([
            "task-verification-on-request",
            "campaign-lifecycle-time-boundary",
            "eligibility-refresh-recurring",
            "export-preparation-operator",
            "analytics-ingestion-recurring",
            "ai-ops-report-recurring",
            "stale-review-cleanup-operator",
            "contract-sync-operator",
            "reward-distribution-operator",
          ]),
          status: "local_ready",
          valid: true,
        },
        observabilityExporterFoundation: {
          adapterId: "local-dry-run-observability-exporter-adapter",
          blockerCount: 0,
          diagnosticCodes: [],
          disabledLiveOperationCount: 8,
          exporterId: "local-dry-run",
          id: "campaign-os-observability-exporter-foundation",
          liveAlertRoutingEnabled: false,
          liveLogExportEnabled: false,
          liveMetricsExportEnabled: false,
          liveTelemetryExportEnabled: false,
          liveTraceExportEnabled: false,
          metricNamespace: "campaign-os-runtime",
          mode: "dry_run",
          operationCount: 8,
          productionReady: false,
          requiredConfigKeys: expect.arrayContaining([
            "CAMPAIGN_OS_OBSERVABILITY_EXPORTER",
            "CAMPAIGN_OS_OBSERVABILITY_EXPORTER_URL",
            "CAMPAIGN_OS_OBSERVABILITY_SINK",
          ]),
          sinkId: "local-metrics-sink",
          status: "local_ready",
          valid: true,
        },
        workerSchedulerFoundation: {
          blockerCount: 0,
          diagnosticCodes: [],
          id: "campaign-os-worker-scheduler-foundation",
          jobCatalogCount: 9,
          liveCronExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveSchedulerExecutionEnabled: false,
          liveWorkerExecutionEnabled: false,
          productionReady: false,
          schedulePolicyCount: 9,
          status: "local_ready",
          valid: true,
          verificationHandoffValid: true,
        },
      },
    });
    expect(bootstrap.uptimeMs).toBe(2500);
    expect(bootstrap.diagnosticCodes).toEqual([]);
    expect(bootstrap.deferredDependencyIds).toEqual(
      backendRuntimeBootstrapDeferredDependencies.map((dependency) => dependency.id),
    );
    expect(bootstrap.activation.deploymentHandoff.environmentKeys).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ key: "CAMPAIGN_OS_DATABASE_URL", redacted: true }),
        expect.objectContaining({ key: "CAMPAIGN_OS_AUTH_SECRET", redacted: true }),
      ]),
    );
    expect(bootstrap.activation.productionDependencyBlockers.map((blocker) => blocker.id)).toEqual(
      expect.arrayContaining([
        "live-database-driver",
        "migration-executor",
        "wallet-proof-verifier",
        "session-issuer",
        "contract-writer",
        "reward-custody",
        "reward-distribution",
      ]),
    );
  });

  it("fails closed for production-required without marking local fallbacks production-ready", () => {
    const env = {
      CAMPAIGN_OS_AUTH_SECRET: "auth-secret",
      CAMPAIGN_OS_BACKEND_PROFILE: "production-required",
      CAMPAIGN_OS_CONTRACT_WRITER_ENDPOINT: "https://writer.invalid/private-key-sample",
      CAMPAIGN_OS_DATABASE_URL: "postgres://db.invalid/campaign-os",
      CAMPAIGN_OS_DATABASE_MNEMONIC: "mnemonic sample",
      CAMPAIGN_OS_DATABASE_SIGNATURE: "raw-signature-sample",
      CAMPAIGN_OS_PROVIDER_REGISTRY_URL: "https://providers.invalid/object-key-sample",
      CAMPAIGN_OS_SCHEDULER_ENDPOINT: "https://scheduler-user:scheduler-pass@scheduler.invalid/hook?token=scheduler-secret",
      CAMPAIGN_OS_SCHEDULER_TOKEN_SAMPLE: "Bearer scheduler-token-sample",
      CAMPAIGN_OS_WORKER_QUEUE_URL: "https://queue-user:queue-pass@queue.invalid/jobs?token=queue-secret",
    };
    const contract = resolveApiServerRuntimeContract({ env });
    const backendReadiness = createBackendServiceReadinessReport({
      configOptions: { env },
    });
    const bootstrap = createBackendRuntimeBootstrapContract({
      backendReadiness,
      contract,
      now: new Date(contract.startedAt),
    });

    expect(bootstrap).toMatchObject({
      profileId: "production-required",
      readiness: {
        authSession: {
          status: "blocked",
          valid: false,
          verificationMode: "production_required",
        },
        backend: {
          valid: false,
        },
        databaseAdapterRuntime: {
          liveConnectionAttempted: false,
          liveQueryExecutionEnabled: false,
          status: "blocked",
          valid: false,
        },
        persistenceRuntime: {
          liveConnectionAttempted: false,
          liveExecutionEnabled: false,
          status: "boundary_ready",
        },
        queueRuntimeFoundation: {
          blockerCount: 7,
          diagnosticCodes: expect.arrayContaining([
            "QUEUE_PROVIDER_MISSING",
            "QUEUE_RETRY_POLICY_MISSING",
            "QUEUE_IDEMPOTENCY_STORE_MISSING",
            "QUEUE_WORKER_LEASE_MISSING",
            "QUEUE_OBSERVABILITY_MISSING",
            "QUEUE_PROVIDER_HANDOFF_MISSING",
            "QUEUE_DEAD_LETTER_MISSING",
          ]),
          dryRunEnqueueEnabled: false,
          liveCronExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveSchedulerExecutionEnabled: false,
          liveWorkerExecutionEnabled: false,
          productionReady: false,
          providerAdapter: {
            adapterId: "missing-provider-queue-provider-adapter",
            blockerCount: expect.any(Number),
            diagnosticCodes: expect.arrayContaining([
              "QUEUE_PROVIDER_MISSING",
              "QUEUE_PROVIDER_ENDPOINT_MISSING",
              "QUEUE_PROVIDER_CREDENTIALS_MISSING",
              "QUEUE_PROVIDER_DRIVER_MISSING",
              "QUEUE_PROVIDER_DRIVER_ENDPOINT_MISSING",
              "QUEUE_PROVIDER_DRIVER_CREDENTIALS_MISSING",
              "QUEUE_PROVIDER_DRIVER_RUNBOOK_MISSING",
              "QUEUE_PROVIDER_DRIVER_LIVE_ENABLEMENT_MISSING",
            ]),
            driverBlockerCount: expect.any(Number),
            driverDiagnosticCodes: expect.arrayContaining([
              "QUEUE_PROVIDER_DRIVER_MISSING",
              "QUEUE_PROVIDER_DRIVER_ENDPOINT_MISSING",
              "QUEUE_PROVIDER_DRIVER_CREDENTIALS_MISSING",
              "QUEUE_PROVIDER_DRIVER_RUNBOOK_MISSING",
              "QUEUE_PROVIDER_DRIVER_LIVE_ENABLEMENT_MISSING",
              "QUEUE_PROVIDER_SDK_PACKAGE_MISSING",
              "QUEUE_PROVIDER_SDK_BINDING_MISSING",
              "QUEUE_PROVIDER_SDK_LIVE_ENABLEMENT_MISSING",
            ]),
            driverLiveQueuePublishingEnabled: false,
            driverLiveWorkerExecutionEnabled: false,
            driverProductionReady: false,
            driverSdkBindingBlockerCount: expect.any(Number),
            driverSdkBindingDiagnosticCodes: expect.arrayContaining([
              "QUEUE_PROVIDER_SDK_PACKAGE_MISSING",
              "QUEUE_PROVIDER_SDK_BINDING_MISSING",
              "QUEUE_PROVIDER_SDK_LIVE_ENABLEMENT_MISSING",
            ]),
            driverSdkBindingLiveProviderCallAttempted: false,
            driverSdkBindingLiveQueuePublishingEnabled: false,
            driverSdkBindingLiveWorkerExecutionEnabled: false,
            driverSdkBindingMode: "production_required",
            driverSdkBindingProductionReady: false,
            driverSdkBindingSdkClientConstructed: false,
            driverSdkBindingStatus: "blocked",
            driverSdkBindingValid: false,
            liveQueuePublishingEnabled: false,
            liveWorkerExecutionEnabled: false,
            mode: "production_required",
            productionReady: false,
            providerId: "missing-provider",
            status: "blocked",
            valid: false,
          },
          queuePlanCount: 9,
          status: "blocked",
          valid: false,
        },
        workerLeaseStoreFoundation: {
          adapterId: "missing-lease-store-worker-lease-store-adapter",
          blockerCount: expect.any(Number),
          diagnosticCodes: expect.arrayContaining([
            "WORKER_LEASE_STORE_UNSUPPORTED",
            "WORKER_LEASE_STORE_MISSING",
            "WORKER_LEASE_ENDPOINT_MISSING",
            "WORKER_LEASE_CREDENTIALS_MISSING",
            "WORKER_LEASE_CLOCK_MISSING",
            "WORKER_LEASE_HEARTBEAT_POLICY_MISSING",
            "WORKER_LEASE_TTL_POLICY_MISSING",
            "WORKER_LEASE_RELEASE_POLICY_MISSING",
            "WORKER_LEASE_STALE_RECOVERY_MISSING",
            "WORKER_LEASE_FENCING_POLICY_MISSING",
            "WORKER_LEASE_IDEMPOTENCY_COORDINATION_MISSING",
            "WORKER_LEASE_OBSERVABILITY_MISSING",
          ]),
          liveQueuePublishingEnabled: false,
          liveWorkerExecutionEnabled: false,
          mode: "production_required",
          productionReady: false,
          status: "blocked",
          storeId: "missing-lease-store",
          valid: false,
        },
        workerIdempotencyStoreFoundation: {
          adapterId: "missing-idempotency-store-worker-idempotency-store-adapter",
          blockerCount: expect.any(Number),
          diagnosticCodes: expect.arrayContaining([
            "IDEMPOTENCY_STORE_UNSUPPORTED",
            "IDEMPOTENCY_STORE_MISSING",
            "IDEMPOTENCY_STORE_ENDPOINT_MISSING",
            "IDEMPOTENCY_STORE_CREDENTIALS_MISSING",
            "IDEMPOTENCY_NAMESPACE_MISSING",
            "IDEMPOTENCY_KEY_SCHEMA_VERSION_MISSING",
            "IDEMPOTENCY_RETENTION_POLICY_MISSING",
            "IDEMPOTENCY_CONFLICT_POLICY_MISSING",
            "IDEMPOTENCY_COMPLETION_POLICY_MISSING",
            "IDEMPOTENCY_CLOCK_MISSING",
            "IDEMPOTENCY_WORKER_LEASE_COORDINATION_MISSING",
            "IDEMPOTENCY_OBSERVABILITY_MISSING",
          ]),
          liveIdempotencyExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveWorkerExecutionEnabled: false,
          mode: "production_required",
          productionReady: false,
          status: "blocked",
          storeId: "missing-idempotency-store",
          valid: false,
        },
        schedulerRuntimeFoundation: {
          blockerCount: 6,
          diagnosticCodes: expect.arrayContaining([
            "SCHEDULER_PROVIDER_MISSING",
            "SCHEDULER_CLOCK_LEASE_MISSING",
            "SCHEDULER_IDEMPOTENCY_STORE_MISSING",
            "SCHEDULER_OBSERVABILITY_MISSING",
            "SCHEDULER_OPERATOR_AUTHORIZATION_MISSING",
            "SCHEDULER_DEAD_LETTER_MISSING",
          ]),
          dryRunTriggerEnabled: false,
          liveCronExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveSchedulerExecutionEnabled: false,
          liveWorkerExecutionEnabled: false,
          productionReady: false,
          registrationCount: 9,
          status: "blocked",
          valid: false,
        },
        observabilityExporterFoundation: {
          blockerCount: expect.any(Number),
          diagnosticCodes: expect.arrayContaining([
            "OBSERVABILITY_EXPORTER_MISSING",
            "OBSERVABILITY_ENDPOINT_MISSING",
            "OBSERVABILITY_CREDENTIALS_MISSING",
            "OBSERVABILITY_SINK_MISSING",
            "OBSERVABILITY_METRIC_NAMESPACE_MISSING",
            "OBSERVABILITY_TRACE_COLLECTOR_MISSING",
            "OBSERVABILITY_LOG_SINK_MISSING",
            "OBSERVABILITY_ALERT_ROUTING_MISSING",
          ]),
          exporterId: "missing-observability-exporter",
          liveAlertRoutingEnabled: false,
          liveLogExportEnabled: false,
          liveMetricsExportEnabled: false,
          liveTelemetryExportEnabled: false,
          liveTraceExportEnabled: false,
          mode: "production_required",
          productionReady: false,
          sinkId: "missing-observability-sink",
          status: "blocked",
          valid: false,
        },
        workerSchedulerFoundation: {
          blockerCount: 4,
          diagnosticCodes: expect.arrayContaining([
            "RETRY_BACKOFF_POLICY_MISSING",
            "IDEMPOTENCY_STORE_MISSING",
            "WORKER_LEASE_MISSING",
            "OBSERVABILITY_MISSING",
          ]),
          liveCronExecutionEnabled: false,
          liveQueuePublishingEnabled: false,
          liveSchedulerExecutionEnabled: false,
          liveWorkerExecutionEnabled: false,
          productionReady: false,
          status: "blocked",
          valid: false,
          verificationHandoffValid: true,
        },
      },
      status: "blocked",
      valid: false,
    });
    expect(bootstrap.diagnosticCodes).toEqual(
      expect.arrayContaining([
        "BACKEND_RUNTIME_BOOTSTRAP_PRODUCTION_BLOCKED",
        "BACKEND_RUNTIME_BOOTSTRAP_SERVER_RUNTIME_INVALID",
        "BACKEND_RUNTIME_BOOTSTRAP_BACKEND_READINESS_INVALID",
      ]),
    );
    expect(bootstrap.deferredDependencies).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: "production-database-driver",
          status: "blocked",
        }),
        expect.objectContaining({
          id: "auth-middleware",
          status: "blocked",
        }),
        expect.objectContaining({
          id: "contract-writer",
          status: "blocked",
        }),
        expect.objectContaining({
          id: "reward-custody",
          status: "blocked",
        }),
        expect.objectContaining({
          id: "analytics-warehouse",
          status: "deferred",
        }),
      ]),
    );
    expectNoSecretLeak(bootstrap);
  });

  it("represents all required deferred backend activation dependencies", () => {
    const bootstrap = createLocalBootstrap();

    expect(bootstrap.deferredDependencyIds).toEqual(
      expect.arrayContaining([
        "deployment-config",
        "production-database-driver",
        "database-migration-executor",
        "auth-middleware",
        "provider-adapters",
        "worker-ingress",
        "scheduler",
        "contract-writer",
        "object-storage-export",
        "observability-exporter",
        "analytics-warehouse",
        "reward-custody",
        "reward-distribution",
      ]),
    );
    expect(bootstrap.deferredDependencies.every((dependency) => dependency.requiredBeforeProduction)).toBe(true);
    expect(bootstrap.deferredDependencies.every((dependency) => dependency.blockedBy.length > 0)).toBe(true);
  });

  it("reports shutdown lifecycle states without claiming readiness", () => {
    const contract = resolveApiServerRuntimeContract({
      env: {},
      shutdownTimeoutMs: 1234,
      startedAt: "2026-07-06T18:00:00.000Z",
    });
    const backendReadiness = createBackendServiceReadinessReport();
    const stopping = createBackendRuntimeBootstrapContract({
      backendReadiness,
      contract,
      shutdownState: {
        activeRequestCount: 2,
        state: "stopping",
        stopStartedAt: "2026-07-06T18:00:03.000Z",
      },
    });
    const stopped = createBackendRuntimeBootstrapContract({
      backendReadiness,
      contract,
      shutdownState: {
        activeRequestCount: 0,
        closedAt: "2026-07-06T18:00:04.000Z",
        state: "stopped",
      },
    });

    expect(stopping).toMatchObject({
      diagnosticCodes: expect.arrayContaining([
        "BACKEND_RUNTIME_BOOTSTRAP_SHUTDOWN_IN_PROGRESS",
      ]),
      shutdown: {
        activeRequestCount: 2,
        shutdownTimeoutMs: 1234,
        state: "stopping",
      },
      status: "deferred",
      valid: true,
    });
    expect(stopped).toMatchObject({
      diagnosticCodes: expect.arrayContaining([
        "BACKEND_RUNTIME_BOOTSTRAP_STOPPED",
      ]),
      shutdown: {
        activeRequestCount: 0,
        state: "stopped",
      },
      status: "blocked",
      valid: false,
    });
  });
});
