import { requiredApiSkillIds } from "../domain/apiSkillContracts";
import type { ApiSkillId, LocalizedText } from "../domain/types";
import type { ApiRuntimeContractCoverage, ApiRuntimeRouteContract } from "./contracts";
import { apiRuntimeServiceGroupById } from "./capabilities";
import { runtimeBoundary } from "./envelope";

const text = (enUS: string, zhCN: string, zhTW = enUS): LocalizedText => ({
  "en-US": enUS,
  "zh-CN": zhCN,
  "zh-TW": zhTW,
});

const route = (contract: ApiRuntimeRouteContract): ApiRuntimeRouteContract => contract;

const boundary = runtimeBoundary;
const dependenciesFor = (serviceGroup: ApiRuntimeRouteContract["serviceGroup"]) =>
  apiRuntimeServiceGroupById[serviceGroup].deferredDependencies;

export const apiRuntimeRoutes = [
  route({
    apiGroup: "runtime",
    boundary,
    id: "runtime.health",
    method: "GET",
    path: "/api/health",
    productionDependencies: dependenciesFor("runtime"),
    readiness: "ready",
    riskLevel: "low",
    serviceGroup: "runtime",
    summary: text("Local runtime health and safety flags.", "本地 runtime 健康状态与安全边界。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "runtime",
    boundary,
    id: "runtime.contracts",
    method: "GET",
    path: "/api/contracts",
    productionDependencies: dependenciesFor("runtime"),
    readiness: "ready",
    riskLevel: "low",
    serviceGroup: "runtime",
    summary: text("Local route catalog and API skill coverage.", "本地 route catalog 与 API Skill 覆盖。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "service_registry",
    boundary,
    id: "runtime.services",
    method: "GET",
    path: "/api/services",
    productionDependencies: dependenciesFor("service_registry"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "service_registry",
    summary: text("External service registry readiness.", "外部服务 registry readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "wallet_session",
    apiSkillId: "agent_wallet_action",
    boundary,
    id: "agent.wallet.action.review",
    method: "POST",
    path: "/api/agent-wallet/actions/review",
    productionDependencies: dependenciesFor("wallet_session"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "wallet_session",
    summary: text("Review internal Agent Skill wallet action readiness.", "审核内部 Agent Skill 钱包动作 readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "wallet_session",
    apiSkillId: "create_wallet_session",
    boundary,
    id: "wallet.session.create",
    method: "POST",
    path: "/api/wallet/session",
    productionDependencies: dependenciesFor("wallet_session"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "wallet_session",
    summary: text("Create a normalized local wallet session.", "创建本地归一化钱包会话。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    apiSkillId: "list_campaigns",
    boundary,
    id: "campaigns.list",
    method: "GET",
    path: "/api/campaigns",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("List seeded Campaign OS campaigns.", "列出 seeded Campaign OS 活动。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_creation",
    apiSkillId: "create_campaign",
    boundary,
    id: "campaigns.create",
    method: "POST",
    path: "/api/campaigns",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Create a local campaign draft.", "创建本地活动草稿。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    apiSkillId: "get_campaign_detail",
    boundary,
    id: "campaigns.detail",
    method: "GET",
    path: "/api/campaigns/:campaignId",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Get seeded campaign detail.", "获取 seeded 活动详情。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    apiSkillId: "get_campaign_lifecycle",
    boundary,
    id: "campaigns.lifecycle",
    method: "GET",
    path: "/api/campaigns/:campaignId/lifecycle",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect local campaign lifecycle operations.", "检查本地活动 lifecycle 操作。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    apiSkillId: "get_campaign_launch_readiness",
    boundary,
    id: "campaigns.launch.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/launch-readiness",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect local campaign launch readiness.", "检查本地活动 launch readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary,
    id: "campaigns.delivery.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/delivery-readiness",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect local delivery checklist readiness.", "检查本地交付清单 readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary: text(
      "Local front-end/back-end publish delivery review bridge. No live API, production publish, provider call, contract write, storage write, or reward execution is performed.",
      "本地前后端 publish delivery review bridge。不会执行真实发布、provider 调用、合约写入、storage 写入或奖励执行。",
    ),
    id: "campaigns.publish.delivery.review",
    method: "GET",
    path: "/api/campaigns/:campaignId/publish-delivery-review",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect the local publish and delivery joint review payload.", "检查本地发布与交付联合 review payload。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary: text(
      "Local points/ranking ledger runtime review route. No live API, Pixiepoints write, backend ledger write, provider/indexer call, wallet signature, contract write, export file, reward custody, or reward distribution is performed.",
      "本地 points/ranking ledger runtime review route。不会执行实时 API、Pixiepoints 写入、后端账本写入、provider/indexer 调用、钱包签名、合约写入、导出文件、奖励托管或发奖。",
    ),
    id: "campaigns.points.ranking.ledger.runtime",
    method: "GET",
    path: "/api/campaigns/:campaignId/points-ranking-ledger-runtime",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect the local points ranking ledger runtime payload.", "检查本地 points ranking ledger runtime payload。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary,
    id: "campaigns.companion.contract.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/companion-contract-readiness",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect local companion contract readiness.", "检查本地 companion contract readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary: text(
      "Local contract writer runtime readiness review route. No live API, signer, wallet signature, ABI generation, contract write, root write, queue publishing, scheduler execution, storage write, export write, reward custody, or reward distribution is performed.",
      "本地 contract writer runtime readiness review route。不会执行实时 API、真实 signer、钱包签名、ABI 生成、合约写入、root 写入、队列发布、调度执行、storage 写入、导出写入、奖励托管或发奖。",
    ),
    id: "campaigns.contract.writer.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/contract-writer/readiness",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "campaign",
    summary: text("Inspect local contract writer runtime readiness.", "检查本地 contract writer runtime readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary: text(
      "Local reward distribution handoff readiness review route. No live API, payout, reward custody, reward distribution, provider call, wallet signing, contract write, queue publishing, scheduler execution, or worker execution is performed.",
      "本地 reward distribution handoff readiness review route。不会执行实时 API、payout、奖励托管、发奖、provider 调用、钱包签名、合约写入、队列发布、调度执行或 worker 执行。",
      "本地 reward distribution handoff readiness review route。不會執行即時 API、payout、獎勵託管、發獎、provider 呼叫、錢包簽名、合約寫入、隊列發布、排程執行或 worker 執行。",
    ),
    id: "campaigns.reward.distribution.handoff.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/reward-distribution/handoff-readiness",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "campaign",
    summary: text("Inspect local reward distribution handoff readiness.", "检查本地 reward distribution handoff readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary: text(
      "Local review-only project owner funding proof bridge. No live API call, upload, object storage write, signed URL, funding transfer, reward custody, reward distribution, provider call, wallet signing, contract write, queue publishing, scheduler execution, or worker execution is performed.",
      "本地、仅审核的项目方资金证明 bridge。不会执行上传、对象存储写入、signed URL、资金转移、奖励托管、发奖、provider 调用、钱包签名、合约写入、队列发布、调度执行或 worker 执行。",
      "本地、僅審核的專案方資金證明 bridge。不會執行上傳、物件儲存寫入、signed URL、資金轉移、獎勵託管、發獎、provider 呼叫、錢包簽名、合約寫入、隊列發布、排程執行或 worker 執行。",
    ),
    id: "campaigns.reward.funding-proof.review",
    method: "GET",
    path: "/api/campaigns/:campaignId/reward-distribution/funding-proof-review",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "campaign",
    summary: text("Inspect local project owner funding proof review state.", "检查本地项目方资金证明 review state。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary: text(
      "Local review-only project owner funding proof metadata normalization route. Request metadata is sanitized and not persisted; No live API call, upload, object storage write, signed URL, funding transfer, reward custody, reward distribution, provider call, wallet signing, contract write, queue publishing, scheduler execution, or worker execution is performed.",
      "本地、仅审核的项目方资金证明 metadata 归一化 route。请求 metadata 会被清洗且不会持久化；不会执行上传、对象存储写入、signed URL、资金转移、奖励托管、发奖、provider 调用、钱包签名、合约写入、队列发布、调度执行或 worker 执行。",
      "本地、僅審核的專案方資金證明 metadata 歸一化 route。請求 metadata 會被清洗且不會持久化；不會執行上傳、物件儲存寫入、signed URL、資金轉移、獎勵託管、發獎、provider 呼叫、錢包簽名、合約寫入、隊列發布、排程執行或 worker 執行。",
    ),
    id: "campaigns.reward.funding-proof.review.submit",
    method: "POST",
    path: "/api/campaigns/:campaignId/reward-distribution/funding-proof-review",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "campaign",
    summary: text("Normalize local project owner funding proof review metadata.", "归一化本地项目方资金证明 review metadata。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_discovery",
    boundary,
    id: "campaigns.contract.transparency",
    method: "GET",
    path: "/api/campaigns/:campaignId/contract-transparency",
    productionDependencies: dependenciesFor("campaign"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "campaign",
    summary: text("Inspect local contract transparency lanes.", "检查本地 contract transparency lanes。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "task_generation",
    apiSkillId: "add_campaign_task",
    boundary,
    id: "campaigns.tasks.add",
    method: "POST",
    path: "/api/campaigns/:campaignId/tasks",
    productionDependencies: dependenciesFor("task"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "task",
    summary: text("Add a local campaign task draft.", "添加本地活动任务草稿。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "task_generation",
    apiSkillId: "generate_campaign_tasks",
    boundary,
    id: "campaigns.tasks.generate",
    method: "POST",
    path: "/api/campaigns/:campaignId/tasks/generate",
    productionDependencies: dependenciesFor("task"),
    readiness: "ready",
    riskLevel: "medium",
    serviceGroup: "task",
    summary: text("Generate local campaign task suggestions.", "生成本地活动任务建议。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "task_verification",
    apiSkillId: "verify_task",
    boundary,
    id: "tasks.verify",
    method: "POST",
    path: "/api/tasks/:taskId/verify",
    productionDependencies: dependenciesFor("verification"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "verification",
    summary: text("Verify seeded task evidence locally.", "本地验证 seeded 任务 evidence。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "task_verification",
    apiSkillId: "get_campaign_provider_readiness",
    boundary,
    id: "campaigns.provider.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/provider-readiness",
    productionDependencies: dependenciesFor("verification"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "verification",
    summary: text("Inspect local provider and verification readiness.", "检查本地 provider 与验证 readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "eligibility",
    apiSkillId: "check_eligibility",
    boundary,
    id: "campaigns.eligibility",
    method: "GET",
    path: "/api/campaigns/:campaignId/eligibility",
    productionDependencies: dependenciesFor("eligibility"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "eligibility",
    summary: text("Check local campaign eligibility.", "检查本地活动资格。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "analytics",
    apiSkillId: "get_campaign_analytics",
    boundary,
    id: "campaigns.analytics",
    method: "GET",
    path: "/api/campaigns/:campaignId/analytics",
    productionDependencies: dependenciesFor("analytics"),
    readiness: "ready",
    riskLevel: "low",
    serviceGroup: "analytics",
    summary: text("Get local campaign analytics summary.", "获取本地活动 analytics 汇总。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "analytics",
    boundary: text(
      "Local analytics ingestion readiness review route. No live API, analytics SDK, event warehouse write, browser tracking, profiling, fingerprinting, provider call, production database mutation, export write, contract write, wallet signature, reward custody, or reward distribution is performed.",
      "本地 analytics ingestion readiness review route。不会执行实时 API、analytics SDK、事件仓库写入、浏览器追踪、画像、指纹识别、provider 调用、生产数据库变更、导出写入、合约写入、钱包签名、奖励托管或发奖。",
    ),
    id: "campaigns.analytics.ingestion.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/analytics/ingestion-readiness",
    productionDependencies: dependenciesFor("analytics"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "analytics",
    summary: text("Inspect local analytics ingestion runtime readiness.", "检查本地 analytics ingestion runtime readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "campaign_summary",
    apiSkillId: "summarize_campaign",
    boundary,
    id: "campaigns.summary",
    method: "GET",
    path: "/api/campaigns/:campaignId/summary",
    productionDependencies: dependenciesFor("analytics"),
    readiness: "ready",
    riskLevel: "low",
    serviceGroup: "analytics",
    summary: text("Get a local campaign report-card summary.", "获取本地活动报告卡汇总。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "content_generation",
    apiSkillId: "generate_i18n_draft",
    boundary,
    id: "campaigns.i18n.generate",
    method: "POST",
    path: "/api/campaigns/:campaignId/i18n/generate",
    productionDependencies: dependenciesFor("i18n"),
    readiness: "local_only",
    riskLevel: "medium",
    serviceGroup: "i18n",
    summary: text("Generate local i18n draft for human review.", "生成人工审核用本地 i18n 草稿。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "content_generation",
    apiSkillId: "generate_campaign_posts",
    boundary,
    id: "campaigns.posts.generate",
    method: "POST",
    path: "/api/campaigns/:campaignId/posts/generate",
    productionDependencies: dependenciesFor("i18n"),
    readiness: "review_required",
    riskLevel: "medium",
    serviceGroup: "i18n",
    summary: text("Generate local campaign channel post drafts.", "生成本地活动渠道帖子草稿。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "export",
    apiSkillId: "export_winners",
    boundary,
    id: "campaigns.export.preview",
    method: "POST",
    path: "/api/campaigns/:campaignId/export",
    productionDependencies: dependenciesFor("export"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "export",
    summary: text("Preview local winners export.", "预览本地 winners 导出。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "export",
    apiSkillId: "get_campaign_export_readiness",
    boundary,
    id: "campaigns.export.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/export-readiness",
    productionDependencies: dependenciesFor("export"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "export",
    summary: text("Inspect local export confirmation readiness.", "检查本地导出确认 readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "export",
    boundary: text(
      "Local object storage export readiness review route. No live API, upload, object key creation, signed URL creation, download, provider call, contract write, wallet signature, reward custody, or reward distribution is performed.",
      "本地 object storage export readiness review route。不会执行实时 API、上传、object key 创建、signed URL 创建、下载、provider 调用、合约写入、钱包签名、奖励托管或发奖。",
    ),
    id: "campaigns.export.storage.readiness",
    method: "GET",
    path: "/api/campaigns/:campaignId/export/storage-readiness",
    productionDependencies: dependenciesFor("export"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "export",
    summary: text("Inspect local object storage export readiness.", "检查本地 object storage export readiness。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "export",
    boundary,
    id: "campaigns.export.artifacts.list",
    method: "GET",
    path: "/api/campaigns/:campaignId/export-artifacts",
    productionDependencies: dependenciesFor("export"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "export",
    summary: text("List local export artifact audit records.", "列出本地导出 artifact 审计记录。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "export",
    boundary,
    id: "campaigns.export.artifacts.detail",
    method: "GET",
    path: "/api/campaigns/:campaignId/export-artifacts/:artifactId",
    productionDependencies: dependenciesFor("export"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "export",
    summary: text("Get a local export artifact audit record.", "获取本地导出 artifact 审计记录。"),
    supportMode: "local_seeded",
  }),
  route({
    apiGroup: "export",
    boundary,
    id: "campaigns.export.artifacts.file",
    method: "GET",
    path: "/api/campaigns/:campaignId/export-artifacts/:artifactId/file",
    productionDependencies: dependenciesFor("export"),
    readiness: "review_required",
    riskLevel: "high",
    serviceGroup: "export",
    summary: text("Return a local export artifact file handoff payload.", "返回本地导出 artifact 文件交接 payload。"),
    supportMode: "local_seeded",
  }),
] as const satisfies readonly ApiRuntimeRouteContract[];

export type ApiRuntimeRouteId = (typeof apiRuntimeRoutes)[number]["id"];

export const apiRuntimeRouteById = Object.fromEntries(
  apiRuntimeRoutes.map((runtimeRoute) => [runtimeRoute.id, runtimeRoute]),
) as Record<ApiRuntimeRouteId, ApiRuntimeRouteContract>;

export const createApiRuntimeContractCoverage = (): ApiRuntimeContractCoverage => {
  const coveredSkillIdSet = new Set(
    apiRuntimeRoutes
      .map((runtimeRoute) => runtimeRoute.apiSkillId)
      .filter((skillId): skillId is ApiSkillId => Boolean(skillId)),
  );
  const coveredSkillIds = requiredApiSkillIds.filter((skillId) => coveredSkillIdSet.has(skillId));

  return {
    coveredSkillIds,
    deferredSkillIds: requiredApiSkillIds.filter((skillId) => !coveredSkillIdSet.has(skillId)),
    routeCount: apiRuntimeRoutes.length,
    routeIds: apiRuntimeRoutes.map((runtimeRoute) => runtimeRoute.id),
  };
};
