import type { SupportedLocale } from "../../../domain";

export const userAppCopy = {
  "en-US": {
    active: "Live campaign",
    campaignDetail: "Campaign Detail",
    completed: "Completed",
    connectWallet: "Connect Wallet",
    contractMode: "Contract mode",
    eligibility: "Eligibility checker",
    eligible: "Eligible",
    feedTitle: "Campaign Feed",
    ineligible: "Ineligible",
    localePreference: "Locale preference",
    messageBoundary: "Wallet connection is limited to connection and message signing in this shell.",
    missingTasks: "Missing tasks",
    nextAction: "Next action",
    noLiveLedger: "Seeded shell preview; points and rank are not a live ledger.",
    points: "Points",
    privateKeySafety: "Campaign OS never asks for private keys or seed phrases.",
    rank: "Rank",
    referral: "Referral context",
    referralValue: "Referral attribution preview only",
    rewards: "Points and ranking",
    riskFlags: "Risk flags",
    taskList: "Task list",
    timeWindow: "Time window",
    walletAddress: "Wallet address",
    walletOptions: "Wallet options",
    walletPolicy: "Wallet policy",
    walletSource: "Wallet source",
    walletType: "Wallet type",
    recommended: "Recommended",
    advanced: "Internal/advanced",
    capability: "Capabilities",
    verification: "Verification",
    compatibility: "Wallet compatibility",
    localeReadiness: "Locale readiness",
    recoverMissing: "Complete missing required tasks before export eligibility.",
  },
  "zh-CN": {
    active: "进行中的活动",
    campaignDetail: "活动详情",
    completed: "已完成",
    connectWallet: "连接钱包",
    contractMode: "合约模式",
    eligibility: "资格检查器",
    eligible: "符合资格",
    feedTitle: "活动 Feed",
    ineligible: "不符合资格",
    localePreference: "语言偏好",
    messageBoundary: "当前 shell 仅展示连接钱包和消息签名边界。",
    missingTasks: "缺失任务",
    nextAction: "下一步",
    noLiveLedger: "这是 seeded shell 预览；积分和排名不是实时账本。",
    points: "积分",
    privateKeySafety: "Campaign OS 永远不会索要私钥或助记词。",
    rank: "排名",
    referral: "推荐关系",
    referralValue: "仅展示推荐归因预览",
    rewards: "积分与排名",
    riskFlags: "风险标记",
    taskList: "任务列表",
    timeWindow: "活动时间",
    walletAddress: "钱包地址",
    walletOptions: "钱包选项",
    walletPolicy: "钱包策略",
    walletSource: "钱包来源",
    walletType: "钱包类型",
    recommended: "推荐",
    advanced: "内部/高级",
    capability: "能力",
    verification: "验证方式",
    compatibility: "钱包兼容性",
    localeReadiness: "语言就绪状态",
    recoverMissing: "完成缺失的必做任务后再进入导出资格。",
  },
} satisfies Record<SupportedLocale, Record<string, string>>;

export type UserAppCopy = (typeof userAppCopy)["en-US"];
