import type { SupportedLocale } from "../../../domain";

export const userAppCopy = {
  "en-US": {
    active: "Live campaign",
    campaignDetail: "Campaign Detail",
    completed: "Completed",
    completedRequired: "Required progress",
    connectWallet: "Connect Wallet",
    contractMode: "Contract mode",
    eligibleCutoff: "Eligible rank cutoff",
    eligibility: "Eligibility checker",
    eligible: "Eligible",
    ended: "Ended",
    evidenceSource: "Evidence source",
    failed: "Failed",
    feedTitle: "Campaign Feed",
    ineligible: "Ineligible",
    inviteLink: "Invite link",
    invitedCount: "Raw invites",
    qualifiedInvitees: "Qualified invitees",
    localePreference: "Locale preference",
    leaderboard: "Leaderboard preview",
    messageBoundary: "Wallet connection is limited to connection and message signing in this shell.",
    missingTasks: "Missing tasks",
    noMissingTasks: "No missing required tasks",
    nextAction: "Next action",
    noLiveLedger: "Seeded shell preview; points and rank are not a live ledger.",
    pending: "Pending verification",
    points: "Points",
    pointsAwarded: "Points awarded",
    pointsAvailable: "Available points",
    pointsThreshold: "Points threshold",
    privateKeySafety: "Campaign OS never asks for private keys or seed phrases.",
    rank: "Rank",
    referral: "Referral context",
    referralPoints: "Referral points",
    referralValue: "Referral attribution preview only",
    rewards: "Points and ranking",
    rewardBoundary: "Rewards are provided by the campaign project. Export winners does not distribute rewards.",
    riskFlags: "Risk flags",
    riskFlagged: "Risk flagged",
    score: "Score",
    status: "Status",
    taskList: "Task list",
    timeWindow: "Time window",
    walletAddress: "Wallet address",
    walletOptions: "Wallet options",
    walletPolicy: "Wallet policy",
    walletSource: "Wallet source",
    walletType: "Wallet type",
    recommended: "Recommended",
    advanced: "Internal/advanced",
    capability: "Capabilities",
    verification: "Verification",
    compatibility: "Wallet compatibility",
    localeReadiness: "Locale readiness",
    recoverMissing: "Complete missing required tasks before export eligibility.",
    ready: "Ready",
    manualReview: "Manual review",
    notEligible: "Not eligible",
    riskClear: "No risk flags",
    taskVerification: "Task verification states",
  },
  "zh-CN": {
    active: "进行中的活动",
    campaignDetail: "活动详情",
    completed: "已完成",
    completedRequired: "必做进度",
    connectWallet: "连接钱包",
    contractMode: "合约模式",
    eligibleCutoff: "入选排名线",
    eligibility: "资格检查器",
    eligible: "符合资格",
    ended: "已结束",
    evidenceSource: "证据来源",
    failed: "失败",
    feedTitle: "活动 Feed",
    ineligible: "不符合资格",
    inviteLink: "邀请链接",
    invitedCount: "原始邀请数",
    qualifiedInvitees: "合格被邀请人",
    localePreference: "语言偏好",
    leaderboard: "排行榜预览",
    messageBoundary: "当前 shell 仅展示连接钱包和消息签名边界。",
    missingTasks: "缺失任务",
    noMissingTasks: "没有缺失的必做任务",
    nextAction: "下一步",
    noLiveLedger: "这是 seeded shell 预览；积分和排名不是实时账本。",
    pending: "等待验证",
    points: "积分",
    pointsAwarded: "已获得积分",
    pointsAvailable: "可获得积分",
    pointsThreshold: "积分门槛",
    privateKeySafety: "Campaign OS 永远不会索要私钥或助记词。",
    rank: "排名",
    referral: "推荐关系",
    referralPoints: "推荐积分",
    referralValue: "仅展示推荐归因预览",
    rewards: "积分与排名",
    rewardBoundary: "奖励由活动项目方提供。导出 winners 不等于发奖。",
    riskFlags: "风险标记",
    riskFlagged: "风险标记",
    score: "分数",
    status: "状态",
    taskList: "任务列表",
    timeWindow: "活动时间",
    walletAddress: "钱包地址",
    walletOptions: "钱包选项",
    walletPolicy: "钱包策略",
    walletSource: "钱包来源",
    walletType: "钱包类型",
    recommended: "推荐",
    advanced: "内部/高级",
    capability: "能力",
    verification: "验证方式",
    compatibility: "钱包兼容性",
    localeReadiness: "语言就绪状态",
    recoverMissing: "完成缺失的必做任务后再进入导出资格。",
    ready: "待完成",
    manualReview: "人工审核",
    notEligible: "不符合资格",
    riskClear: "无风险标记",
    taskVerification: "任务验证状态",
  },
} satisfies Record<SupportedLocale, Record<string, string>>;

export type UserAppCopy = (typeof userAppCopy)["en-US"];
