import type { SupportedLocale } from "../../../domain";

const enUS = {
    active: "Live campaign",
    appHubTitle: "aelf App Hub",
    appHubSubtitle: "Mobile entry for campaigns, points, pay, forecast, and portfolio.",
    appHubBoundary: "Seeded mobile hub preview; no Telegram Mini App, payment, forecast, or portfolio service is connected.",
    appHubToday: "Today's campaign",
    appHubGuide: "What should I do today?",
    appHubGuideText: "You have live campaign tasks and one eligibility gap to review.",
    appHubQuickActions: "Quick actions",
    appHubCampaigns: "Campaigns",
    appHubPay: "Pay",
    appHubForecast: "Forecast",
    appHubPortfolio: "Portfolio",
    appHubMe: "Me",
    appHubHome: "Home",
    campaignDetail: "Campaign Detail",
    shareCardReadiness: "Share card readiness",
    shareCardReadinessSubtitle: "Localized URL and metadata preview for this campaign.",
    shareCanonicalUrl: "Canonical URL",
    shareAlternateUrls: "Alternate URLs",
    sharePreviewTitle: "Preview title",
    sharePreviewDescription: "Preview description",
    shareFallbackNotice: "Fallback notice",
    shareFallbackActive: "English fallback",
    shareReadyLocal: "Local preview ready",
    shareBoundary: "Local share readiness only. No SSR, crawler guarantee, social API, or share-card upload is connected.",
    campaignType: "Campaign type",
    comingSoon: "Coming Soon",
    completed: "Completed",
    completedRequired: "Required progress",
    connectWallet: "Connect Wallet",
    continueTasks: "Continue tasks",
    verifyTaskAction: "Verify task",
    retryVerificationAction: "Retry verification",
    submitProofAction: "Submit proof",
    viewReviewAction: "View review queue",
    alreadyVerifiedAction: "Already verified",
    latestLocalAction: "Latest local action",
    localAttempt: "Local attempt",
    proofType: "Proof type",
    noUploadExecuted: "No upload executed",
    localOnlyActionBoundary: "Local task action only; no live provider, upload, backend mutation, reward distribution, or contract write is executed.",
    noLiveProviderBoundary: "No live provider is called by this action.",
    noRewardDistributionBoundary: "This action does not approve eligibility, export winners, or distribute rewards.",
    localActionStatus: "Local action status",
    localValidationFailure: "Local validation failure",
    actionKind: "Action",
    manualQueue: "Review queue",
    contractMode: "Contract mode",
    diagnostics: "Wallet Connection Diagnostics",
    diagnosticsSubtitle: "Seeded AA + EOA coverage for campaign wallet QA.",
    diagnosticsTotal: "Seeded sessions",
    diagnosticsVerified: "Verified sessions",
    diagnosticsIssues: "Issue states",
    diagnosticsRecommendedReady: "Recommended AA ready",
    diagnosticsEoaReady: "EOA paths ready",
    diagnosticsQa: "Wallet QA checklist",
    diagnosticsScenario: "QA scenario",
    diagnosticsSupported: "Supported; AA is recommended, not mandatory.",
    diagnosticsNotLive: "Diagnostics are seeded QA evidence, not a live wallet connection test.",
    eligibleCutoff: "Eligible rank cutoff",
    eligibility: "Eligibility checker",
    eligible: "Eligible",
    ecosystemNextActions: "Ecosystem next actions",
    ecosystemSubtitle: "Explainable Pay, Forecast, and Portfolio follow-ups derived from campaign progress.",
    ecosystemBoundary: "Seeded/local ecosystem recommendations only. No live Pay, Forecast, or Portfolio service, wallet SDK, payment, prediction, portfolio sync, contract view, or contract send is connected.",
    ecosystemReady: "Ready",
    ecosystemLocked: "Locked",
    ecosystemReview: "Review",
    reviewRequired: "Review required",
    ecosystemCompleted: "Checkpoint",
    ecosystemPrimary: "Primary",
    ecosystemSecondary: "Secondary",
    ecosystemTertiary: "Tertiary",
    ecosystemLoopProgress: "Loop progress",
    ecosystemServiceState: "Service state",
    ecosystemSeededPreview: "Seeded preview",
    ecosystemNotConnected: "Not connected",
    ecosystemSignal: "Campaign signal",
    ended: "Ended",
    evidenceSource: "Evidence source",
    evidenceHashes: "Evidence hashes",
    exportBatch: "Export batch",
    exportEvidence: "Export evidence",
    exportRowStatus: "Export row status",
    fulfillmentOwner: "Reward fulfillment owner",
    failed: "Failed",
    feedTitle: "Campaign Feed",
    feedSubtitle: "Find live aelf campaigns, points, time left, core tasks, and eligibility entry points.",
    feedBoundary: "Local Campaign Discovery API readiness only; no live marketplace, App Hub backend, Portfolio, or Forecast service is connected.",
    ineligible: "Ineligible",
    inviteLink: "Invite link",
    invitedCount: "Raw invites",
    qualifiedInvitees: "Qualified invitees",
    localePreference: "Locale preference",
    leaderboard: "Leaderboard preview",
    messageBoundary: "Wallet connection is limited to connection and message signing in this shell.",
    missingColumns: "Missing columns",
    missingTasks: "Missing tasks",
    myPoints: "My Points",
    myTasks: "My Tasks",
    participantWorkspace: "My Tasks / Points / Referral",
    participantWorkspaceSubtitle: "One workspace for required task progress, seeded points, rank, and qualified referral contribution.",
    participantWorkspaceBoundary: "Seeded/local participant workspace only; no live points ledger, Referral backend, wallet SDK action, contract write, claim, winners export approval, reward custody, or reward distribution is executed.",
    participantSummary: "Participant summary",
    portfolioCampaignHistory: "Portfolio Campaign History",
    portfolioCampaignHistorySubtitle: "Current and historical campaign checkpoints for points, eligibility, wallet, locale, and export review.",
    portfolioActiveCampaigns: "Active / upcoming",
    portfolioHistoricalCampaigns: "Historical",
    portfolioReviewRows: "Review rows",
    portfolioBlockedRows: "Blocked rows",
    portfolioExportReady: "Export ready",
    portfolioTotalPoints: "Portfolio points",
    portfolioState: "Portfolio state",
    portfolioWallet: "Wallet",
    portfolioLocale: "Locale",
    portfolioEligibility: "Eligibility",
    portfolioWinnerExport: "Winner / export",
    portfolioBoundary: "Seeded/local Portfolio campaign history only. No live Portfolio service, Portfolio sync, wallet SDK, contract view/send, export file, reward custody, or reward distribution is connected.",
    pendingTasks: "Pending / ready tasks",
    progressPercent: "Progress percent",
    noEvidenceHashes: "No evidence hashes",
    noMissingTasks: "No missing required tasks",
    noTaskRecords: "No task records",
    nextAction: "Next action",
    noLiveLedger: "Seeded shell preview; points and rank are not a live ledger.",
    pending: "Pending verification",
    points: "Points",
    pointsAwarded: "Points awarded",
    pointsAvailable: "Available points",
    pointsThreshold: "Points threshold",
    evidenceCategory: "Evidence category",
    fallbackReason: "Fallback reason",
    noManualReview: "No manual review",
    noProviderFallback: "No live provider fallback in this seeded preview.",
    providerReadiness: "Provider readiness",
    privateKeySafety: "Campaign OS never asks for private keys or seed phrases.",
    rank: "Rank",
    daysLeft: "days left",
    referral: "Referral context",
    referralSummary: "Referral summary",
    workspaceQualifiedInvitees: "Qualified referrals",
    referralPoints: "Referral points",
    referralValue: "Referral attribution preview only",
    rewards: "Points and ranking",
    rewardBoundary: "Rewards are provided by the campaign project. Export winners does not distribute rewards.",
    riskFlags: "Risk flags",
    riskFlagged: "Risk flagged",
    score: "Score",
    status: "Status",
    start: "Start",
    checkEligibility: "Check eligibility",
    checkAddressEligibility: "Check address eligibility",
    taskList: "Task list",
    taskRecords: "Task records",
    timeWindow: "Time window",
    walletAddress: "Wallet address",
    walletChain: "Chain / network",
    walletLastSeen: "Last seen",
    walletOptions: "Wallet options",
    walletPolicy: "Wallet policy",
    walletSession: "Session",
    walletSessionStatus: "Wallet session status",
    walletSignature: "Signature",
    walletSource: "Wallet source",
    walletType: "Wallet type",
    walletTypeVerified: "Wallet type verified",
    seededWalletBoundary: "Seeded preview only; no live wallet SDK connection or transaction signing is executed.",
    recommended: "Recommended",
    advanced: "Internal/advanced",
    capability: "Capabilities",
    walletGroupAdvanced: "Advanced / Agent",
    walletGroupEoa: "EOA wallets",
    walletGroupRecommended: "Recommended",
    verification: "Verification",
    compatibility: "Wallet compatibility",
    localeReadiness: "Locale readiness",
    recoverMissing: "Complete missing required tasks before export eligibility.",
    ready: "Ready",
    manualReview: "Manual review",
    eligibilityAddress: "Eligibility address",
    checkedAddress: "Checked address",
    seededParticipants: "Seeded participants",
    walletVerification: "Wallet verification",
    verifiedActions: "Verified actions",
    onChainActions: "On-chain actions",
    leaderboardMode: "Leaderboard mode",
    activeMode: "Active mode",
    modeScore: "Mode score",
    rowCount: "Row count",
    qualityPolicy: "Quality policy",
    riskLevel: "Risk level",
    unknownWalletType: "Wallet type remains unknown until supported wallet/session verification.",
    notEligible: "Not eligible",
    riskClear: "No risk flags",
    taskVerification: "Task verification states",
    winnersExportStatus: "Winners export status",
    winnersExportSubtitle: "Participant-facing export row, evidence, and fulfillment boundary.",
} satisfies Record<string, string>;

const zhCN = {
    active: "进行中的活动",
    appHubTitle: "aelf App Hub",
    appHubSubtitle: "移动端入口，聚合活动、积分、Pay、Forecast 与 Portfolio。",
    appHubBoundary: "仅 seeded 移动端 Hub 预览；未接入 Telegram Mini App、支付、Forecast 或 Portfolio 服务。",
    appHubToday: "今日活动",
    appHubGuide: "今天该做什么？",
    appHubGuideText: "当前有进行中的活动任务，以及 1 个资格缺口需要查看。",
    appHubQuickActions: "快捷入口",
    appHubCampaigns: "活动",
    appHubPay: "Pay",
    appHubForecast: "Forecast",
    appHubPortfolio: "Portfolio",
    appHubMe: "我的",
    appHubHome: "首页",
    campaignDetail: "活动详情",
    shareCardReadiness: "分享卡片就绪状态",
    shareCardReadinessSubtitle: "该活动的本地化 URL 与 metadata 预览。",
    shareCanonicalUrl: "Canonical URL",
    shareAlternateUrls: "备用 URL",
    sharePreviewTitle: "预览标题",
    sharePreviewDescription: "预览描述",
    shareFallbackNotice: "回退提示",
    shareFallbackActive: "英文回退",
    shareReadyLocal: "本地预览就绪",
    shareBoundary: "仅本地分享准备度；未接入 SSR、crawler 保证、social API 或分享卡片上传。",
    campaignType: "活动类型",
    comingSoon: "即将开始",
    completed: "已完成",
    completedRequired: "必做进度",
    connectWallet: "连接钱包",
    continueTasks: "继续任务",
    verifyTaskAction: "验证任务",
    retryVerificationAction: "重试验证",
    submitProofAction: "提交证明",
    viewReviewAction: "查看审核队列",
    alreadyVerifiedAction: "已验证",
    latestLocalAction: "最新本地动作",
    localAttempt: "本地尝试",
    proofType: "证明类型",
    noUploadExecuted: "未执行上传",
    localOnlyActionBoundary: "仅本地任务动作；不会调用真实 provider、上传、后端变更、奖励发放或合约写入。",
    noLiveProviderBoundary: "该动作不会调用真实 provider。",
    noRewardDistributionBoundary: "该动作不会批准资格、导出 winners 或发放奖励。",
    localActionStatus: "本地动作状态",
    localValidationFailure: "本地校验失败",
    actionKind: "动作",
    manualQueue: "审核队列",
    contractMode: "合约模式",
    diagnostics: "钱包连接诊断",
    diagnosticsSubtitle: "用于活动钱包 QA 的 seeded AA + EOA 覆盖。",
    diagnosticsTotal: "Seeded 会话",
    diagnosticsVerified: "已验证会话",
    diagnosticsIssues: "问题状态",
    diagnosticsRecommendedReady: "推荐 AA 已就绪",
    diagnosticsEoaReady: "EOA 路径已就绪",
    diagnosticsQa: "钱包 QA 清单",
    diagnosticsScenario: "QA 场景",
    diagnosticsSupported: "支持 EOA；AA 是推荐路径，不是强制要求。",
    diagnosticsNotLive: "诊断是 seeded QA 证据，不是实时钱包连接测试。",
    eligibleCutoff: "入选排名线",
    eligibility: "资格检查器",
    eligible: "符合资格",
    ecosystemNextActions: "生态下一步",
    ecosystemSubtitle: "基于活动进度派生 Pay、Forecast 与 Portfolio 后续行动。",
    ecosystemBoundary: "仅 seeded/本地生态推荐。不会连接真实 Pay、Forecast 或 Portfolio 服务、钱包 SDK、支付、预测、Portfolio 同步、合约读取或合约发送。",
    ecosystemReady: "就绪",
    ecosystemLocked: "锁定",
    ecosystemReview: "审核",
    reviewRequired: "需要审核",
    ecosystemCompleted: "检查点",
    ecosystemPrimary: "主要",
    ecosystemSecondary: "次要",
    ecosystemTertiary: "第三",
    ecosystemLoopProgress: "闭环进度",
    ecosystemServiceState: "服务状态",
    ecosystemSeededPreview: "Seeded 预览",
    ecosystemNotConnected: "未连接",
    ecosystemSignal: "活动信号",
    ended: "已结束",
    evidenceSource: "证据来源",
    evidenceHashes: "证据哈希",
    exportBatch: "导出批次",
    exportEvidence: "导出证据",
    exportRowStatus: "导出行状态",
    fulfillmentOwner: "奖励履约方",
    failed: "失败",
    feedTitle: "活动 Feed",
    feedSubtitle: "展示进行中的 aelf 活动、可获得积分、剩余时间、核心任务与资格入口。",
    feedBoundary: "仅本地 Campaign Discovery API readiness；不会连接实时 marketplace、App Hub 后端、Portfolio 或 Forecast 服务。",
    ineligible: "不符合资格",
    inviteLink: "邀请链接",
    invitedCount: "原始邀请数",
    qualifiedInvitees: "合格被邀请人",
    localePreference: "语言偏好",
    leaderboard: "排行榜预览",
    messageBoundary: "当前 shell 仅展示连接钱包和消息签名边界。",
    missingColumns: "缺失字段",
    missingTasks: "缺失任务",
    myPoints: "我的积分",
    myTasks: "我的任务",
    participantWorkspace: "我的任务 / 积分 / 推荐",
    participantWorkspaceSubtitle: "在一个工作台查看必做任务进度、seeded 积分、排名与合格推荐贡献。",
    participantWorkspaceBoundary: "仅 seeded/本地参与者工作台；不会执行实时 points ledger、Referral 后端、钱包 SDK 动作、合约写入、claim、winners 导出批准、奖励托管或发奖。",
    participantSummary: "参与者摘要",
    portfolioCampaignHistory: "Portfolio 活动历史",
    portfolioCampaignHistorySubtitle: "查看当前与历史活动的积分、资格、钱包、语言与导出审核检查点。",
    portfolioActiveCampaigns: "进行中 / 即将开始",
    portfolioHistoricalCampaigns: "历史活动",
    portfolioReviewRows: "需审核记录",
    portfolioBlockedRows: "阻断记录",
    portfolioExportReady: "导出就绪",
    portfolioTotalPoints: "Portfolio 积分",
    portfolioState: "Portfolio 状态",
    portfolioWallet: "钱包",
    portfolioLocale: "语言",
    portfolioEligibility: "资格",
    portfolioWinnerExport: "获奖 / 导出",
    portfolioBoundary: "仅 seeded/本地 Portfolio 活动历史。不会连接真实 Portfolio 服务、Portfolio 同步、钱包 SDK、合约读取/发送、导出文件、奖励托管或发奖。",
    pendingTasks: "待处理 / 待开始任务",
    progressPercent: "进度百分比",
    noEvidenceHashes: "无证据哈希",
    noMissingTasks: "没有缺失的必做任务",
    noTaskRecords: "无任务记录",
    nextAction: "下一步",
    noLiveLedger: "这是 seeded shell 预览；积分和排名不是实时账本。",
    pending: "等待验证",
    points: "积分",
    pointsAwarded: "已获得积分",
    pointsAvailable: "可获得积分",
    pointsThreshold: "积分门槛",
    evidenceCategory: "Evidence 分类",
    fallbackReason: "回退原因",
    noManualReview: "无人工审核",
    noProviderFallback: "当前 seeded 预览没有真实 provider 回退。",
    providerReadiness: "Provider readiness",
    privateKeySafety: "Campaign OS 永远不会索要私钥或助记词。",
    rank: "排名",
    daysLeft: "天剩余",
    referral: "推荐关系",
    referralSummary: "推荐摘要",
    workspaceQualifiedInvitees: "合格推荐",
    referralPoints: "推荐积分",
    referralValue: "仅展示推荐归因预览",
    rewards: "积分与排名",
    rewardBoundary: "奖励由活动项目方提供。导出 winners 不等于发奖。",
    riskFlags: "风险标记",
    riskFlagged: "风险标记",
    score: "分数",
    status: "状态",
    start: "开始",
    checkEligibility: "检查资格",
    checkAddressEligibility: "检查地址资格",
    taskList: "任务列表",
    taskRecords: "任务记录",
    timeWindow: "活动时间",
    walletAddress: "钱包地址",
    walletChain: "链 / 网络",
    walletLastSeen: "最近活跃",
    walletOptions: "钱包选项",
    walletPolicy: "钱包策略",
    walletSession: "会话",
    walletSessionStatus: "钱包会话状态",
    walletSignature: "签名",
    walletSource: "钱包来源",
    walletType: "钱包类型",
    walletTypeVerified: "钱包类型已验证",
    seededWalletBoundary: "仅 seeded 预览；不会执行实时钱包 SDK 连接或交易签名。",
    recommended: "推荐",
    advanced: "内部/高级",
    capability: "能力",
    walletGroupAdvanced: "高级 / Agent",
    walletGroupEoa: "EOA 钱包",
    walletGroupRecommended: "推荐",
    verification: "验证方式",
    compatibility: "钱包兼容性",
    localeReadiness: "语言就绪状态",
    recoverMissing: "完成缺失的必做任务后再进入导出资格。",
    ready: "待完成",
    manualReview: "人工审核",
    eligibilityAddress: "资格地址",
    checkedAddress: "检查地址",
    seededParticipants: "Seeded 参与者",
    walletVerification: "钱包验证",
    verifiedActions: "已验证行为",
    onChainActions: "链上行为",
    leaderboardMode: "排行榜模式",
    activeMode: "当前模式",
    modeScore: "模式分数",
    rowCount: "行数",
    qualityPolicy: "质量策略",
    riskLevel: "风险等级",
    unknownWalletType: "钱包类型会保持未知，直到通过受支持的钱包/会话验证。",
    notEligible: "不符合资格",
    riskClear: "无风险标记",
    taskVerification: "任务验证状态",
    winnersExportStatus: "Winners 导出状态",
    winnersExportSubtitle: "面向参与者展示导出行、证据与奖励履约边界。",
} satisfies typeof enUS;

export const userAppCopy = {
  "en-US": enUS,
  "zh-CN": zhCN,
  "zh-TW": {
    ...zhCN,
    active: "進行中的活動",
    campaignDetail: "活動詳情",
    feedTitle: "活動 Feed",
    localePreference: "語言偏好",
    localeReadiness: "語言 readiness",
    portfolioCampaignHistory: "Portfolio 活動歷史",
    portfolioCampaignHistorySubtitle: "查看目前與歷史活動的積分、資格、錢包、語言與匯出審核檢查點。",
    portfolioActiveCampaigns: "進行中 / 即將開始",
    portfolioHistoricalCampaigns: "歷史活動",
    portfolioReviewRows: "需審核記錄",
    portfolioBlockedRows: "阻斷記錄",
    portfolioExportReady: "匯出就緒",
    portfolioTotalPoints: "Portfolio 積分",
    portfolioState: "Portfolio 狀態",
    portfolioWallet: "錢包",
    portfolioLocale: "語言",
    portfolioEligibility: "資格",
    portfolioWinnerExport: "獲獎 / 匯出",
    portfolioBoundary: "僅 seeded/本地 Portfolio 活動歷史。未連接即時 Portfolio 服務、Portfolio 同步、錢包 SDK、合約讀取/發送、匯出檔案、獎勵託管或發獎。",
    ready: "就緒",
    seededWalletBoundary: "僅 seeded 預覽；不會執行即時錢包 SDK 連線或交易簽名。",
    verifyTaskAction: "驗證任務",
    retryVerificationAction: "重試驗證",
    submitProofAction: "提交證明",
    viewReviewAction: "查看審核佇列",
    alreadyVerifiedAction: "已驗證",
    latestLocalAction: "最新本地動作",
    localAttempt: "本地嘗試",
    proofType: "證明類型",
    noUploadExecuted: "未執行上傳",
    localOnlyActionBoundary: "僅本地任務動作；不會呼叫即時 provider、上傳、後端變更、獎勵發放或合約寫入。",
    noLiveProviderBoundary: "此動作不會呼叫即時 provider。",
    noRewardDistributionBoundary: "此動作不會核准資格、匯出 winners 或發放獎勵。",
    localActionStatus: "本地動作狀態",
    localValidationFailure: "本地校驗失敗",
    actionKind: "動作",
    manualQueue: "審核佇列",
    shareAlternateUrls: "備用 URL",
    shareBoundary: "僅本地分享準備度；未接入 SSR、crawler 保證、social API 或分享卡片上傳。",
    shareCardReadiness: "分享卡片 readiness",
    shareCardReadinessSubtitle: "此活動的本地化 URL 與 metadata 預覽。",
    shareFallbackActive: "英文回退",
    shareFallbackNotice: "回退提示",
    sharePreviewDescription: "預覽描述",
    sharePreviewTitle: "預覽標題",
    shareReadyLocal: "本地預覽就緒",
    taskVerification: "任務驗證狀態",
  },
} satisfies Record<SupportedLocale, typeof enUS>;

export type UserAppCopy = (typeof userAppCopy)["en-US"];
