import type { SupportedLocale } from "../../../domain";

type BusinessContentLocale = Exclude<SupportedLocale, "ja-JP" | "ko-KR" | "vi-VN" | "id-ID" | "tr-TR" | "es-ES">;

const enUS = {
  active: "Live",
  activeWorkspace: "Active workspace",
  apiSkillApiGroup: "API group",
  apiSkillBoundary: "Seeded/local boundary",
  apiSkillContracts: "API / Skill Contracts",
  apiSkillContractsSubtitle: "Read-only contract registry for future agents and APIs.",
  apiSkillCoveredGroups: "Covered v0.2 fields",
  apiSkillEvidence: "Evidence",
  apiSkillExternalEvidence: "External evidence",
  apiSkillFields: "Fields",
  apiSkillHighRisk: "High risk",
  apiSkillInputFields: "Input fields",
  apiSkillLocalOnly: "Local only",
  apiSkillMissing: "Missing skills",
  apiSkillNextAction: "Next action",
  apiSkillOutputFields: "Output fields",
  apiSkillReadiness: "Readiness",
  apiSkillReview: "Review required",
  apiSkillRisk: "Risk",
  apiSkillTotal: "Total contracts",
  apiUsageAuthKey: "Auth / key",
  apiUsageBillingHandoff: "Billing handoff",
  apiUsageBoundary: "No-live API usage boundary",
  apiUsageCandidates: "API usage candidates",
  apiUsageCommercialModel: "Commercial model",
  apiUsageConsumerTier: "Consumer tier",
  apiUsageEvidence: "Evidence",
  apiUsageHighRisk: "High risk",
  apiUsageLocalReady: "Local ready",
  apiUsageMetering: "Metering",
  apiUsageMissingCandidates: "Missing candidates",
  apiUsageNextAction: "Next action",
  apiUsageNotStarted: "Not started",
  apiUsageOwner: "Owner",
  apiUsageProductionReady: "Production-ready candidates",
  apiUsageQuota: "Quota",
  apiUsageRateLimit: "Rate-limit",
  apiUsageReadiness: "API usage commercialization readiness",
  apiUsageReadinessSubtitle: "Project-owner review of auth, quota, metering, rate-limit, billing handoff, and reward boundaries before any live API usage.",
  apiUsageReviewState: "Review state",
  apiUsageRewardBoundary: "Reward boundary",
  apiUsageSummary: "API usage summary",
  apiUsageTopNextAction: "Top next action",
  apiUsageTotalCandidates: "Total candidates",
  aiContent: "AI content",
  aiContentAiDrafts: "AI drafts",
  aiContentArtifacts: "artifacts",
  aiContentChannel: "Channel",
  aiContentCopyReady: "Copy ready",
  aiContentHumanApproved: "Human approved",
  aiContentHumanReviewRequired: "Human review required",
  aiContentLifecycleAiDraft: "AI draft",
  aiContentLifecycleEdited: "Edited",
  aiContentLifecycleHumanApproved: "Human approved",
  aiContentLifecyclePublishIntent: "Publish intent",
  aiContentLifecycleScheduleIntent: "Schedule intent",
  aiContentNextAction: "Next action",
  aiContentPack: "AI Content Pack",
  aiContentPackSubtitle: "Project-owner review of generated campaign copy, release intent, and quality gates.",
  aiContentPublishBlocked: "Publish blocked",
  aiContentPublishReady: "Publish ready",
  aiContentQualityBlockers: "Quality blockers",
  aiContentQualityGates: "Quality gates",
  aiContentReviewer: "Reviewer",
  aiContentRiskLevel: "Risk level",
  aiContentScheduleReady: "Schedule ready",
  aiContentSummary: "AI Content Pack summary",
  aiContentTotalArtifacts: "Total artifacts",
  aiOptimizationLocalOnlyBoundary: "Local-only boundary",
  aiOptimizationNoAutoExecution: "Review input only; no live AI, automatic risk scoring, export, reward distribution, wallet action, or contract execution.",
  aiOptimizationOwnerSafeNextAction: "Owner-safe next action",
  aiOptimizationRecommendedAction: "Recommended action",
  aiOptimizationReviewInput: "Review input / no auto-execution",
  aiOptimizationSubtitle: "Project-owner-safe recommendation from the seeded/local optimization workflow.",
  aiOptimizationSummary: "AI Optimization summary",
  aiOpsKpiAdoption: "AI Ops KPI Adoption Console",
  aiOpsKpiAdoptionSubtitle: "Seeded/local adoption metrics for AI drafts, accepted content, saved edit time, reports, and adopted suggestions.",
  aiOpsKpiBlocked: "Blocked KPIs",
  aiOpsKpiBoundary: "KPI boundary",
  aiOpsKpiEvidence: "Evidence",
  aiOpsKpiNextAction: "Next action",
  aiOpsKpiOwner: "Owner",
  aiOpsKpiReady: "Ready KPIs",
  aiOpsKpiReadinessBlocked: "Blocked",
  aiOpsKpiReadinessReady: "Ready",
  aiOpsKpiReadinessReviewRequired: "Review required",
  aiOpsKpiReview: "Review KPIs",
  aiOpsKpiSource: "Source",
  aiOpsKpiStrongestSignal: "Strongest signal",
  aiOpsKpiTarget: "Target",
  aiOpsKpiTopNextAction: "Top next action",
  aiOpsKpiTotal: "Total KPIs",
  aiOpsKpiTrend: "Trend",
  aiOpsKpiValue: "Value",
  aiPlanner: "AI Campaign Planner",
  aiPlannerAction: "Review generated brief",
  aiPlannerBlocked: "Blocked",
  aiPlannerBoundary: "Planner boundary",
  aiPlannerConfidence: "Confidence",
  aiPlannerDecisionCounts: "Decision counts",
  aiPlannerDefaultLocale: "Default locale",
  aiPlannerGroupList: "Planner recommendation groups",
  aiPlannerNextAction: "Next action",
  aiPlannerOwner: "Owner",
  aiPlannerReady: "Ready",
  aiPlannerRecommendation: "Recommendation",
  aiPlannerReviewRequired: "Review required",
  aiPlannerState: "Draft brief ready for owner review",
  aiPlannerSupportedLocales: "Supported locales",
  aiPlannerWarning: "Warning",
  analyticsExport: "Analytics and Export",
  analyticsExportAction: "Preview winners export",
  analyticsExportState: "Export preview includes wallet, locale, eligibility, and risk fields",
  advancedAnalyticsActionFamily: "Action family",
  advancedAnalyticsAudience: "Audience",
  advancedAnalyticsBoundary: "Advanced analytics boundary",
  advancedAnalyticsCohorts: "Cohorts",
  advancedAnalyticsCohortSegments: "Cohort segments",
  advancedAnalyticsConversionSignal: "Conversion",
  advancedAnalyticsConverted: "Converted",
  advancedAnalyticsCostEfficiency: "Cost efficiency",
  advancedAnalyticsCostPerVerifiedAction: "Cost per verified action",
  advancedAnalyticsCoverage: "Coverage",
  advancedAnalyticsDay7Retention: "Day 7 retention",
  advancedAnalyticsDay30Retention: "Day 30 retention",
  advancedAnalyticsEvidenceGap: "Evidence gap",
  advancedAnalyticsGap: "Gap",
  advancedAnalyticsNextAction: "Next action",
  advancedAnalyticsOwner: "Owner",
  advancedAnalyticsPremiumReadyReports: "Premium-ready reports",
  advancedAnalyticsPremiumReadiness: "Premium analytics readiness",
  advancedAnalyticsProductConversion: "Product conversion",
  advancedAnalyticsProductConversionRows: "Product conversion rows",
  advancedAnalyticsProductCoverage: "Product coverage",
  advancedAnalyticsQualityNote: "Quality note",
  advancedAnalyticsReadiness: "Advanced Analytics readiness",
  advancedAnalyticsReadinessSubtitle: "Seeded cohort, retention, quality, cost, product conversion, and premium report readiness before live analytics.",
  advancedAnalyticsReadyCohorts: "Ready cohorts",
  advancedAnalyticsRealUserQuality: "Real user quality",
  advancedAnalyticsRealUserQualityScore: "Real user quality score",
  advancedAnalyticsRetentionSignal: "Retention",
  advancedAnalyticsReviewCohorts: "Review cohorts",
  advancedAnalyticsRewardBudget: "Reward budget",
  advancedAnalyticsRiskReview: "Risk review",
  advancedAnalyticsSampleBasis: "Sample basis",
  advancedAnalyticsSummary: "Advanced analytics summary",
  advancedAnalyticsRetentionWindows: "Retention windows",
  advancedAnalyticsVerifiedActions: "Verified actions",
  advancedAnalyticsWalletMix: "Wallet mix",
  contractImpact: "Contract Impact Review",
  contractImpactAction: "Open review notes",
  contractImpactState: "Off-chain MVP mode; no contract migration required",
  contractModeOffChain: "OFF CHAIN MVP",
  contractMode: "Contract mode",
  countBlockers: "blockers",
  countPassed: "passed",
  countWarnings: "warnings",
  completionRate: "Completion rate",
  connectedWallets: "Connected wallets",
  closeoutAiRetrospective: "AI retrospective",
  closeoutAiRetrospectiveBoundary: "AI retrospective boundary",
  closeoutBlockedGates: "Blocked gates",
  closeoutBoundary: "Closeout boundary",
  closeoutEvidence: "Evidence",
  closeoutFinalArchive: "Final archive",
  closeoutGateList: "Closeout gates",
  closeoutGeneratedAt: "Generated at",
  closeoutHealthSummary: "Health summary",
  closeoutHumanReviewRequired: "Human review required",
  closeoutLocalOnlyGates: "Local-only gates",
  closeoutNextAction: "Next action",
  closeoutNextIterationActions: "Next iteration actions",
  closeoutOwner: "Owner",
  closeoutReason: "Reason",
  closeoutReadyGates: "Ready gates",
  closeoutRetrospective: "Post-campaign retrospective",
  closeoutRetrospectiveSubtitle: "Seeded/local closeout review for analytics, AI winner report, export readiness, risk, archive evidence, and next-campaign actions.",
  closeoutReviewGates: "Review gates",
  closeoutRewardBoundary: "Reward responsibility",
  closeoutRiskPosture: "Risk posture",
  closeoutStatus: "Closeout status",
  closeoutSummary: "Closeout summary",
  closeoutTotalGates: "Total gates",
  closeoutVerifiedActionEvidence: "Verified-action evidence",
  closeoutWinnerReport: "Winner report",
  dashboardTitle: "Project Console",
  dashboardSubtitle: "Operational snapshot for the active campaign shell.",
  exportReady: "Export-ready winners",
  exportDisclaimer: "Export winners does not distribute rewards.",
  daippTaskBlocked: "Blocked",
  daippTaskBoundary: "No-live daipp boundary",
  daippTaskEvidence: "Evidence",
  daippTaskNextAction: "Next action",
  daippTaskOwner: "Owner",
  daippTaskProviderState: "Provider state",
  daippTaskReadiness: "daipp Agent Coin task readiness",
  daippTaskReadinessSubtitle: "Seeded/local readiness for agent page visit, agent interaction, coin buy/hold, intro share, and launch leaderboard tasks before live daipp integration.",
  daippTaskReady: "Ready",
  daippTaskReviewRequired: "Review required",
  daippTaskRiskState: "Risk state",
  daippTaskTotal: "daipp task paths",
  forestTaskBlocked: "Blocked",
  forestTaskBoundary: "No-live Forest NFT boundary",
  forestTaskEvidence: "Evidence",
  forestTaskNextAction: "Next action",
  forestTaskOwner: "Owner",
  forestTaskProviderState: "Provider state",
  forestTaskReadiness: "Forest NFT task readiness",
  forestTaskReadinessSubtitle: "Seeded/local readiness for NFT mint, holder evidence, trade/listing, and holder leaderboard tasks before live Forest integration.",
  forestTaskReady: "Ready",
  forestTaskReviewRequired: "Review required",
  forestTaskRiskState: "Risk state",
  forestTaskTotal: "NFT task paths",
  ebridgeTaskBlocked: "Blocked",
  ebridgeTaskBoundary: "No-live eBridge task boundary",
  ebridgeTaskEvidence: "Evidence",
  ebridgeTaskNextAction: "Next action",
  ebridgeTaskOwner: "Owner",
  ebridgeTaskProviderState: "Provider state",
  ebridgeTaskReadiness: "eBridge task readiness",
  ebridgeTaskReadinessSubtitle: "Seeded/local readiness for bridge intent, amount threshold, on-chain evidence, Awaken unlock dependency, and eligibility impact before live eBridge integration.",
  ebridgeTaskReady: "Ready",
  ebridgeTaskReviewRequired: "Review required",
  ebridgeTaskRiskState: "Risk state",
  ebridgeTaskTotal: "eBridge task paths",
  awakenTaskBlocked: "Blocked",
  awakenTaskBoundary: "No-live Awaken task boundary",
  awakenTaskEvidence: "Evidence",
  awakenTaskNextAction: "Next action",
  awakenTaskOwner: "Owner",
  awakenTaskProviderState: "Provider state",
  awakenTaskReadiness: "Awaken swap / liquidity task readiness",
  awakenTaskReadinessSubtitle: "Seeded/local readiness for Awaken swap, add liquidity, LP hold evidence, bridge unlock dependency, and ranking eligibility impact before live Awaken integration.",
  awakenTaskReady: "Ready",
  awakenTaskReviewRequired: "Review required",
  awakenTaskRiskState: "Risk state",
  awakenTaskTotal: "Awaken task paths",
  schrodingerTaskBlocked: "Blocked",
  schrodingerTaskBoundary: "No-live Schrödinger NFT boundary",
  schrodingerTaskEvidence: "Evidence",
  schrodingerTaskNextAction: "Next action",
  schrodingerTaskOwner: "Owner",
  schrodingerTaskProviderState: "Provider state",
  schrodingerTaskReadiness: "Schrödinger NFT task readiness",
  schrodingerTaskReadinessSubtitle: "Seeded/local readiness for NFT adopt, holder evidence, trade/listing, and holder leaderboard tasks before live Schrödinger integration.",
  schrodingerTaskReady: "Ready",
  schrodingerTaskReviewRequired: "Review required",
  schrodingerTaskRiskState: "Risk state",
  schrodingerTaskTotal: "Schrödinger task paths",
  forecastTaskBlocked: "Blocked",
  forecastTaskBoundary: "No-live boundary",
  forecastTaskEvidence: "Evidence",
  forecastTaskNextAction: "Next action",
  forecastTaskOwner: "Owner",
  forecastTaskProviderState: "Provider state",
  forecastTaskReadiness: "Forecast campaign task readiness",
  forecastTaskReadinessSubtitle: "Seeded/local readiness for prediction participation, win streak, and Forecast leaderboard tasks before live integration.",
  forecastTaskReady: "Ready",
  forecastTaskReviewRequired: "Review required",
  forecastTaskRiskState: "Risk state",
  forecastTaskTotal: "Task paths",
  payTaskBlocked: "Blocked",
  payTaskBoundary: "No-live Pay boundary",
  payTaskNextAction: "Next action",
  payTaskOwner: "Owner",
  payTaskProviderState: "Provider state",
  payTaskReadiness: "Pay campaign task readiness",
  payTaskReadinessSubtitle: "Seeded/local readiness for invoice completion, payment link completion, and Pay follow-up handoff before live integration.",
  payTaskReady: "Ready",
  payTaskReviewRequired: "Review required",
  payTaskRiskState: "Risk state",
  payTaskTotal: "Task paths",
  tmrwdaoTaskBlocked: "Blocked",
  tmrwdaoTaskBoundary: "No-live governance boundary",
  tmrwdaoTaskEvidence: "Evidence",
  tmrwdaoTaskNextAction: "Next action",
  tmrwdaoTaskOwner: "Owner",
  tmrwdaoTaskProviderState: "Provider state",
  tmrwdaoTaskReadiness: "TMRWDAO governance task readiness",
  tmrwdaoTaskReadinessSubtitle: "Seeded/local readiness for DAO join, proposal summary, proposal vote evidence, and governance result review before live DAO integration.",
  tmrwdaoTaskReady: "Ready",
  tmrwdaoTaskReviewRequired: "Review required",
  tmrwdaoTaskRiskState: "Risk state",
  tmrwdaoTaskTotal: "Governance task paths",
  localeCoverage: "Locale coverage",
  localeAnalyticsReadiness: "Locale analytics readiness",
  localeAnalyticsReadinessSubtitle: "Seeded readiness rows by MVP locale before real analytics wiring.",
  localeAnalyticsMetric: "Metric",
  localeAnalyticsValue: "Value",
  localeAnalyticsBoundary: "Local readiness only. No live analytics SDK, event ingestion, crawler service, or external dashboard is connected.",
  lifecycleAllowed: "Allowed",
  lifecycleBlocked: "Blocked",
  lifecycleBlockingChecks: "Blocking checks",
  lifecycleCurrentStatus: "Current status",
  lifecycleCurrentStatusDetail: "Derived from the active seeded campaign shell.",
  lifecycleExportSensitive: "Export-sensitive operations",
  lifecycleExportSensitiveDetail: "Export and archive intents stay review-first.",
  lifecycleGateGroup: "Gate group",
  lifecycleLaunchBlockers: "launch blockers",
  lifecycleLocalOnlyBoundary: "Lifecycle local-only boundary",
  lifecycleNotApplicable: "Not applicable",
  lifecycleOperationCount: "lifecycle operations",
  lifecycleOperations: "Lifecycle operations",
  lifecycleOperationsEyebrow: "Campaign lifecycle",
  lifecycleOperationsSubtitle: "Owner-safe status operations for launch, schedule, export, and archive decisions.",
  lifecycleOwner: "Owner",
  lifecycleOwnerAction: "Owner action",
  lifecycleReviewRequired: "Review required",
  lifecycleSummary: "Lifecycle operations summary",
  lifecycleTopNextAction: "Top next action",
  launchConsoleAudience: "Audience",
  launchConsoleBlocked: "Blocked",
  launchConsoleBoundary: "No-live boundary",
  launchConsoleCampaignIntent: "Campaign intent",
  launchConsoleGateEvidence: "Gate evidence",
  launchConsoleHandoffRequired: "Handoff required",
  launchConsoleHandoffs: "Skill handoffs",
  launchConsoleLaunchBlocking: "Launch blocking",
  launchConsoleLocalOnly: "Local only",
  launchConsoleNextAction: "Next action",
  launchConsoleNoLiveBoundary: "Seeded/local preview only. No live Launch Console, no automatic campaign creation or publish, no external API, wallet signing, contract write, export file, or reward distribution is executed.",
  launchConsoleOwner: "Owner",
  launchConsoleReady: "Ready",
  launchConsoleRecommendedTiming: "Timing",
  launchConsoleReviewRequired: "Review required",
  launchConsoleStage: "Stage",
  launchConsoleSummary: "Bundle summary",
  launchConsoleTaskCategoryContentAnalytics: "Content / analytics",
  launchConsoleTaskCategoryOnChainApi: "On-chain / API",
  launchConsoleTaskCategorySocialManual: "Social / manual",
  launchConsoleTaskCategoryWallet: "Wallet",
  launchConsoleTasks: "Task blocks",
  launchConsoleBundles: "Launch Console campaign bundles",
  launchConsoleBundlesSubtitle: "Seeded/local launch packages for pre-launch, launch, and post-launch review before any live Launch Console handoff.",
  launchConsoleTotalBundles: "Total bundles",
  aiPlannerLaunchApprovalRoutes: "Approval routes",
  aiPlannerLaunchBoundary: "Launch boundary",
  aiPlannerLaunchDecision: "AI Planner Launch Decision",
  aiPlannerLaunchDecisionItems: "Launch decisions",
  aiPlannerLaunchDecisionSubtitle: "Actionable local review package for selected tasks, inherited publish gates, owner routes, and no-auto-publish boundaries.",
  aiPlannerLaunchInheritedGateCount: "Inherited gates",
  aiPlannerLaunchInheritedGates: "Inherited publish gates",
  aiPlannerLaunchLocaleReadiness: "Locale readiness",
  aiPlannerLaunchPoints: "Points",
  aiPlannerLaunchSelectedTaskCount: "Selected tasks",
  aiPlannerLaunchSelectedTasks: "Selected task templates",
  aiPlannerLaunchSelectedTemplate: "Selected campaign preset",
  aiPlannerLaunchSelectedTemplateCount: "Selected preset",
  aiPlannerLaunchVerification: "Verification",
  aiPlannerLaunchWalletCompatibility: "Wallet compatibility",
  aiPlannerLaunchBlocksPublish: "Blocks publish",
  campaignCreationWorkflowReadiness: "Campaign Creation Workflow Readiness",
  campaignCreationWorkflowSubtitle: "Ordered seeded/local readiness for the v0.2 Create Campaign flow before any live creation or publish.",
  campaignCreationWorkflowStepList: "Creation workflow steps",
  campaignCreationWorkflowReadySteps: "Ready steps",
  campaignCreationWorkflowReviewSteps: "Review steps",
  campaignCreationWorkflowWarningSteps: "Warning steps",
  campaignCreationWorkflowBlockedSteps: "Blocked steps",
  campaignCreationWorkflowInheritedGates: "Inherited gates",
  campaignCreationWorkflowBoundary: "Creation boundary",
  campaignCreationWorkflowEvidence: "Evidence",
  campaignCreationWorkflowBlockers: "Blockers",
  campaignCreationWorkflowWarnings: "Warnings",
  campaignCreationWorkflowNoIssues: "No inherited blockers or warnings",
  campaignCreationWorkflowSourceChecklist: "Source checklist",
  readiness: "Publish readiness",
  riskQueue: "Risk review queue",
  taskCount: "configured tasks",
  rewardsEligibility: "Rewards & Eligibility",
  rewardsEligibilityAction: "Check participant eligibility",
  rewardsEligibilityState: "Eligibility preview separates missing tasks and risk flags",
  taskBuilder: "Task Builder Preview",
  taskBuilderAction: "Review task compatibility",
  taskBuilderState: "Wallet-aware tasks cover AA, EOA, and any-wallet participation",
  translationReview: "i18n Translation Review",
  translationReviewAction: "Review Chinese draft",
  translationReviewState: "English is published; Chinese remains AI draft/fallback",
  walletSplit: "AA / EOA split",
  walletAdapterReadiness: "aelf-web-login adapter readiness",
  walletAdapterReadinessSubtitle: "AA and EOA wallet adapter readiness before live SDK wiring.",
  walletAdapterConfigured: "Configured adapters",
  walletAdapterEnabledPreview: "Enabled preview",
  walletAdapterMaintenance: "Maintenance",
  walletAdapterMissingLiveEvidence: "Missing live evidence",
  walletAdapterReleaseBlockers: "Release blockers",
  walletAdapterFeatureGate: "Feature gate",
  walletAdapterFallback: "Fallback",
  walletAdapterNextAction: "Next action",
  walletAdapterBoundary: "No live wallet SDK boundary",
  liveWalletConnectorBoundary: "Live wallet connector boundary",
  liveWalletConnectorBoundaryEyebrow: "Connector boundary",
  liveWalletConnectorBoundarySubtitle: "Disabled-by-default connector package candidates before live wallet SDK execution.",
  liveWalletConnectorCandidates: "Connector candidates",
  liveWalletConnectorDisabledReviewRequired: "Disabled / review-required",
  liveWalletConnectorMissingEvidence: "Missing live evidence",
  liveWalletConnectorConfigRequired: "Configuration gate required",
  liveWalletConnectorReviewApprovalRequired: "Live QA and review approval required",
  liveWalletConnectorReleaseGuardrail: "No production enablement in this mission",
  liveWalletConnectorPackage: "Candidate package",
  zhFallbackWarning: "Chinese content falls back to English until reviewed.",
  warning: "Warning",
  blocker: "Blocker",
  builderAiOutline: "AI generated outline",
  builderAiPrompt: "AI prompt",
  builderAnyWalletDefault: "Default recommended",
  builderCompleteness: "Draft completeness",
  builderCompletenessSummary: "Basics are complete; contract and risk checks remain visible before publish.",
  builderEntryAction: "Open builder draft",
  builderEntryState: "Draft setup combines AI brief and structured campaign fields",
  builderEntryTitle: "Campaign Builder",
  builderFormState: "Structured form state",
  builderLocaleScope: "Locale scope",
  builderLocaleScopeDetail: "Default and fallback: en-US. Supported: en-US, zh-CN, and zh-TW fallback readiness.",
  builderMissingBasics: "Missing required basics",
  builderNoMissingBasics: "No missing basics",
  builderOverview: "Draft overview",
  builderObjective: "Objective",
  builderProject: "Project",
  builderTargetUsers: "Target users",
  builderTimePeriod: "Time period",
  builderWalletPolicy: "Wallet policy",
  campaignTemplatePackBoundary: "Seeded/local campaign presets only: no live provider verification, automatic campaign creation, automatic publish, reward custody, or reward distribution.",
  campaignTemplatePackNextAction: "Next action",
  campaignTemplatePackOwner: "Owner",
  campaignTemplatePackReadiness: "Readiness",
  campaignTemplatePackReviewRequired: "Review required",
  campaignTemplatePackRewardBoundary: "Reward boundary",
  campaignTemplatePackReady: "Ready",
  campaignTemplatePackSubtitle: "Campaign-level presets for the first aelf-native campaign templates; each preset keeps human review and reward responsibility visible before drafting.",
  campaignTemplatePackSuitableFor: "Suitable for",
  campaignTemplatePackTaskSequence: "Task sequence",
  campaignTemplatePackTitle: "Campaign Template Pack",
  campaignTemplatePackTotal: "Templates",
  campaignTemplatePackWalletPolicy: "Wallet policy",
  commandCenter: "Campaign Command Center",
  commandCenterSubtitle: "Project-owner view of campaign states, risk, export readiness, and next actions.",
  commandCenterSummary: "Campaign portfolio",
  commandCampaigns: "campaigns",
  commandLive: "Live",
  commandScheduledDraft: "Scheduled / draft",
  commandEnded: "Ended",
  commandExported: "Exported",
  commandWarnings: "Warnings",
  commandBlockers: "Blockers",
  commandNextAction: "Owner action",
  commandPriority: "Priority",
  commandRisk: "Risk",
  commandExport: "Export",
  commandTimeWindow: "Time window",
  commandLocale: "Locale",
  commandWallet: "Wallet split",
  portfolioCommercialReadiness: "Project portfolio readiness",
  portfolioCommercialSubtitle: "Seeded portfolio metrics and commercial model readiness before any live billing or reward operation.",
  portfolioCommercialSummary: "Portfolio summary",
  portfolioCommercialMetrics: "Portfolio metrics",
  portfolioCommercialModels: "Commercial readiness",
  portfolioCommercialTopNextAction: "Top next action",
  portfolioCommercialRewardBoundary: "Reward boundary",
  portfolioCommercialOwner: "Owner",
  portfolioCommercialEvidence: "Evidence",
  portfolioCommercialNextAction: "Next action",
  portfolioCommercialProductionReady: "Production-ready models",
  createStepContract: "Contract",
  createStepGoal: "Goal",
  createStepI18n: "i18n",
  createStepPrefix: "Step",
  createStepPublishReadiness: "Publish readiness",
  createStepRewardsEligibility: "Rewards & Eligibility",
  createStepTasks: "Tasks",
  createDraftActiveLocales: "Active draft locales",
  createDraftAiAssistedMode: "AI assisted mode",
  createDraftCampaignName: "Campaign name",
  createDraftComposer: "Local campaign draft composer",
  createDraftComposerTitle: "Editable campaign draft",
  createDraftEndDate: "End date",
  createDraftFormMode: "Form mode",
  createDraftGenerateOutline: "Generate local outline",
  createDraftHumanReviewAcknowledged: "Human reviewed",
  createDraftHumanReviewRequired: "Human review required",
  createDraftLocalBoundary: "Local draft only: no live AI provider, automatic publish, live campaign creation, backend mutation, wallet signature, contract execution, export generation, reward custody, or reward distribution.",
  createDraftMode: "Creation mode",
  createDraftOutlinePreview: "Generated outline preview",
  createDraftProjectName: "Project name",
  createDraftReset: "Reset to Awaken baseline",
  createDraftReviewAcknowledgement: "Human review acknowledged",
  createDraftStartDate: "Start date",
  createDraftSupportedLocales: "Supported locales",
  createDraftTargetUsers: "Target users",
  createDraftTaskTemplates: "Task template selection",
  createDraftTaskTemplatesSummary: "Selections update the local draft, readiness gates, and launch decision preview.",
  createDraftWalletPolicy: "Wallet policy",
  createWorkspaceStepper: "Create campaign checkpoints",
  createWorkspaceStepperSummary: "Project-owner checkpoints for goal, task, reward, locale, contract, and publish readiness review.",
  analyticsExportDecision: "Analytics & Export Decision",
  analyticsExportDecisionSubtitle: "Owner-facing quality metrics before approving winner export.",
  dropOffPoint: "Largest drop-off",
  readyRows: "Ready rows",
  reviewRequiredRows: "Review-required rows",
  blockedRows: "Blocked rows",
  rowStatusCounts: "Row status counts",
  exportBatch: "Export batch",
  exportAcknowledgements: "acknowledgements",
  csvColumns: "CSV columns",
  evidenceCoverage: "Evidence coverage",
  exportConfirmationReadiness: "Export confirmation readiness",
  exportConfirmationReadinessEyebrow: "Seeded/local export gate",
  exportConfirmationReadinessSubtitle: "Preview modes, required fields, row reasons, acknowledgements, and root blockers before owner approval.",
  exportConfirmationSummary: "Export confirmation summary",
  exportContractRootReadiness: "Contract root readiness",
  exportCoveredFields: "Covered fields",
  exportIncludedFields: "Included fields",
  exportArtifact: "Local export artifact",
  exportArtifactBatchId: "Artifact batch",
  exportArtifactBoundary: "Local artifact only: no download URL, no storage write, no contract root, no contract transaction, no reward custody, and no reward distribution.",
  exportArtifactChecksum: "Checksum",
  exportArtifactFormat: "Artifact format",
  exportArtifactNoContractRoot: "No contract root",
  exportArtifactNoDownloadUrl: "No download URL",
  exportArtifactNoRewardDistribution: "No reward distribution",
  exportArtifactNoStorageWrite: "No storage write",
  exportArtifactPayloadSize: "Payload bytes",
  exportArtifactRows: "Artifact rows",
  exportFulfillmentAcknowledgementState: "Approval state",
  exportFulfillmentBoundary: "Local handoff boundary",
  exportFulfillmentChecksum: "Checksum",
  exportFulfillmentFutureStorage: "Future storage-backed export",
  exportFulfillmentIncludedColumns: "Included columns",
  exportFulfillmentNextAction: "Local handoff next action",
  exportFulfillmentNoContractRoot: "No contract root",
  exportFulfillmentNoDownloadUrl: "No download URL",
  exportFulfillmentNoRewardDistribution: "No reward distribution",
  exportFulfillmentNoStorageWrite: "No storage write",
  exportFulfillmentOwnerApproved: "Owner approved",
  exportFulfillmentPackageId: "Package id",
  exportFulfillmentPackages: "Local package readiness",
  exportFulfillmentPayloadBytes: "Payload bytes",
  exportFulfillmentReadiness: "Export fulfillment readiness",
  exportFulfillmentReadinessSubtitle: "Project-owner handoff state for local CSV and JSON packages before any storage-backed download.",
  exportFulfillmentRows: "Ready / review / blocked rows",
  exportFulfillmentSafety: "Safety boundaries",
  exportFulfillmentStatus: "Handoff status",
  exportStorageProviderSummary: "Storage provider approval summary",
  exportStorageProviderSummarySubtitle: "Compact project-owner view of the blocked production storage path. Local CSV/JSON handoff remains the available export path.",
  exportStorageProviderTopBlocker: "Top storage blocker",
  exportStorageProviderNextAction: "Safe next action",
  exportStorageProviderStorageWriteDisabled: "Storage write enabled = false",
  exportStorageProviderDownloadUrlDisabled: "Download URL enabled = false",
  exportStorageProviderNoContractRootWrite: "Contract root/write enabled = false",
  exportStorageProviderRewardCustodyDisabled: "Reward custody enabled = false",
  exportStorageProviderRewardDistributionDisabled: "Reward distribution enabled = false",
  exportStorageProviderLocalHandoff: "Local CSV/JSON handoff remains available",
  exportStorageProviderBoundary: "Production storage boundary",
  exportStorageProviderApprovalBlocked: "Production storage approval blocked",
  exportLocalPreviewOnly: "Local preview only",
  exportMissingFields: "Missing fields",
  exportPreviewModes: "CSV / JSON preview modes",
  exportProjectAcknowledgements: "Project acknowledgements",
  exportRealFile: "Real file",
  exportRequiredFields: "Required export fields",
  exportRootClaimBlocked: "Root and claim execution blockers",
  exportRowReasonCoverage: "Row reason coverage",
  exportSafeDefault: "Safe default: no contract root",
  exportTotalRows: "total rows",
  exportWorkspaceDecision: "Export Decision",
  exportWorkspaceDecisionSubtitle: "Seeded export preview for verified rows, CSV contract, evidence coverage, and reward responsibility.",
  providerEvidenceRegistry: "Provider evidence registry",
  providerEvidenceRegistrySubtitle: "Adapter readiness, feature gates, fallbacks, and launch blockers before live provider wiring.",
  providerRegistryTotalEntries: "Registry entries",
  providerRegistryMissingLiveEvidence: "Missing live evidence",
  providerRegistryLocalOnly: "Local-only paths",
  providerRegistryReviewRequired: "Review-required paths",
  providerRegistryUnavailable: "Unavailable paths",
  providerRegistryBlocked: "Blocked paths",
  providerRegistryLaunchBlockers: "Launch blockers",
  providerRegistryFeatureGate: "Feature gate",
  providerRegistryFallback: "Fallback",
  providerRegistryAdapterReadiness: "Adapter readiness",
  providerRegistryUnavailableReadiness: "Unavailable",
  providerRegistryBlockedReadiness: "Blocked",
  providerRegistryLocalOnlyBoundary: "Seeded/local provider evidence only",
  participantAccount: "Account",
  participantBlocked: "Blocked",
  participantEligible: "Eligible",
  participantExportPosture: "Export posture",
  participantExportReady: "Export-ready",
  participantExportStatus: "Export status",
  participantLocale: "Locale",
  participantLocaleMix: "Locale mix",
  participantNextAction: "Next action",
  participantNoRiskFlags: "No risk flags",
  participantOperations: "Participant operations",
  participantOperationsSubtitle: "Seeded/local participant review by wallet, locale, task progress, risk, and export posture.",
  participantPending: "Pending",
  participantReviewRequired: "Review required",
  participantRewardBoundary: "Reward boundary",
  participantRiskFlags: "Risk flags",
  participantRowList: "Participant rows",
  participantSummary: "Participant summary",
  participantTaskProgress: "Task progress",
  participantWalletMix: "Wallet mix",
  participantWalletSource: "Wallet source",
  pointsRankingReferralBlocked: "Blocked",
  pointsRankingReferralBoundary: "Service boundary",
  pointsRankingReferralEvidence: "Evidence",
  pointsRankingReferralLaneList: "Readiness lanes",
  pointsRankingReferralLocalOnly: "Local only",
  pointsRankingReferralNextAction: "Next action",
  pointsRankingReferralOwner: "Owner",
  pointsRankingReferralQualifiedInvitees: "Qualified invitees",
  pointsRankingReferralRawInvites: "Raw invites",
  pointsRankingReferralReady: "Ready",
  pointsRankingReferralReadiness: "Points / Ranking / Referral Service Readiness",
  pointsRankingReferralReferralPoints: "Referral points",
  pointsRankingReferralReviewRequired: "Review required",
  pointsRankingReferralSource: "Source",
  pointsRankingReferralSubtitle: "Seeded/local readiness for points ledger, off-chain ranking, referral qualification, and Pixiepoints/backend handoff.",
  pointsRankingReferralSummary: "Service readiness summary",
  pointsRankingReferralTotalLanes: "Total lanes",
  settingsBlockedGroups: "Blocked groups",
  settingsCurrentValue: "Current value",
  settingsEvidence: "Evidence",
  settingsGroupList: "Settings groups",
  settingsNextAction: "Next action",
  settingsOwner: "Owner",
  settingsReadiness: "Settings readiness",
  settingsReadinessSubtitle: "Read-only campaign settings readiness before any live mutation or backend save.",
  settingsReadOnlyBoundary: "Read-only / no live mutation boundary",
  settingsReadyGroups: "Ready groups",
  settingsReviewGroups: "Review groups",
  settingsSummary: "Settings summary",
  settingsTotalGroups: "Total groups",
  eligible: "Eligible",
  ineligible: "Ineligible",
  missingTask: "Missing task",
  open: "Open",
  approved: "Approved",
  published: "published",
  aiDraft: "AI draft",
  apiSkillReadinessBlocked: "Blocked",
  apiSkillReadinessLocalOnly: "Local only",
  apiSkillReadinessReady: "Ready",
  apiSkillReadinessReviewRequired: "Review required",
  reviewed: "reviewed",
  fallback: "fallback",
  formObjective: "Objective confirmed",
  formReward: "Reward plan confirmed",
  formTimeline: "Timeline confirmed",
  formWallet: "Wallet policy confirmed",
  serviceBoundaryDetail: "No live backend/API, wallet signature, secret storage, real export file, reward distribution, or contract root write.",
  serviceBoundaryTitle: "Seeded/local boundary",
  serviceCoverage: "Service coverage",
  serviceCoveredApiGroups: "Covered API groups",
  serviceCoveredFieldGroups: "Covered field groups",
  serviceFacade: "Local API Service Facade",
  serviceFacadeSubtitle: "Callable seeded/local service surface for v0.2 API and UI coverage.",
  serviceReadinessBlocked: "Blocked",
  serviceReadinessLocalOnly: "Local only",
  serviceReadinessReady: "Ready",
  serviceReadinessReviewRequired: "Review required",
  serviceSampleResponses: "Sample responses",
  serviceTotalServices: "Total services",
  verificationPipelineAffectedOutcomes: "Affected outcomes",
  verificationPipelineBlockedPaths: "Blocked paths",
  verificationPipelineCompleted: "Completed",
  verificationPipelineEligibilityImpact: "Eligibility impact",
  verificationPipelineFailed: "Failed",
  verificationPipelineFallbackReason: "Fallback reason",
  verificationPipelineLiveEvidence: "Live evidence",
  verificationPipelineLiveReady: "Live ready",
  verificationPipelineManualReviewPaths: "Manual review paths",
  verificationPipelineMissingLiveEvidence: "Missing live evidence",
  verificationPipelineMissingRequiredTasks: "Missing required tasks",
  verificationPipelineNextAction: "Operator next action",
  verificationPipelineNone: "None",
  verificationPipelinePending: "Pending",
  verificationPipelineReadiness: "Verification pipeline readiness",
  verificationPipelineReadinessSubtitle: "Provider readiness, task outcomes, eligibility impact, and non-live boundaries for launch review.",
  verificationPipelineReferralQualification: "Referral qualification",
  verificationPipelineReleaseImpact: "Release impact",
  verificationPipelineRiskFlags: "Risk flags",
  verificationPipelineSeededCoverage: "Seeded/local coverage",
  verificationPipelineSeededReady: "Seeded ready",
  verificationPipelineTaskOutcomeCoverage: "Task outcome coverage",
  verificationPipelineTotalPaths: "Total paths",
  projectWorkspace: "Project Console workspace",
  projectWorkspaceNavigation: "Project Console workspace navigation",
  stateComponentsBoundary: "State gallery boundary",
  stateComponentsBlocked: "Blocked states",
  stateComponentsCovered: "Covered states",
  stateComponentsDescription: "Description",
  stateComponentsDeliveryGallery: "State Components Delivery Gallery",
  stateComponentsExamples: "Representative states",
  stateComponentsFamilies: "State families",
  stateComponentsMeaning: "Meaning",
  stateComponentsMessage: "Message",
  stateComponentsNextAction: "Next action",
  stateComponentsOwner: "Owner",
  stateComponentsReadiness: "Readiness",
  stateComponentsReviewRequired: "Review-required states",
  stateComponentsSource: "Source",
  stateComponentsSourceReferences: "Source references",
  stateComponentsSubtitle: "Seeded/local state coverage for loading, empty, error, toast, modal, blocked publish, campaign, task, eligibility, i18n, wallet QA, and export review.",
  stateComponentsTopNextAction: "Top next action",
  stateReadinessBlocked: "Blocked",
  stateReadinessCovered: "Covered",
  stateReadinessReviewRequired: "Review required",
  templatesWorkspaceBoundary: "Template selection stays local and preserves wallet compatibility, verification type, and locale readiness signals.",
  verificationBoundary: "Verification boundary",
  verificationCoverage: "Verification coverage",
  verificationEvidenceCategories: "Evidence categories",
  verificationManualReview: "Manual review",
  verificationProviderReadiness: "Provider readiness",
  verificationRulesAffectedOutcomes: "Affected outcome types",
  verificationRulesProviderEvidence: "Verification provider evidence",
  verificationRulesProviderLaunchBlockers: "Provider launch blockers",
  verificationRulesSummary: "Verification rules summary",
  verificationRulesTopRule: "Top rule",
  verificationRiskStates: "Risk-sensitive states",
  workspaceAiContent: "AI Content",
  workspaceAiContentSummary: "Review generated content, optimization recommendations, human approval state, and no-auto-publish boundaries.",
  workspaceAnalytics: "Analytics",
  workspaceAnalyticsSummary: "Inspect seeded KPIs, funnel drop-off, wallet split, locale split, and locale analytics readiness.",
  workspaceCampaigns: "Campaigns",
  workspaceCampaignsSummary: "Monitor portfolio state, active campaign metrics, risk, export readiness, and owner next actions.",
  workspaceCloseout: "Closeout",
  workspaceCloseoutSummary: "Review post-campaign analytics, AI winner report, export readiness, risk, reward ownership, archive state, and next-campaign actions.",
  workspaceCreate: "Create",
  workspaceCreateSummary: "Create and review campaign drafts through goal, task, reward, i18n, contract, and publish checkpoints.",
  workspaceExport: "Export",
  workspaceExportSummary: "Review verified export rows, CSV columns, evidence coverage, API contracts, and reward responsibility.",
  workspaceParticipants: "Participants",
  workspaceParticipantsSummary: "Review participant eligibility, task progress, risk flags, wallet mix, and export posture without reward distribution.",
  workspaceSettings: "Settings",
  workspaceSettingsSummary: "Inspect read-only wallet, contract, reward, i18n, verification, export, and publish settings readiness.",
  workspaceStates: "States",
  workspaceStatesSummary: "Audit state component coverage, recovery actions, source references, and no-live boundaries in one place.",
  workspaceTemplates: "Templates",
  workspaceTemplatesSummary: "Choose wallet-aware task templates with verification and language readiness context.",
  workspaceVerificationRules: "Verification Rules",
  workspaceVerificationRulesSummary: "Review on-chain, API, manual-review, referral, provider evidence, release impact, and no-live boundaries.",
} satisfies Record<string, string>;

const zhCN = {
  active: "进行中",
  activeWorkspace: "当前工作区",
  apiSkillApiGroup: "API 分组",
  apiSkillBoundary: "Seeded/本地边界",
  apiSkillContracts: "API / Skill Contracts",
  apiSkillContractsSubtitle: "面向未来 agent 与 API 的只读 contract registry。",
  apiSkillCoveredGroups: "已覆盖 v0.2 字段",
  apiSkillEvidence: "Evidence",
  apiSkillExternalEvidence: "外部 evidence",
  apiSkillFields: "字段",
  apiSkillHighRisk: "高风险",
  apiSkillInputFields: "输入字段",
  apiSkillLocalOnly: "仅本地",
  apiSkillMissing: "缺失 skills",
  apiSkillNextAction: "下一步",
  apiSkillOutputFields: "输出字段",
  apiSkillReadiness: "Readiness",
  apiSkillReview: "需要审核",
  apiSkillRisk: "风险",
  apiSkillTotal: "Contract 总数",
  apiUsageAuthKey: "认证 / key",
  apiUsageBillingHandoff: "Billing handoff",
  apiUsageBoundary: "无实时 API usage 边界",
  apiUsageCandidates: "API usage 候选项",
  apiUsageCommercialModel: "商业模式",
  apiUsageConsumerTier: "消费者层级",
  apiUsageEvidence: "Evidence",
  apiUsageHighRisk: "高风险",
  apiUsageLocalReady: "本地就绪",
  apiUsageMetering: "计量",
  apiUsageMissingCandidates: "缺失候选项",
  apiUsageNextAction: "下一步",
  apiUsageNotStarted: "未开始",
  apiUsageOwner: "负责人",
  apiUsageProductionReady: "生产就绪候选项",
  apiUsageQuota: "配额",
  apiUsageRateLimit: "限流",
  apiUsageReadiness: "API usage 商业化 readiness",
  apiUsageReadinessSubtitle: "任何实时 API usage 前，项目方审核认证、配额、计量、限流、billing handoff 与奖励边界。",
  apiUsageReviewState: "审核状态",
  apiUsageRewardBoundary: "奖励边界",
  apiUsageSummary: "API usage 摘要",
  apiUsageTopNextAction: "首要下一步",
  apiUsageTotalCandidates: "候选项总数",
  aiContent: "AI 内容",
  aiContentAiDrafts: "AI 草稿",
  aiContentArtifacts: "个内容",
  aiContentChannel: "渠道",
  aiContentCopyReady: "可复制",
  aiContentHumanApproved: "人工已批准",
  aiContentHumanReviewRequired: "需要人工审核",
  aiContentLifecycleAiDraft: "AI 草稿",
  aiContentLifecycleEdited: "已编辑",
  aiContentLifecycleHumanApproved: "人工已批准",
  aiContentLifecyclePublishIntent: "发布意图",
  aiContentLifecycleScheduleIntent: "排期意图",
  aiContentNextAction: "下一步",
  aiContentPack: "AI 内容包",
  aiContentPackSubtitle: "项目方审核生成文案、发布意图与质量门禁的工作区。",
  aiContentPublishBlocked: "发布已阻断",
  aiContentPublishReady: "可发布",
  aiContentQualityBlockers: "质量阻断",
  aiContentQualityGates: "质量门禁",
  aiContentReviewer: "审核人",
  aiContentRiskLevel: "风险等级",
  aiContentScheduleReady: "可排期",
  aiContentSummary: "AI 内容包摘要",
  aiContentTotalArtifacts: "内容总数",
  aiOptimizationLocalOnlyBoundary: "本地边界",
  aiOptimizationNoAutoExecution: "仅作为审核输入；不会执行实时 AI、自动风险评分、导出、发奖、钱包动作或合约执行。",
  aiOptimizationOwnerSafeNextAction: "项目方安全下一步",
  aiOptimizationRecommendedAction: "推荐动作",
  aiOptimizationReviewInput: "审核输入 / 不自动执行",
  aiOptimizationSubtitle: "来自 seeded/本地优化工作流的项目方安全建议。",
  aiOptimizationSummary: "AI 优化摘要",
  aiOpsKpiAdoption: "AI Ops KPI 采纳看板",
  aiOpsKpiAdoptionSubtitle: "面向 AI 草稿、内容采纳、节省编辑时间、报告生成和建议采纳的 seeded/本地指标。",
  aiOpsKpiBlocked: "阻断 KPI",
  aiOpsKpiBoundary: "KPI 边界",
  aiOpsKpiEvidence: "证据",
  aiOpsKpiNextAction: "下一步",
  aiOpsKpiOwner: "负责人",
  aiOpsKpiReady: "就绪 KPI",
  aiOpsKpiReadinessBlocked: "阻断",
  aiOpsKpiReadinessReady: "就绪",
  aiOpsKpiReadinessReviewRequired: "需要审核",
  aiOpsKpiReview: "需审核 KPI",
  aiOpsKpiSource: "来源",
  aiOpsKpiStrongestSignal: "最强采纳信号",
  aiOpsKpiTarget: "目标",
  aiOpsKpiTopNextAction: "最高优先级动作",
  aiOpsKpiTotal: "KPI 总数",
  aiOpsKpiTrend: "趋势",
  aiOpsKpiValue: "数值",
  aiPlanner: "AI 活动策划",
  aiPlannerAction: "审核生成简报",
  aiPlannerBlocked: "阻断",
  aiPlannerBoundary: "Planner 边界",
  aiPlannerConfidence: "置信度",
  aiPlannerDecisionCounts: "决策统计",
  aiPlannerDefaultLocale: "默认语言",
  aiPlannerGroupList: "Planner 推荐分组",
  aiPlannerNextAction: "下一步",
  aiPlannerOwner: "负责人",
  aiPlannerReady: "就绪",
  aiPlannerRecommendation: "推荐",
  aiPlannerReviewRequired: "需要审核",
  aiPlannerState: "活动简报草稿已生成，等待项目方审核",
  aiPlannerSupportedLocales: "支持语言",
  aiPlannerWarning: "警告",
  analyticsExport: "数据分析与导出",
  analyticsExportAction: "预览 winners 导出",
  analyticsExportState: "导出预览包含钱包、语言、资格和风险字段",
  advancedAnalyticsActionFamily: "行为类型",
  advancedAnalyticsAudience: "受众",
  advancedAnalyticsBoundary: "高级分析边界",
  advancedAnalyticsCohorts: "Cohorts",
  advancedAnalyticsCohortSegments: "Cohort segments",
  advancedAnalyticsConversionSignal: "转化",
  advancedAnalyticsConverted: "已转化",
  advancedAnalyticsCostEfficiency: "成本效率",
  advancedAnalyticsCostPerVerifiedAction: "Cost per verified action",
  advancedAnalyticsCoverage: "覆盖",
  advancedAnalyticsDay7Retention: "Day 7 留存",
  advancedAnalyticsDay30Retention: "Day 30 留存",
  advancedAnalyticsEvidenceGap: "Evidence gap",
  advancedAnalyticsGap: "缺口",
  advancedAnalyticsNextAction: "下一步",
  advancedAnalyticsOwner: "负责人",
  advancedAnalyticsPremiumReadyReports: "Premium-ready reports",
  advancedAnalyticsPremiumReadiness: "Premium analytics readiness",
  advancedAnalyticsProductConversion: "产品转化",
  advancedAnalyticsProductConversionRows: "产品转化明细",
  advancedAnalyticsProductCoverage: "产品覆盖",
  advancedAnalyticsQualityNote: "质量备注",
  advancedAnalyticsReadiness: "高级分析 readiness",
  advancedAnalyticsReadinessSubtitle: "接入实时 analytics 前，展示 seeded cohort、留存、真实用户质量、成本、产品转化与 premium report readiness。",
  advancedAnalyticsReadyCohorts: "就绪 cohorts",
  advancedAnalyticsRealUserQuality: "真实用户质量",
  advancedAnalyticsRealUserQualityScore: "真实用户质量分",
  advancedAnalyticsRetentionSignal: "留存",
  advancedAnalyticsReviewCohorts: "需复核 cohorts",
  advancedAnalyticsRewardBudget: "奖励预算",
  advancedAnalyticsRiskReview: "风险审核",
  advancedAnalyticsSampleBasis: "样本依据",
  advancedAnalyticsSummary: "高级分析摘要",
  advancedAnalyticsRetentionWindows: "留存窗口",
  advancedAnalyticsVerifiedActions: "已验证行为",
  advancedAnalyticsWalletMix: "钱包组合",
  contractImpact: "合约影响审核",
  contractImpactAction: "打开审核备注",
  contractImpactState: "Off-chain MVP 模式；无需合约迁移",
  contractModeOffChain: "OFF CHAIN MVP",
  contractMode: "合约模式",
  countBlockers: "个阻断项",
  countPassed: "项通过",
  countWarnings: "个警告",
  completionRate: "完成率",
  connectedWallets: "已连接钱包",
  closeoutAiRetrospective: "AI 复盘",
  closeoutAiRetrospectiveBoundary: "AI 复盘边界",
  closeoutBlockedGates: "阻断门禁",
  closeoutBoundary: "Closeout 边界",
  closeoutEvidence: "证据",
  closeoutFinalArchive: "最终归档",
  closeoutGateList: "Closeout 门禁",
  closeoutGeneratedAt: "生成时间",
  closeoutHealthSummary: "健康摘要",
  closeoutHumanReviewRequired: "需要人工审核",
  closeoutLocalOnlyGates: "本地门禁",
  closeoutNextAction: "下一步",
  closeoutNextIterationActions: "下一轮动作",
  closeoutOwner: "负责人",
  closeoutReason: "原因",
  closeoutReadyGates: "就绪门禁",
  closeoutRetrospective: "活动后复盘",
  closeoutRetrospectiveSubtitle: "基于 seeded/本地数据审核 analytics、AI winner 报告、导出 readiness、风险、归档证据与下一轮活动动作。",
  closeoutReviewGates: "需审核门禁",
  closeoutRewardBoundary: "奖励责任",
  closeoutRiskPosture: "风险姿态",
  closeoutStatus: "Closeout 状态",
  closeoutSummary: "Closeout 摘要",
  closeoutTotalGates: "门禁总数",
  closeoutVerifiedActionEvidence: "有效行为证据",
  closeoutWinnerReport: "Winner 报告",
  dashboardTitle: "项目控制台",
  dashboardSubtitle: "当前活动 shell 的运营快照。",
  exportReady: "可导出 winners",
  exportDisclaimer: "导出 winners 不等于发奖。",
  daippTaskBlocked: "阻断",
  daippTaskBoundary: "No-live daipp 边界",
  daippTaskEvidence: "证据",
  daippTaskNextAction: "下一步",
  daippTaskOwner: "负责人",
  daippTaskProviderState: "Provider 状态",
  daippTaskReadiness: "daipp Agent Coin 任务 readiness",
  daippTaskReadinessSubtitle: "面向 agent 页面访问、agent 互动、coin buy/hold、intro 分享与 launch 排行榜任务的 seeded/本地 readiness；真实 daipp 集成前保持可审核。",
  daippTaskReady: "就绪",
  daippTaskReviewRequired: "需要审核",
  daippTaskRiskState: "风险状态",
  daippTaskTotal: "daipp 任务路径",
  forestTaskBlocked: "阻断",
  forestTaskBoundary: "No-live Forest NFT 边界",
  forestTaskEvidence: "证据",
  forestTaskNextAction: "下一步",
  forestTaskOwner: "负责人",
  forestTaskProviderState: "Provider 状态",
  forestTaskReadiness: "Forest NFT 任务 readiness",
  forestTaskReadinessSubtitle: "面向 NFT mint、holder 证据、trade/listing 与 holder 排行榜任务的 seeded/本地 readiness；真实 Forest 集成前保持可审核。",
  forestTaskReady: "就绪",
  forestTaskReviewRequired: "需要审核",
  forestTaskRiskState: "风险状态",
  forestTaskTotal: "NFT 任务路径",
  ebridgeTaskBlocked: "阻断",
  ebridgeTaskBoundary: "No-live eBridge 任务边界",
  ebridgeTaskEvidence: "证据",
  ebridgeTaskNextAction: "下一步",
  ebridgeTaskOwner: "负责人",
  ebridgeTaskProviderState: "Provider 状态",
  ebridgeTaskReadiness: "eBridge 任务 readiness",
  ebridgeTaskReadinessSubtitle: "面向 bridge 意图、金额门槛、链上证据、Awaken 解锁依赖与资格影响的 seeded/本地 readiness；真实 eBridge 集成前保持可审核。",
  ebridgeTaskReady: "就绪",
  ebridgeTaskReviewRequired: "需要审核",
  ebridgeTaskRiskState: "风险状态",
  ebridgeTaskTotal: "eBridge 任务路径",
  awakenTaskBlocked: "阻断",
  awakenTaskBoundary: "No-live Awaken 任务边界",
  awakenTaskEvidence: "证据",
  awakenTaskNextAction: "下一步",
  awakenTaskOwner: "负责人",
  awakenTaskProviderState: "Provider 状态",
  awakenTaskReadiness: "Awaken swap / liquidity 任务 readiness",
  awakenTaskReadinessSubtitle: "面向 Awaken swap、添加流动性、LP 持有证据、bridge 解锁依赖与排名资格影响的 seeded/本地 readiness；真实 Awaken 集成前保持可审核。",
  awakenTaskReady: "就绪",
  awakenTaskReviewRequired: "需要审核",
  awakenTaskRiskState: "风险状态",
  awakenTaskTotal: "Awaken 任务路径",
  schrodingerTaskBlocked: "阻断",
  schrodingerTaskBoundary: "No-live Schrödinger NFT 边界",
  schrodingerTaskEvidence: "证据",
  schrodingerTaskNextAction: "下一步",
  schrodingerTaskOwner: "负责人",
  schrodingerTaskProviderState: "Provider 状态",
  schrodingerTaskReadiness: "Schrödinger NFT 任务 readiness",
  schrodingerTaskReadinessSubtitle: "面向 NFT adopt、holder 证据、trade/listing 与 holder 排行榜任务的 seeded/本地 readiness；真实 Schrödinger 集成前保持可审核。",
  schrodingerTaskReady: "就绪",
  schrodingerTaskReviewRequired: "需要审核",
  schrodingerTaskRiskState: "风险状态",
  schrodingerTaskTotal: "Schrödinger 任务路径",
  forecastTaskBlocked: "阻断",
  forecastTaskBoundary: "No-live 边界",
  forecastTaskEvidence: "Evidence",
  forecastTaskNextAction: "下一步",
  forecastTaskOwner: "负责人",
  forecastTaskProviderState: "Provider 状态",
  forecastTaskReadiness: "Forecast 活动任务 readiness",
  forecastTaskReadinessSubtitle: "面向预测参与、连胜任务与 Forecast 排行榜任务的 seeded/本地 readiness；真实集成前保持可审核。",
  forecastTaskReady: "就绪",
  forecastTaskReviewRequired: "需要审核",
  forecastTaskRiskState: "风险状态",
  forecastTaskTotal: "任务路径",
  payTaskBlocked: "阻断",
  payTaskBoundary: "No-live Pay 边界",
  payTaskNextAction: "下一步",
  payTaskOwner: "负责人",
  payTaskProviderState: "Provider 状态",
  payTaskReadiness: "Pay 活动任务 readiness",
  payTaskReadinessSubtitle: "面向发票完成、支付链接完成与 Pay 后续移交的 seeded/本地 readiness；真实集成前保持可审核。",
  payTaskReady: "就绪",
  payTaskReviewRequired: "需要审核",
  payTaskRiskState: "风险状态",
  payTaskTotal: "任务路径",
  tmrwdaoTaskBlocked: "阻断",
  tmrwdaoTaskBoundary: "No-live 治理边界",
  tmrwdaoTaskEvidence: "证据",
  tmrwdaoTaskNextAction: "下一步",
  tmrwdaoTaskOwner: "负责人",
  tmrwdaoTaskProviderState: "Provider 状态",
  tmrwdaoTaskReadiness: "TMRWDAO 治理任务 readiness",
  tmrwdaoTaskReadinessSubtitle: "面向 DAO 加入、提案摘要、提案投票证据与治理结果审核的 seeded/本地 readiness；真实 DAO 集成前保持可审核。",
  tmrwdaoTaskReady: "就绪",
  tmrwdaoTaskReviewRequired: "需要审核",
  tmrwdaoTaskRiskState: "风险状态",
  tmrwdaoTaskTotal: "治理任务路径",
  localeCoverage: "语言覆盖率",
  localeAnalyticsReadiness: "语言 analytics 就绪状态",
  localeAnalyticsReadinessSubtitle: "接入真实 analytics 前，按 MVP 语言展示 seeded readiness 行。",
  localeAnalyticsMetric: "指标",
  localeAnalyticsValue: "数值",
  localeAnalyticsBoundary: "仅本地准备度；未接入实时 analytics SDK、事件采集、crawler 服务或外部 dashboard。",
  lifecycleAllowed: "允许",
  lifecycleBlocked: "阻断",
  lifecycleBlockingChecks: "阻断检查",
  lifecycleCurrentStatus: "当前状态",
  lifecycleCurrentStatusDetail: "来自当前 seeded 活动 shell。",
  lifecycleExportSensitive: "导出敏感操作",
  lifecycleExportSensitiveDetail: "导出与归档意图保持先审核。",
  lifecycleGateGroup: "门禁分组",
  lifecycleLaunchBlockers: "上线阻断",
  lifecycleLocalOnlyBoundary: "Lifecycle 本地边界",
  lifecycleNotApplicable: "不适用",
  lifecycleOperationCount: "个 lifecycle 操作",
  lifecycleOperations: "Lifecycle 操作",
  lifecycleOperationsEyebrow: "活动 lifecycle",
  lifecycleOperationsSubtitle: "面向项目方的安全状态操作，用于上线、排期、导出与归档决策。",
  lifecycleOwner: "负责人",
  lifecycleOwnerAction: "项目方动作",
  lifecycleReviewRequired: "需要审核",
  lifecycleSummary: "Lifecycle 操作摘要",
  lifecycleTopNextAction: "首要下一步",
  launchConsoleAudience: "受众",
  launchConsoleBlocked: "阻断",
  launchConsoleBoundary: "非实时边界",
  launchConsoleCampaignIntent: "活动意图",
  launchConsoleGateEvidence: "门禁 evidence",
  launchConsoleHandoffRequired: "需要 handoff",
  launchConsoleHandoffs: "Skill handoff",
  launchConsoleLaunchBlocking: "上线阻断",
  launchConsoleLocalOnly: "本地预览",
  launchConsoleNextAction: "下一步",
  launchConsoleNoLiveBoundary: "仅 seeded/本地预览。不会连接真实 Launch Console，不会自动创建或发布活动，不会调用外部 API、钱包签名、合约写入、导出文件或奖励发放。",
  launchConsoleOwner: "负责人",
  launchConsoleReady: "就绪",
  launchConsoleRecommendedTiming: "时机",
  launchConsoleReviewRequired: "需要审核",
  launchConsoleStage: "阶段",
  launchConsoleSummary: "活动包摘要",
  launchConsoleTaskCategoryContentAnalytics: "内容 / 分析",
  launchConsoleTaskCategoryOnChainApi: "链上 / API",
  launchConsoleTaskCategorySocialManual: "社交 / 人工",
  launchConsoleTaskCategoryWallet: "钱包",
  launchConsoleTasks: "任务块",
  launchConsoleBundles: "Launch Console 活动包",
  launchConsoleBundlesSubtitle: "面向预热、上线与上线后三阶段审核的 seeded/本地 launch package；任何真实 Launch Console handoff 前都需要复核。",
  launchConsoleTotalBundles: "活动包总数",
  aiPlannerLaunchApprovalRoutes: "审批路线",
  aiPlannerLaunchBoundary: "发布边界",
  aiPlannerLaunchDecision: "AI Planner 发布决策",
  aiPlannerLaunchDecisionItems: "发布决策项",
  aiPlannerLaunchDecisionSubtitle: "面向已选任务、继承发布门禁、负责人路线与不自动发布边界的本地审核包。",
  aiPlannerLaunchInheritedGateCount: "继承门禁",
  aiPlannerLaunchInheritedGates: "继承发布门禁",
  aiPlannerLaunchLocaleReadiness: "语言 readiness",
  aiPlannerLaunchPoints: "积分",
  aiPlannerLaunchSelectedTaskCount: "已选任务",
  aiPlannerLaunchSelectedTasks: "已选任务模板",
  aiPlannerLaunchSelectedTemplate: "已选活动模板",
  aiPlannerLaunchSelectedTemplateCount: "已选模板",
  aiPlannerLaunchVerification: "验证方式",
  aiPlannerLaunchWalletCompatibility: "钱包兼容",
  aiPlannerLaunchBlocksPublish: "阻断发布",
  campaignCreationWorkflowReadiness: "活动创建流程 Readiness",
  campaignCreationWorkflowSubtitle: "v0.2 创建活动流程的有序 seeded/本地 readiness；不会触发实时创建或发布。",
  campaignCreationWorkflowStepList: "创建流程步骤",
  campaignCreationWorkflowReadySteps: "就绪步骤",
  campaignCreationWorkflowReviewSteps: "需审核步骤",
  campaignCreationWorkflowWarningSteps: "警告步骤",
  campaignCreationWorkflowBlockedSteps: "阻断步骤",
  campaignCreationWorkflowInheritedGates: "继承门禁",
  campaignCreationWorkflowBoundary: "创建边界",
  campaignCreationWorkflowEvidence: "Evidence",
  campaignCreationWorkflowBlockers: "阻断项",
  campaignCreationWorkflowWarnings: "警告项",
  campaignCreationWorkflowNoIssues: "无继承阻断或警告",
  campaignCreationWorkflowSourceChecklist: "来源检查清单",
  readiness: "发布 readiness",
  riskQueue: "风险审核队列",
  taskCount: "个已配置任务",
  rewardsEligibility: "奖励与资格",
  rewardsEligibilityAction: "检查参与者资格",
  rewardsEligibilityState: "资格预览区分缺失任务和风险标记",
  taskBuilder: "任务构建预览",
  taskBuilderAction: "审核钱包兼容性",
  taskBuilderState: "钱包感知任务覆盖 AA、EOA 与任意钱包参与",
  translationReview: "i18n 翻译审核",
  translationReviewAction: "审核中文草稿",
  translationReviewState: "英文已发布；中文仍为 AI 草稿/回退状态",
  walletSplit: "AA / EOA 占比",
  walletAdapterReadiness: "aelf-web-login adapter readiness",
  walletAdapterReadinessSubtitle: "接入真实 SDK 前的 AA 与 EOA 钱包 adapter readiness。",
  walletAdapterConfigured: "已配置 adapter",
  walletAdapterEnabledPreview: "预览启用",
  walletAdapterMaintenance: "维护中",
  walletAdapterMissingLiveEvidence: "缺失真实证据",
  walletAdapterReleaseBlockers: "发布阻断",
  walletAdapterFeatureGate: "功能门禁",
  walletAdapterFallback: "Fallback",
  walletAdapterNextAction: "下一步",
  walletAdapterBoundary: "无实时钱包 SDK 边界",
  liveWalletConnectorBoundary: "Live wallet connector boundary",
  liveWalletConnectorBoundaryEyebrow: "Connector 边界",
  liveWalletConnectorBoundarySubtitle: "接入实时钱包 SDK 前，默认关闭的 connector package 候选与上线阻断。",
  liveWalletConnectorCandidates: "Connector 候选",
  liveWalletConnectorDisabledReviewRequired: "已关闭 / 需审核",
  liveWalletConnectorMissingEvidence: "缺失真实证据",
  liveWalletConnectorConfigRequired: "需要配置门禁",
  liveWalletConnectorReviewApprovalRequired: "需要 live QA 与审核批准",
  liveWalletConnectorReleaseGuardrail: "本 mission 不启用生产连接",
  liveWalletConnectorPackage: "候选 package",
  zhFallbackWarning: "中文内容在审核前回退展示英文。",
  warning: "警告",
  blocker: "阻断",
  builderAiOutline: "AI 生成大纲",
  builderAiPrompt: "AI Prompt",
  builderAnyWalletDefault: "默认推荐",
  builderCompleteness: "草稿完整度",
  builderCompletenessSummary: "基础信息已完成；发布前仍展示合约与风险检查。",
  builderEntryAction: "打开活动草稿",
  builderEntryState: "草稿设置结合 AI 简报与结构化活动字段",
  builderEntryTitle: "活动构建器",
  builderFormState: "结构化表单状态",
  builderLocaleScope: "语言范围",
  builderLocaleScopeDetail: "默认与回退：en-US。支持：en-US、zh-CN 与 zh-TW 回退 readiness。",
  builderMissingBasics: "缺失必填基础信息",
  builderNoMissingBasics: "无缺失基础信息",
  builderOverview: "草稿概览",
  builderObjective: "目标",
  builderProject: "项目",
  builderTargetUsers: "目标用户",
  builderTimePeriod: "活动周期",
  builderWalletPolicy: "钱包策略",
  campaignTemplatePackBoundary: "仅 seeded/本地活动模板：不会执行实时 provider 验证、自动创建活动、自动发布、奖励托管或发奖。",
  campaignTemplatePackNextAction: "下一步",
  campaignTemplatePackOwner: "负责人",
  campaignTemplatePackReadiness: "Readiness",
  campaignTemplatePackReviewRequired: "需要审核",
  campaignTemplatePackRewardBoundary: "奖励边界",
  campaignTemplatePackReady: "就绪",
  campaignTemplatePackSubtitle: "面向首批 aelf-native 活动模板的 campaign-level presets；每个模板在创建草稿前展示人工审核与奖励责任。",
  campaignTemplatePackSuitableFor: "适用场景",
  campaignTemplatePackTaskSequence: "任务序列",
  campaignTemplatePackTitle: "活动模板包",
  campaignTemplatePackTotal: "模板数",
  campaignTemplatePackWalletPolicy: "钱包策略",
  commandCenter: "活动指挥中心",
  commandCenterSubtitle: "面向项目方的活动状态、风险、导出准备度和下一步动作视图。",
  commandCenterSummary: "活动组合",
  commandCampaigns: "个活动",
  commandLive: "进行中",
  commandScheduledDraft: "已排期 / 草稿",
  commandEnded: "已结束",
  commandExported: "已导出",
  commandWarnings: "警告",
  commandBlockers: "阻断",
  commandNextAction: "项目方动作",
  commandPriority: "优先级",
  commandRisk: "风险",
  commandExport: "导出",
  commandTimeWindow: "活动周期",
  commandLocale: "语言",
  commandWallet: "钱包占比",
  portfolioCommercialReadiness: "项目组合 readiness",
  portfolioCommercialSubtitle: "在任何实时 billing 或奖励操作前，展示 seeded 项目组合指标与商业化模型 readiness。",
  portfolioCommercialSummary: "项目组合摘要",
  portfolioCommercialMetrics: "项目组合指标",
  portfolioCommercialModels: "商业化 readiness",
  portfolioCommercialTopNextAction: "首要下一步",
  portfolioCommercialRewardBoundary: "奖励边界",
  portfolioCommercialOwner: "负责人",
  portfolioCommercialEvidence: "Evidence",
  portfolioCommercialNextAction: "下一步",
  portfolioCommercialProductionReady: "生产就绪模型",
  createStepContract: "合约",
  createStepGoal: "目标",
  createStepI18n: "i18n",
  createStepPrefix: "步骤",
  createStepPublishReadiness: "发布准备度",
  createStepRewardsEligibility: "奖励与资格",
  createStepTasks: "任务",
  createDraftActiveLocales: "当前草稿语言",
  createDraftAiAssistedMode: "AI 辅助模式",
  createDraftCampaignName: "活动名称",
  createDraftComposer: "本地活动草稿编辑器",
  createDraftComposerTitle: "可编辑活动草稿",
  createDraftEndDate: "结束日期",
  createDraftFormMode: "表单模式",
  createDraftGenerateOutline: "生成本地大纲",
  createDraftHumanReviewAcknowledged: "已人工审核",
  createDraftHumanReviewRequired: "需要人工审核",
  createDraftLocalBoundary: "仅本地草稿：不会调用实时 AI provider、自动发布、创建实时活动、变更后端、请求钱包签名、执行合约、生成导出、托管奖励或发奖。",
  createDraftMode: "创建模式",
  createDraftOutlinePreview: "生成大纲预览",
  createDraftProjectName: "项目名称",
  createDraftReset: "重置为 Awaken 基线",
  createDraftReviewAcknowledgement: "已确认人工审核",
  createDraftStartDate: "开始日期",
  createDraftSupportedLocales: "支持语言",
  createDraftTargetUsers: "目标用户",
  createDraftTaskTemplates: "任务模板选择",
  createDraftTaskTemplatesSummary: "选择会更新本地草稿、readiness 门禁与发布决策预览。",
  createDraftWalletPolicy: "钱包策略",
  createWorkspaceStepper: "创建活动检查点",
  createWorkspaceStepperSummary: "项目方按目标、任务、奖励、语言、合约与发布准备度检查活动草稿。",
  analyticsExportDecision: "分析与导出决策",
  analyticsExportDecisionSubtitle: "批准 winners 导出前，项目方需要看的质量指标。",
  dropOffPoint: "最大流失点",
  readyRows: "就绪行",
  reviewRequiredRows: "需复核行",
  blockedRows: "阻断行",
  rowStatusCounts: "行状态统计",
  exportBatch: "导出批次",
  exportAcknowledgements: "确认项",
  csvColumns: "CSV 字段",
  evidenceCoverage: "证据覆盖",
  exportConfirmationReadiness: "导出确认 readiness",
  exportConfirmationReadinessEyebrow: "Seeded/本地导出门禁",
  exportConfirmationReadinessSubtitle: "项目方批准前检查预览模式、必需字段、行原因、确认项与 root 阻断。",
  exportConfirmationSummary: "导出确认摘要",
  exportContractRootReadiness: "合约 root readiness",
  exportCoveredFields: "已覆盖字段",
  exportIncludedFields: "包含字段",
  exportArtifact: "本地导出 artifact",
  exportArtifactBatchId: "Artifact 批次",
  exportArtifactBoundary: "仅本地 artifact：不生成下载链接、不写入存储、不生成合约 root、不执行合约交易、不托管奖励也不发奖。",
  exportArtifactChecksum: "Checksum",
  exportArtifactFormat: "Artifact 格式",
  exportArtifactNoContractRoot: "不生成合约 root",
  exportArtifactNoDownloadUrl: "不生成下载链接",
  exportArtifactNoRewardDistribution: "不发奖",
  exportArtifactNoStorageWrite: "不写入存储",
  exportArtifactPayloadSize: "Payload bytes",
  exportArtifactRows: "Artifact 行数",
  exportFulfillmentAcknowledgementState: "批准状态",
  exportFulfillmentBoundary: "本地交接边界",
  exportFulfillmentChecksum: "Checksum",
  exportFulfillmentFutureStorage: "未来 storage-backed 导出",
  exportFulfillmentIncludedColumns: "包含字段",
  exportFulfillmentNextAction: "本地交接下一步",
  exportFulfillmentNoContractRoot: "不生成合约 root",
  exportFulfillmentNoDownloadUrl: "不生成下载链接",
  exportFulfillmentNoRewardDistribution: "不发奖",
  exportFulfillmentNoStorageWrite: "不写入存储",
  exportFulfillmentOwnerApproved: "项目方已批准",
  exportFulfillmentPackageId: "Package ID",
  exportFulfillmentPackages: "本地 package readiness",
  exportFulfillmentPayloadBytes: "Payload bytes",
  exportFulfillmentReadiness: "导出履约 readiness",
  exportFulfillmentReadinessSubtitle: "面向项目方交接的本地 CSV 和 JSON package 状态，不启用 storage-backed 下载。",
  exportFulfillmentRows: "就绪 / 需审核 / 阻断行",
  exportFulfillmentSafety: "安全边界",
  exportFulfillmentStatus: "交接状态",
  exportStorageProviderSummary: "Storage provider 批准摘要",
  exportStorageProviderSummarySubtitle: "面向项目方的 compact 视图：生产 storage 路径仍被阻断，本地 CSV/JSON 交接仍是可用导出路径。",
  exportStorageProviderTopBlocker: "首要 storage 阻断",
  exportStorageProviderNextAction: "安全下一步",
  exportStorageProviderStorageWriteDisabled: "存储写入启用 = false",
  exportStorageProviderDownloadUrlDisabled: "下载链接启用 = false",
  exportStorageProviderNoContractRootWrite: "合约 root/write 启用 = false",
  exportStorageProviderRewardCustodyDisabled: "奖励托管启用 = false",
  exportStorageProviderRewardDistributionDisabled: "发奖启用 = false",
  exportStorageProviderLocalHandoff: "本地 CSV/JSON 交接仍可用",
  exportStorageProviderBoundary: "生产 storage 边界",
  exportStorageProviderApprovalBlocked: "生产 storage 批准已阻断",
  exportLocalPreviewOnly: "仅本地预览",
  exportMissingFields: "缺失字段",
  exportPreviewModes: "CSV / JSON 预览模式",
  exportProjectAcknowledgements: "项目方确认项",
  exportRealFile: "真实文件",
  exportRequiredFields: "必需导出字段",
  exportRootClaimBlocked: "Root 与 claim 执行阻断",
  exportRowReasonCoverage: "行原因覆盖",
  exportSafeDefault: "安全默认：不生成合约 root",
  exportTotalRows: "总行数",
  exportWorkspaceDecision: "导出决策",
  exportWorkspaceDecisionSubtitle: "基于 seeded 数据预览已验证行、CSV 合约、证据覆盖与奖励责任。",
  providerEvidenceRegistry: "Provider 证据登记表",
  providerEvidenceRegistrySubtitle: "接入真实 provider 前，审核 adapter readiness、配置门禁、fallback 与上线阻断。",
  providerRegistryTotalEntries: "登记条目",
  providerRegistryMissingLiveEvidence: "缺失真实 evidence",
  providerRegistryLocalOnly: "仅本地路径",
  providerRegistryReviewRequired: "需复核路径",
  providerRegistryUnavailable: "不可用路径",
  providerRegistryBlocked: "阻断路径",
  providerRegistryLaunchBlockers: "上线阻断",
  providerRegistryFeatureGate: "配置门禁",
  providerRegistryFallback: "Fallback",
  providerRegistryAdapterReadiness: "Adapter readiness",
  providerRegistryUnavailableReadiness: "不可用",
  providerRegistryBlockedReadiness: "阻断",
  providerRegistryLocalOnlyBoundary: "仅 seeded/本地 provider 证据",
  participantAccount: "账户",
  participantBlocked: "阻断",
  participantEligible: "符合资格",
  participantExportPosture: "导出姿态",
  participantExportReady: "导出就绪",
  participantExportStatus: "导出状态",
  participantLocale: "语言",
  participantLocaleMix: "语言分布",
  participantNextAction: "下一步",
  participantNoRiskFlags: "无风险标记",
  participantOperations: "参与者运营",
  participantOperationsSubtitle: "基于 seeded/本地数据按钱包、语言、任务进度、风险与导出姿态审核参与者。",
  participantPending: "待处理",
  participantReviewRequired: "需要审核",
  participantRewardBoundary: "奖励边界",
  participantRiskFlags: "风险标记",
  participantRowList: "参与者行",
  participantSummary: "参与者摘要",
  participantTaskProgress: "任务进度",
  participantWalletMix: "钱包分布",
  participantWalletSource: "钱包来源",
  pointsRankingReferralBlocked: "阻断",
  pointsRankingReferralBoundary: "Service 边界",
  pointsRankingReferralEvidence: "证据",
  pointsRankingReferralLaneList: "Readiness lanes",
  pointsRankingReferralLocalOnly: "仅本地",
  pointsRankingReferralNextAction: "下一步",
  pointsRankingReferralOwner: "负责人",
  pointsRankingReferralQualifiedInvitees: "合格邀请",
  pointsRankingReferralRawInvites: "Raw invites",
  pointsRankingReferralReady: "就绪",
  pointsRankingReferralReadiness: "Points / Ranking / Referral Service readiness",
  pointsRankingReferralReferralPoints: "Referral points",
  pointsRankingReferralReviewRequired: "需要审核",
  pointsRankingReferralSource: "来源",
  pointsRankingReferralSubtitle: "面向积分账本、off-chain ranking、邀请资格与 Pixiepoints/backend 交接的 seeded/本地 readiness。",
  pointsRankingReferralSummary: "Service readiness 摘要",
  pointsRankingReferralTotalLanes: "Lane 总数",
  settingsBlockedGroups: "阻断分组",
  settingsCurrentValue: "当前值",
  settingsEvidence: "证据",
  settingsGroupList: "设置分组",
  settingsNextAction: "下一步",
  settingsOwner: "负责人",
  settingsReadiness: "设置 readiness",
  settingsReadinessSubtitle: "任何实时写入或后端保存前，只读检查活动设置 readiness。",
  settingsReadOnlyBoundary: "只读 / 无实时写入边界",
  settingsReadyGroups: "就绪分组",
  settingsReviewGroups: "需审核分组",
  settingsSummary: "设置摘要",
  settingsTotalGroups: "分组总数",
  eligible: "符合资格",
  ineligible: "不符合资格",
  missingTask: "缺失任务",
  open: "待处理",
  approved: "已批准",
  published: "已发布",
  aiDraft: "AI 草稿",
  apiSkillReadinessBlocked: "阻断",
  apiSkillReadinessLocalOnly: "仅本地",
  apiSkillReadinessReady: "就绪",
  apiSkillReadinessReviewRequired: "需要审核",
  reviewed: "已审核",
  fallback: "回退",
  formObjective: "目标已确认",
  formReward: "奖励方案已确认",
  formTimeline: "周期已确认",
  formWallet: "钱包策略已确认",
  serviceBoundaryDetail: "不会调用 live backend/API、钱包签名、secret 存储、真实导出文件、奖励发放或合约 root 写入。",
  serviceBoundaryTitle: "Seeded/本地边界",
  serviceCoverage: "Service 覆盖",
  serviceCoveredApiGroups: "已覆盖 API 分组",
  serviceCoveredFieldGroups: "已覆盖字段分组",
  serviceFacade: "本地 API Service Facade",
  serviceFacadeSubtitle: "面向 v0.2 API 与 UI 覆盖的可调用 seeded/本地 service surface。",
  serviceReadinessBlocked: "阻断",
  serviceReadinessLocalOnly: "仅本地",
  serviceReadinessReady: "就绪",
  serviceReadinessReviewRequired: "需要审核",
  serviceSampleResponses: "示例响应",
  serviceTotalServices: "服务总数",
  verificationPipelineAffectedOutcomes: "影响结果",
  verificationPipelineBlockedPaths: "阻断路径",
  verificationPipelineCompleted: "已完成",
  verificationPipelineEligibilityImpact: "资格影响",
  verificationPipelineFailed: "失败",
  verificationPipelineFallbackReason: "Fallback 原因",
  verificationPipelineLiveEvidence: "实时 evidence",
  verificationPipelineLiveReady: "实时就绪",
  verificationPipelineManualReviewPaths: "人工审核路径",
  verificationPipelineMissingLiveEvidence: "缺失实时 evidence",
  verificationPipelineMissingRequiredTasks: "缺失必做任务",
  verificationPipelineNextAction: "运营下一步",
  verificationPipelineNone: "无",
  verificationPipelinePending: "待验证",
  verificationPipelineReadiness: "验证 pipeline readiness",
  verificationPipelineReadinessSubtitle: "用于发布审核的 provider readiness、任务结果、资格影响与非实时边界。",
  verificationPipelineReferralQualification: "邀请资格",
  verificationPipelineReleaseImpact: "发布影响",
  verificationPipelineRiskFlags: "风险标记",
  verificationPipelineSeededCoverage: "Seeded/本地覆盖",
  verificationPipelineSeededReady: "Seeded 就绪",
  verificationPipelineTaskOutcomeCoverage: "任务结果覆盖",
  verificationPipelineTotalPaths: "路径总数",
  projectWorkspace: "项目控制台工作区",
  projectWorkspaceNavigation: "项目控制台工作区导航",
  stateComponentsBoundary: "状态画廊边界",
  stateComponentsBlocked: "阻断状态",
  stateComponentsCovered: "已覆盖状态",
  stateComponentsDescription: "说明",
  stateComponentsDeliveryGallery: "状态组件交付画廊",
  stateComponentsExamples: "代表性状态",
  stateComponentsFamilies: "状态族",
  stateComponentsMeaning: "含义",
  stateComponentsMessage: "提示文案",
  stateComponentsNextAction: "下一步",
  stateComponentsOwner: "负责人",
  stateComponentsReadiness: "Readiness",
  stateComponentsReviewRequired: "需审核状态",
  stateComponentsSource: "来源",
  stateComponentsSourceReferences: "来源引用",
  stateComponentsSubtitle: "基于 seeded/本地数据集中审计 loading、empty、error、toast、modal、发布阻断、活动、任务、资格、i18n、钱包 QA 与导出审核状态。",
  stateComponentsTopNextAction: "最高优先级动作",
  stateReadinessBlocked: "阻断",
  stateReadinessCovered: "已覆盖",
  stateReadinessReviewRequired: "需要审核",
  templatesWorkspaceBoundary: "模板选择保持本地预览，并保留钱包兼容性、验证方式与语言 readiness 信号。",
  verificationBoundary: "验证边界",
  verificationCoverage: "验证覆盖",
  verificationEvidenceCategories: "Evidence 分类",
  verificationManualReview: "人工审核",
  verificationProviderReadiness: "Provider readiness",
  verificationRulesAffectedOutcomes: "影响结果类型",
  verificationRulesProviderEvidence: "验证 provider 证据",
  verificationRulesProviderLaunchBlockers: "Provider 上线阻断",
  verificationRulesSummary: "验证规则摘要",
  verificationRulesTopRule: "最高优先级规则",
  verificationRiskStates: "风险敏感状态",
  workspaceAiContent: "AI 内容",
  workspaceAiContentSummary: "审核生成内容、优化建议、人工批准状态与不自动发布边界。",
  workspaceAnalytics: "分析",
  workspaceAnalyticsSummary: "查看 seeded KPI、漏斗流失、钱包占比、语言占比与语言 analytics readiness。",
  workspaceCampaigns: "活动",
  workspaceCampaignsSummary: "监控活动组合状态、当前活动指标、风险、导出准备度与项目方下一步动作。",
  workspaceCloseout: "复盘",
  workspaceCloseoutSummary: "审核活动后的 analytics、AI winner 报告、导出 readiness、风险、奖励责任、归档状态与下一轮动作。",
  workspaceCreate: "创建",
  workspaceCreateSummary: "按目标、任务、奖励、i18n、合约与发布检查点创建并审核活动草稿。",
  workspaceExport: "导出",
  workspaceExportSummary: "审核已验证导出行、CSV 字段、证据覆盖、API contracts 与奖励责任。",
  workspaceParticipants: "参与者",
  workspaceParticipantsSummary: "在不发奖的边界下审核参与者资格、任务进度、风险标记、钱包分布与导出姿态。",
  workspaceSettings: "设置",
  workspaceSettingsSummary: "检查钱包、合约、奖励、i18n、验证、导出与发布设置 readiness，保持只读。",
  workspaceStates: "状态",
  workspaceStatesSummary: "集中审计状态组件覆盖、恢复动作、来源引用与 no-live 边界。",
  workspaceTemplates: "模板",
  workspaceTemplatesSummary: "选择钱包感知任务模板，并查看验证方式与语言 readiness 上下文。",
  workspaceVerificationRules: "验证规则",
  workspaceVerificationRulesSummary: "审核链上、API、人工审核、邀请、provider 证据、发布影响与 no-live 边界。",
} satisfies typeof enUS;

export const projectConsoleCopy = {
  "en-US": enUS,
  "zh-CN": zhCN,
  "zh-TW": {
    ...zhCN,
    builderLocaleScopeDetail: "預設與回退：en-US。支援：en-US、zh-CN 與 zh-TW 回退 readiness。",
    closeoutAiRetrospective: "AI 復盤",
    closeoutBlockedGates: "阻斷門禁",
    closeoutGateList: "Closeout 門禁",
    closeoutHumanReviewRequired: "需要人工審核",
    closeoutNextIterationActions: "下一輪動作",
    closeoutRetrospective: "活動後復盤",
    closeoutRetrospectiveSubtitle: "基於 seeded/本地資料審核 analytics、AI winner 報告、匯出 readiness、風險、歸檔證據與下一輪活動動作。",
    closeoutRewardBoundary: "獎勵責任",
    closeoutWinnerReport: "Winner 報告",
    createDraftActiveLocales: "目前草稿語言",
    createDraftAiAssistedMode: "AI 輔助模式",
    createDraftCampaignName: "活動名稱",
    createDraftComposer: "本地活動草稿編輯器",
    createDraftComposerTitle: "可編輯活動草稿",
    createDraftEndDate: "結束日期",
    createDraftFormMode: "表單模式",
    createDraftGenerateOutline: "生成本地大綱",
    createDraftHumanReviewAcknowledged: "已人工審核",
    createDraftHumanReviewRequired: "需要人工審核",
    createDraftLocalBoundary: "僅本地草稿：不會呼叫即時 AI provider、自動發布、建立即時活動、變更後端、請求錢包簽名、執行合約、生成匯出、託管獎勵或發獎。",
    createDraftMode: "建立模式",
    createDraftOutlinePreview: "生成大綱預覽",
    createDraftProjectName: "專案名稱",
    createDraftReset: "重置為 Awaken 基線",
    createDraftReviewAcknowledgement: "已確認人工審核",
    createDraftStartDate: "開始日期",
    createDraftSupportedLocales: "支援語言",
    createDraftTargetUsers: "目標使用者",
    createDraftTaskTemplates: "任務模板選擇",
    createDraftTaskTemplatesSummary: "選擇會更新本地草稿、readiness 門禁與發布決策預覽。",
    createDraftWalletPolicy: "錢包策略",
    createWorkspaceStepperSummary: "專案方依目標、任務、獎勵、語言、合約與發布準備度檢查活動草稿。",
    exportAcknowledgements: "確認項",
    exportConfirmationReadiness: "匯出確認 readiness",
    exportConfirmationReadinessEyebrow: "Seeded/本地匯出門禁",
    exportConfirmationReadinessSubtitle: "專案方批准前檢查預覽模式、必要欄位、行原因、確認項與 root 阻斷。",
    exportArtifact: "本地匯出 artifact",
    exportArtifactBatchId: "Artifact 批次",
    exportArtifactBoundary: "僅本地 artifact：不產生下載連結、不寫入儲存、不生成合約 root、不執行合約交易、不託管獎勵也不發獎。",
    exportArtifactFormat: "Artifact 格式",
    exportArtifactNoContractRoot: "不生成合約 root",
    exportArtifactNoDownloadUrl: "不產生下載連結",
    exportArtifactNoRewardDistribution: "不發獎",
    exportArtifactNoStorageWrite: "不寫入儲存",
    exportArtifactRows: "Artifact 行數",
    exportFulfillmentAcknowledgementState: "批准狀態",
    exportFulfillmentBoundary: "本地交接邊界",
    exportFulfillmentChecksum: "Checksum",
    exportFulfillmentFutureStorage: "未來 storage-backed 匯出",
    exportFulfillmentIncludedColumns: "包含欄位",
    exportFulfillmentNextAction: "本地交接下一步",
    exportFulfillmentNoContractRoot: "不生成合約 root",
    exportFulfillmentNoDownloadUrl: "不產生下載連結",
    exportFulfillmentNoRewardDistribution: "不發獎",
    exportFulfillmentNoStorageWrite: "不寫入儲存",
    exportFulfillmentOwnerApproved: "專案方已批准",
    exportFulfillmentPackageId: "Package ID",
    exportFulfillmentPackages: "本地 package readiness",
    exportFulfillmentPayloadBytes: "Payload bytes",
    exportFulfillmentReadiness: "匯出履約 readiness",
    exportFulfillmentReadinessSubtitle: "面向專案方交接的本地 CSV 和 JSON package 狀態，不啟用 storage-backed 下載。",
    exportFulfillmentRows: "就緒 / 需審核 / 阻斷行",
    exportFulfillmentSafety: "安全邊界",
    exportFulfillmentStatus: "交接狀態",
    exportStorageProviderSummary: "Storage provider 批准摘要",
    exportStorageProviderSummarySubtitle: "面向專案方的 compact 視圖：生產 storage 路徑仍被阻斷，本地 CSV/JSON 交接仍是可用匯出路徑。",
    exportStorageProviderTopBlocker: "首要 storage 阻斷",
    exportStorageProviderNextAction: "安全下一步",
    exportStorageProviderStorageWriteDisabled: "儲存寫入啟用 = false",
    exportStorageProviderDownloadUrlDisabled: "下載連結啟用 = false",
    exportStorageProviderNoContractRootWrite: "合約 root/write 啟用 = false",
    exportStorageProviderRewardCustodyDisabled: "獎勵託管啟用 = false",
    exportStorageProviderRewardDistributionDisabled: "發獎啟用 = false",
    exportStorageProviderLocalHandoff: "本地 CSV/JSON 交接仍可用",
    exportStorageProviderBoundary: "生產 storage 邊界",
    exportStorageProviderApprovalBlocked: "生產 storage 批准已阻斷",
    exportConfirmationSummary: "匯出確認摘要",
    exportContractRootReadiness: "合約 root readiness",
    exportCoveredFields: "已覆蓋欄位",
    exportIncludedFields: "包含欄位",
    exportLocalPreviewOnly: "僅本地預覽",
    exportMissingFields: "缺失欄位",
    exportPreviewModes: "CSV / JSON 預覽模式",
    exportProjectAcknowledgements: "專案方確認項",
    exportRealFile: "真實檔案",
    exportRequiredFields: "必要匯出欄位",
    exportRootClaimBlocked: "Root 與 claim 執行阻斷",
    exportRowReasonCoverage: "行原因覆蓋",
    exportSafeDefault: "安全預設：不生成合約 root",
    exportTotalRows: "總行數",
    exportWorkspaceDecisionSubtitle: "基於 seeded 資料預覽已驗證行、CSV contract、證據覆蓋與獎勵責任。",
    fallback: "回退",
    providerEvidenceRegistry: "Provider 證據登記表",
    providerEvidenceRegistrySubtitle: "接入真實 provider 前，審核 adapter readiness、配置門禁、fallback 與上線阻斷。",
    providerRegistryBlocked: "阻斷路徑",
    providerRegistryBlockedReadiness: "阻斷",
    providerRegistryFeatureGate: "配置門禁",
    providerRegistryFallback: "Fallback",
    providerRegistryLaunchBlockers: "上線阻斷",
    providerRegistryLocalOnly: "僅本地路徑",
    providerRegistryLocalOnlyBoundary: "僅 seeded/本地 provider 證據",
    providerRegistryMissingLiveEvidence: "缺失真實 evidence",
    providerRegistryReviewRequired: "需複核路徑",
    providerRegistryTotalEntries: "登記條目",
    providerRegistryUnavailable: "不可用路徑",
    providerRegistryUnavailableReadiness: "不可用",
    participantAccount: "帳戶",
    participantBlocked: "阻斷",
    participantEligible: "符合資格",
    participantExportPosture: "匯出姿態",
    participantExportReady: "匯出就緒",
    participantExportStatus: "匯出狀態",
    participantLocale: "語言",
    participantLocaleMix: "語言分佈",
    participantNextAction: "下一步",
    participantNoRiskFlags: "無風險標記",
    participantOperations: "參與者營運",
    participantOperationsSubtitle: "基於 seeded/本地資料依錢包、語言、任務進度、風險與匯出姿態審核參與者。",
    participantPending: "待處理",
    participantReviewRequired: "需要審核",
    participantRewardBoundary: "獎勵邊界",
    participantRiskFlags: "風險標記",
    participantRowList: "參與者行",
    participantSummary: "參與者摘要",
    participantTaskProgress: "任務進度",
    participantWalletMix: "錢包分佈",
    participantWalletSource: "錢包來源",
    pointsRankingReferralBlocked: "阻斷",
    pointsRankingReferralBoundary: "Service 邊界",
    pointsRankingReferralEvidence: "證據",
    pointsRankingReferralLaneList: "Readiness lanes",
    pointsRankingReferralLocalOnly: "僅本地",
    pointsRankingReferralNextAction: "下一步",
    pointsRankingReferralOwner: "負責人",
    pointsRankingReferralQualifiedInvitees: "合格邀請",
    pointsRankingReferralRawInvites: "Raw invites",
    pointsRankingReferralReady: "就緒",
    pointsRankingReferralReadiness: "Points / Ranking / Referral Service readiness",
    pointsRankingReferralReferralPoints: "Referral points",
    pointsRankingReferralReviewRequired: "需要審核",
    pointsRankingReferralSource: "來源",
    pointsRankingReferralSubtitle: "面向積分帳本、off-chain ranking、邀請資格與 Pixiepoints/backend 交接的 seeded/本地 readiness。",
    pointsRankingReferralSummary: "Service readiness 摘要",
    pointsRankingReferralTotalLanes: "Lane 總數",
    settingsBlockedGroups: "阻斷分組",
    settingsCurrentValue: "目前值",
    settingsEvidence: "證據",
    settingsGroupList: "設定分組",
    settingsNextAction: "下一步",
    settingsOwner: "負責人",
    settingsReadiness: "設定 readiness",
    settingsReadinessSubtitle: "任何即時寫入或後端保存前，只讀檢查活動設定 readiness。",
    settingsReadOnlyBoundary: "只讀 / 無即時寫入邊界",
    settingsReadyGroups: "就緒分組",
    settingsReviewGroups: "需審核分組",
    settingsSummary: "設定摘要",
    settingsTotalGroups: "分組總數",
    walletAdapterReadiness: "aelf-web-login adapter readiness",
    walletAdapterReadinessSubtitle: "接入真實 SDK 前的 AA 與 EOA 錢包 adapter readiness。",
    walletAdapterConfigured: "已配置 adapter",
    walletAdapterEnabledPreview: "預覽啟用",
    walletAdapterMaintenance: "維護中",
    walletAdapterMissingLiveEvidence: "缺失真實證據",
    walletAdapterReleaseBlockers: "發布阻斷",
    walletAdapterFeatureGate: "功能門禁",
    walletAdapterFallback: "Fallback",
    walletAdapterNextAction: "下一步",
    walletAdapterBoundary: "無即時錢包 SDK 邊界",
    liveWalletConnectorBoundary: "Live wallet connector boundary",
    liveWalletConnectorBoundaryEyebrow: "Connector 邊界",
    liveWalletConnectorBoundarySubtitle: "接入即時錢包 SDK 前，預設關閉的 connector package 候選與上線阻斷。",
    liveWalletConnectorCandidates: "Connector 候選",
    liveWalletConnectorDisabledReviewRequired: "已關閉 / 需審核",
    liveWalletConnectorMissingEvidence: "缺失真實證據",
    liveWalletConnectorConfigRequired: "需要配置門禁",
    liveWalletConnectorReviewApprovalRequired: "需要 live QA 與審核批准",
    liveWalletConnectorReleaseGuardrail: "本 mission 不啟用生產連接",
    liveWalletConnectorPackage: "候選 package",
    lifecycleAllowed: "允許",
    lifecycleBlocked: "阻斷",
    lifecycleBlockingChecks: "阻斷檢查",
    lifecycleCurrentStatus: "目前狀態",
    lifecycleCurrentStatusDetail: "來自目前 seeded 活動 shell。",
    lifecycleExportSensitive: "匯出敏感操作",
    lifecycleExportSensitiveDetail: "匯出與歸檔意圖保持先審核。",
    lifecycleGateGroup: "門禁分組",
    lifecycleLaunchBlockers: "上線阻斷",
    lifecycleLocalOnlyBoundary: "Lifecycle 本地邊界",
    lifecycleNotApplicable: "不適用",
    lifecycleOperationCount: "個 lifecycle 操作",
    lifecycleOperations: "Lifecycle 操作",
    lifecycleOperationsEyebrow: "活動 lifecycle",
    lifecycleOperationsSubtitle: "面向專案方的安全狀態操作，用於上線、排期、匯出與歸檔決策。",
    lifecycleOwner: "負責人",
    lifecycleOwnerAction: "專案方動作",
    lifecycleReviewRequired: "需要審核",
    lifecycleSummary: "Lifecycle 操作摘要",
    lifecycleTopNextAction: "首要下一步",
    launchConsoleAudience: "受眾",
    launchConsoleBlocked: "阻斷",
    launchConsoleBoundary: "非即時邊界",
    launchConsoleCampaignIntent: "活動意圖",
    launchConsoleGateEvidence: "門禁 evidence",
    launchConsoleHandoffRequired: "需要 handoff",
    launchConsoleHandoffs: "Skill handoff",
    launchConsoleLaunchBlocking: "上線阻斷",
    launchConsoleLocalOnly: "本地預覽",
    launchConsoleNextAction: "下一步",
    launchConsoleNoLiveBoundary: "僅 seeded/本地預覽。不會連接真實 Launch Console，不會自動建立或發布活動，不會呼叫外部 API、錢包簽名、合約寫入、導出檔案或獎勵發放。",
    launchConsoleOwner: "負責人",
    launchConsoleReady: "就緒",
    launchConsoleRecommendedTiming: "時機",
    launchConsoleReviewRequired: "需要審核",
    launchConsoleStage: "階段",
    launchConsoleSummary: "活動包摘要",
    launchConsoleTaskCategoryContentAnalytics: "內容 / 分析",
    launchConsoleTaskCategoryOnChainApi: "鏈上 / API",
    launchConsoleTaskCategorySocialManual: "社交 / 人工",
    launchConsoleTaskCategoryWallet: "錢包",
    launchConsoleTasks: "任務區塊",
    launchConsoleBundles: "Launch Console 活動包",
    launchConsoleBundlesSubtitle: "面向預熱、上線與上線後階段審核的 seeded/本地 launch package；任何真實 Launch Console handoff 前都需要複核。",
    launchConsoleTotalBundles: "活動包總數",
    aiPlannerLaunchApprovalRoutes: "審批路線",
    aiPlannerLaunchBoundary: "發布邊界",
    aiPlannerLaunchDecision: "AI Planner 發布決策",
    aiPlannerLaunchDecisionItems: "發布決策項",
    aiPlannerLaunchDecisionSubtitle: "面向已選任務、繼承發布門禁、負責人路線與不自動發布邊界的本地審核包。",
    aiPlannerLaunchInheritedGateCount: "繼承門禁",
    aiPlannerLaunchInheritedGates: "繼承發布門禁",
    aiPlannerLaunchLocaleReadiness: "語言 readiness",
    aiPlannerLaunchPoints: "積分",
    aiPlannerLaunchSelectedTaskCount: "已選任務",
    aiPlannerLaunchSelectedTasks: "已選任務模板",
    aiPlannerLaunchSelectedTemplate: "已選活動模板",
    aiPlannerLaunchSelectedTemplateCount: "已選模板",
    aiPlannerLaunchVerification: "驗證方式",
    aiPlannerLaunchWalletCompatibility: "錢包相容",
    aiPlannerLaunchBlocksPublish: "阻斷發布",
    campaignCreationWorkflowReadiness: "活動建立流程 Readiness",
    campaignCreationWorkflowSubtitle: "v0.2 建立活動流程的有序 seeded/本地 readiness；不會觸發即時建立或發布。",
    campaignCreationWorkflowStepList: "建立流程步驟",
    campaignCreationWorkflowReadySteps: "就緒步驟",
    campaignCreationWorkflowReviewSteps: "需審核步驟",
    campaignCreationWorkflowWarningSteps: "警告步驟",
    campaignCreationWorkflowBlockedSteps: "阻斷步驟",
    campaignCreationWorkflowInheritedGates: "繼承門禁",
    campaignCreationWorkflowBoundary: "建立邊界",
    campaignCreationWorkflowEvidence: "Evidence",
    campaignCreationWorkflowBlockers: "阻斷項",
    campaignCreationWorkflowWarnings: "警告項",
    campaignCreationWorkflowNoIssues: "無繼承阻斷或警告",
    campaignCreationWorkflowSourceChecklist: "來源檢查清單",
    localeAnalyticsBoundary: "僅本地準備度；未接入即時 analytics SDK、事件採集、crawler 服務或外部 dashboard。",
    localeAnalyticsMetric: "指標",
    localeAnalyticsReadiness: "語言 analytics readiness",
    localeAnalyticsReadinessSubtitle: "接入真實 analytics 前，依 MVP 語言展示 seeded readiness 行。",
    localeAnalyticsValue: "數值",
    aiOpsKpiAdoption: "AI Ops KPI 採納看板",
    aiOpsKpiAdoptionSubtitle: "面向 AI 草稿、內容採納、節省編輯時間、報告生成和建議採納的 seeded/本地指標。",
    aiOpsKpiBlocked: "阻斷 KPI",
    aiOpsKpiBoundary: "KPI 邊界",
    aiOpsKpiEvidence: "證據",
    aiOpsKpiNextAction: "下一步",
    aiOpsKpiOwner: "負責人",
    aiOpsKpiReady: "就緒 KPI",
    aiOpsKpiReadinessBlocked: "阻斷",
    aiOpsKpiReadinessReady: "就緒",
    aiOpsKpiReadinessReviewRequired: "需要審核",
    aiOpsKpiReview: "需審核 KPI",
    aiOpsKpiSource: "來源",
    aiOpsKpiStrongestSignal: "最強採納訊號",
    aiOpsKpiTarget: "目標",
    aiOpsKpiTopNextAction: "最高優先級動作",
    aiOpsKpiTotal: "KPI 總數",
    aiOpsKpiTrend: "趨勢",
    aiOpsKpiValue: "數值",
    projectWorkspace: "專案控制台工作區",
    projectWorkspaceNavigation: "專案控制台工作區導航",
    stateComponentsBoundary: "狀態畫廊邊界",
    stateComponentsBlocked: "阻斷狀態",
    stateComponentsCovered: "已覆蓋狀態",
    stateComponentsDeliveryGallery: "狀態元件交付畫廊",
    stateComponentsExamples: "代表性狀態",
    stateComponentsFamilies: "狀態族",
    stateComponentsReviewRequired: "需審核狀態",
    stateComponentsSourceReferences: "來源引用",
    stateComponentsSubtitle: "基於 seeded/本地資料集中審核 loading、empty、error、toast、modal、發布阻斷、活動、任務、資格、i18n、錢包 QA 與匯出審核狀態。",
    templatesWorkspaceBoundary: "模板選擇保持本地預覽，並保留錢包相容性、驗證方式與語言 readiness 訊號。",
    translationReviewState: "英文已發布；繁中目前為 fallback/readiness lane，需人工審核後才可視為最終翻譯。",
    verificationRulesAffectedOutcomes: "影響結果類型",
    verificationRulesProviderEvidence: "驗證 provider 證據",
    verificationRulesProviderLaunchBlockers: "Provider 上線阻斷",
    verificationRulesSummary: "驗證規則摘要",
    verificationRulesTopRule: "最高優先級規則",
    workspaceAiContentSummary: "審核生成內容、優化建議、人工批准狀態與不自動發布邊界。",
    workspaceAnalyticsSummary: "查看 seeded KPI、漏斗流失、錢包占比、語言占比與語言 analytics readiness。",
    workspaceCampaigns: "活動",
    workspaceCampaignsSummary: "監控活動組合狀態、目前活動指標、風險、導出準備度與專案方下一步動作。",
    workspaceCloseout: "復盤",
    workspaceCloseoutSummary: "審核活動後的 analytics、AI winner 報告、匯出 readiness、風險、獎勵責任、歸檔狀態與下一輪動作。",
    workspaceCreateSummary: "依目標、任務、獎勵、i18n、合約與發布檢查點建立並審核活動草稿。",
    workspaceExportSummary: "審核已驗證導出行、CSV 欄位、證據覆蓋、API contracts 與獎勵責任。",
    workspaceParticipants: "參與者",
    workspaceParticipantsSummary: "在不發獎的邊界下審核參與者資格、任務進度、風險標記、錢包分佈與匯出姿態。",
    workspaceSettings: "設定",
    workspaceSettingsSummary: "檢查錢包、合約、獎勵、i18n、驗證、匯出與發布設定 readiness，保持只讀。",
    workspaceStates: "狀態",
    workspaceStatesSummary: "集中審核狀態元件覆蓋、恢復動作、來源引用與 no-live 邊界。",
    workspaceTemplatesSummary: "選擇錢包感知任務模板，並查看驗證方式與語言 readiness 上下文。",
    workspaceVerificationRules: "驗證規則",
    workspaceVerificationRulesSummary: "審核鏈上、API、人工審核、邀請、provider 證據、發布影響與 no-live 邊界。",
    zhFallbackWarning: "繁中內容目前回退展示英文或簡中草稿，需人工審核。",
  },
} satisfies Record<BusinessContentLocale, typeof enUS>;

export type ProjectConsoleCopy = (typeof projectConsoleCopy)["en-US"];
