import type { SupportedLocale } from "../../../domain";

const enUS = {
  active: "Live",
  activeWorkspace: "Active workspace",
  apiSkillApiGroup: "API group",
  apiSkillBoundary: "Seeded/local boundary",
  apiSkillContracts: "API / Skill Contracts",
  apiSkillContractsSubtitle: "Read-only contract registry for future agents and APIs.",
  apiSkillCoveredGroups: "Covered v0.2 fields",
  apiSkillEvidence: "Evidence",
  apiSkillExternalEvidence: "External evidence",
  apiSkillFields: "Fields",
  apiSkillHighRisk: "High risk",
  apiSkillInputFields: "Input fields",
  apiSkillLocalOnly: "Local only",
  apiSkillMissing: "Missing skills",
  apiSkillNextAction: "Next action",
  apiSkillOutputFields: "Output fields",
  apiSkillReadiness: "Readiness",
  apiSkillReview: "Review required",
  apiSkillRisk: "Risk",
  apiSkillTotal: "Total contracts",
  aiContent: "AI content",
  aiContentAiDrafts: "AI drafts",
  aiContentArtifacts: "artifacts",
  aiContentChannel: "Channel",
  aiContentCopyReady: "Copy ready",
  aiContentHumanApproved: "Human approved",
  aiContentHumanReviewRequired: "Human review required",
  aiContentLifecycleAiDraft: "AI draft",
  aiContentLifecycleEdited: "Edited",
  aiContentLifecycleHumanApproved: "Human approved",
  aiContentLifecyclePublishIntent: "Publish intent",
  aiContentLifecycleScheduleIntent: "Schedule intent",
  aiContentNextAction: "Next action",
  aiContentPack: "AI Content Pack",
  aiContentPackSubtitle: "Project-owner review of generated campaign copy, release intent, and quality gates.",
  aiContentPublishBlocked: "Publish blocked",
  aiContentPublishReady: "Publish ready",
  aiContentQualityBlockers: "Quality blockers",
  aiContentQualityGates: "Quality gates",
  aiContentReviewer: "Reviewer",
  aiContentRiskLevel: "Risk level",
  aiContentScheduleReady: "Schedule ready",
  aiContentSummary: "AI Content Pack summary",
  aiContentTotalArtifacts: "Total artifacts",
  aiOptimizationLocalOnlyBoundary: "Local-only boundary",
  aiOptimizationNoAutoExecution: "Review input only; no live AI, automatic risk scoring, export, reward distribution, wallet action, or contract execution.",
  aiOptimizationOwnerSafeNextAction: "Owner-safe next action",
  aiOptimizationRecommendedAction: "Recommended action",
  aiOptimizationReviewInput: "Review input / no auto-execution",
  aiOptimizationSubtitle: "Project-owner-safe recommendation from the seeded/local optimization workflow.",
  aiOptimizationSummary: "AI Optimization summary",
  aiPlanner: "AI Campaign Planner",
  aiPlannerAction: "Review generated brief",
  aiPlannerBlocked: "Blocked",
  aiPlannerBoundary: "Planner boundary",
  aiPlannerConfidence: "Confidence",
  aiPlannerDecisionCounts: "Decision counts",
  aiPlannerDefaultLocale: "Default locale",
  aiPlannerGroupList: "Planner recommendation groups",
  aiPlannerNextAction: "Next action",
  aiPlannerOwner: "Owner",
  aiPlannerReady: "Ready",
  aiPlannerRecommendation: "Recommendation",
  aiPlannerReviewRequired: "Review required",
  aiPlannerState: "Draft brief ready for owner review",
  aiPlannerSupportedLocales: "Supported locales",
  aiPlannerWarning: "Warning",
  analyticsExport: "Analytics and Export",
  analyticsExportAction: "Preview winners export",
  analyticsExportState: "Export preview includes wallet, locale, eligibility, and risk fields",
  advancedAnalyticsActionFamily: "Action family",
  advancedAnalyticsAudience: "Audience",
  advancedAnalyticsBoundary: "Advanced analytics boundary",
  advancedAnalyticsCohorts: "Cohorts",
  advancedAnalyticsCohortSegments: "Cohort segments",
  advancedAnalyticsConversionSignal: "Conversion",
  advancedAnalyticsConverted: "Converted",
  advancedAnalyticsCostEfficiency: "Cost efficiency",
  advancedAnalyticsCostPerVerifiedAction: "Cost per verified action",
  advancedAnalyticsCoverage: "Coverage",
  advancedAnalyticsDay7Retention: "Day 7 retention",
  advancedAnalyticsDay30Retention: "Day 30 retention",
  advancedAnalyticsEvidenceGap: "Evidence gap",
  advancedAnalyticsGap: "Gap",
  advancedAnalyticsNextAction: "Next action",
  advancedAnalyticsOwner: "Owner",
  advancedAnalyticsPremiumReadyReports: "Premium-ready reports",
  advancedAnalyticsPremiumReadiness: "Premium analytics readiness",
  advancedAnalyticsProductConversion: "Product conversion",
  advancedAnalyticsProductConversionRows: "Product conversion rows",
  advancedAnalyticsProductCoverage: "Product coverage",
  advancedAnalyticsQualityNote: "Quality note",
  advancedAnalyticsReadiness: "Advanced Analytics readiness",
  advancedAnalyticsReadinessSubtitle: "Seeded cohort, retention, quality, cost, product conversion, and premium report readiness before live analytics.",
  advancedAnalyticsReadyCohorts: "Ready cohorts",
  advancedAnalyticsRealUserQuality: "Real user quality",
  advancedAnalyticsRealUserQualityScore: "Real user quality score",
  advancedAnalyticsRetentionSignal: "Retention",
  advancedAnalyticsReviewCohorts: "Review cohorts",
  advancedAnalyticsRewardBudget: "Reward budget",
  advancedAnalyticsRiskReview: "Risk review",
  advancedAnalyticsSampleBasis: "Sample basis",
  advancedAnalyticsSummary: "Advanced analytics summary",
  advancedAnalyticsRetentionWindows: "Retention windows",
  advancedAnalyticsVerifiedActions: "Verified actions",
  advancedAnalyticsWalletMix: "Wallet mix",
  contractImpact: "Contract Impact Review",
  contractImpactAction: "Open review notes",
  contractImpactState: "Off-chain MVP mode; no contract migration required",
  contractModeOffChain: "OFF CHAIN MVP",
  contractMode: "Contract mode",
  countBlockers: "blockers",
  countPassed: "passed",
  countWarnings: "warnings",
  completionRate: "Completion rate",
  connectedWallets: "Connected wallets",
  dashboardTitle: "Project Console",
  dashboardSubtitle: "Operational snapshot for the active campaign shell.",
  exportReady: "Export-ready winners",
  exportDisclaimer: "Export winners does not distribute rewards.",
  localeCoverage: "Locale coverage",
  localeAnalyticsReadiness: "Locale analytics readiness",
  localeAnalyticsReadinessSubtitle: "Seeded readiness rows by MVP locale before real analytics wiring.",
  localeAnalyticsMetric: "Metric",
  localeAnalyticsValue: "Value",
  localeAnalyticsBoundary: "Local readiness only. No live analytics SDK, event ingestion, crawler service, or external dashboard is connected.",
  lifecycleAllowed: "Allowed",
  lifecycleBlocked: "Blocked",
  lifecycleBlockingChecks: "Blocking checks",
  lifecycleCurrentStatus: "Current status",
  lifecycleCurrentStatusDetail: "Derived from the active seeded campaign shell.",
  lifecycleExportSensitive: "Export-sensitive operations",
  lifecycleExportSensitiveDetail: "Export and archive intents stay review-first.",
  lifecycleGateGroup: "Gate group",
  lifecycleLaunchBlockers: "launch blockers",
  lifecycleLocalOnlyBoundary: "Lifecycle local-only boundary",
  lifecycleNotApplicable: "Not applicable",
  lifecycleOperationCount: "lifecycle operations",
  lifecycleOperations: "Lifecycle operations",
  lifecycleOperationsEyebrow: "Campaign lifecycle",
  lifecycleOperationsSubtitle: "Owner-safe status operations for launch, schedule, export, and archive decisions.",
  lifecycleOwner: "Owner",
  lifecycleOwnerAction: "Owner action",
  lifecycleReviewRequired: "Review required",
  lifecycleSummary: "Lifecycle operations summary",
  lifecycleTopNextAction: "Top next action",
  launchConsoleAudience: "Audience",
  launchConsoleBlocked: "Blocked",
  launchConsoleBoundary: "No-live boundary",
  launchConsoleCampaignIntent: "Campaign intent",
  launchConsoleGateEvidence: "Gate evidence",
  launchConsoleHandoffRequired: "Handoff required",
  launchConsoleHandoffs: "Skill handoffs",
  launchConsoleLaunchBlocking: "Launch blocking",
  launchConsoleLocalOnly: "Local only",
  launchConsoleNextAction: "Next action",
  launchConsoleNoLiveBoundary: "Seeded/local preview only. No live Launch Console, no automatic campaign creation or publish, no external API, wallet signing, contract write, export file, or reward distribution is executed.",
  launchConsoleOwner: "Owner",
  launchConsoleReady: "Ready",
  launchConsoleRecommendedTiming: "Timing",
  launchConsoleReviewRequired: "Review required",
  launchConsoleStage: "Stage",
  launchConsoleSummary: "Bundle summary",
  launchConsoleTaskCategoryContentAnalytics: "Content / analytics",
  launchConsoleTaskCategoryOnChainApi: "On-chain / API",
  launchConsoleTaskCategorySocialManual: "Social / manual",
  launchConsoleTaskCategoryWallet: "Wallet",
  launchConsoleTasks: "Task blocks",
  launchConsoleBundles: "Launch Console campaign bundles",
  launchConsoleBundlesSubtitle: "Seeded/local launch packages for pre-launch, launch, and post-launch review before any live Launch Console handoff.",
  launchConsoleTotalBundles: "Total bundles",
  readiness: "Publish readiness",
  riskQueue: "Risk review queue",
  taskCount: "configured tasks",
  rewardsEligibility: "Rewards & Eligibility",
  rewardsEligibilityAction: "Check participant eligibility",
  rewardsEligibilityState: "Eligibility preview separates missing tasks and risk flags",
  taskBuilder: "Task Builder Preview",
  taskBuilderAction: "Review task compatibility",
  taskBuilderState: "Wallet-aware tasks cover AA, EOA, and any-wallet participation",
  translationReview: "i18n Translation Review",
  translationReviewAction: "Review Chinese draft",
  translationReviewState: "English is published; Chinese remains AI draft/fallback",
  walletSplit: "AA / EOA split",
  walletAdapterReadiness: "aelf-web-login adapter readiness",
  walletAdapterReadinessSubtitle: "AA and EOA wallet adapter readiness before live SDK wiring.",
  walletAdapterConfigured: "Configured adapters",
  walletAdapterEnabledPreview: "Enabled preview",
  walletAdapterMaintenance: "Maintenance",
  walletAdapterMissingLiveEvidence: "Missing live evidence",
  walletAdapterReleaseBlockers: "Release blockers",
  walletAdapterFeatureGate: "Feature gate",
  walletAdapterFallback: "Fallback",
  walletAdapterNextAction: "Next action",
  walletAdapterBoundary: "No live wallet SDK boundary",
  zhFallbackWarning: "Chinese content falls back to English until reviewed.",
  warning: "Warning",
  blocker: "Blocker",
  builderAiOutline: "AI generated outline",
  builderAiPrompt: "AI prompt",
  builderAnyWalletDefault: "Default recommended",
  builderCompleteness: "Draft completeness",
  builderCompletenessSummary: "Basics are complete; contract and risk checks remain visible before publish.",
  builderEntryAction: "Open builder draft",
  builderEntryState: "Draft setup combines AI brief and structured campaign fields",
  builderEntryTitle: "Campaign Builder",
  builderFormState: "Structured form state",
  builderLocaleScope: "Locale scope",
  builderLocaleScopeDetail: "Default and fallback: en-US. Supported: en-US, zh-CN, and zh-TW fallback readiness.",
  builderMissingBasics: "Missing required basics",
  builderNoMissingBasics: "No missing basics",
  builderOverview: "Draft overview",
  builderObjective: "Objective",
  builderProject: "Project",
  builderTargetUsers: "Target users",
  builderTimePeriod: "Time period",
  builderWalletPolicy: "Wallet policy",
  commandCenter: "Campaign Command Center",
  commandCenterSubtitle: "Project-owner view of campaign states, risk, export readiness, and next actions.",
  commandCenterSummary: "Campaign portfolio",
  commandCampaigns: "campaigns",
  commandLive: "Live",
  commandScheduledDraft: "Scheduled / draft",
  commandEnded: "Ended",
  commandExported: "Exported",
  commandWarnings: "Warnings",
  commandBlockers: "Blockers",
  commandNextAction: "Owner action",
  commandPriority: "Priority",
  commandRisk: "Risk",
  commandExport: "Export",
  commandTimeWindow: "Time window",
  commandLocale: "Locale",
  commandWallet: "Wallet split",
  createStepContract: "Contract",
  createStepGoal: "Goal",
  createStepI18n: "i18n",
  createStepPrefix: "Step",
  createStepPublishReadiness: "Publish readiness",
  createStepRewardsEligibility: "Rewards & Eligibility",
  createStepTasks: "Tasks",
  createWorkspaceStepper: "Create campaign checkpoints",
  createWorkspaceStepperSummary: "Project-owner checkpoints for goal, task, reward, locale, contract, and publish readiness review.",
  analyticsExportDecision: "Analytics & Export Decision",
  analyticsExportDecisionSubtitle: "Owner-facing quality metrics before approving winner export.",
  dropOffPoint: "Largest drop-off",
  readyRows: "Ready rows",
  reviewRequiredRows: "Review-required rows",
  blockedRows: "Blocked rows",
  rowStatusCounts: "Row status counts",
  exportBatch: "Export batch",
  exportAcknowledgements: "acknowledgements",
  csvColumns: "CSV columns",
  evidenceCoverage: "Evidence coverage",
  exportConfirmationReadiness: "Export confirmation readiness",
  exportConfirmationReadinessEyebrow: "Seeded/local export gate",
  exportConfirmationReadinessSubtitle: "Preview modes, required fields, row reasons, acknowledgements, and root blockers before owner approval.",
  exportConfirmationSummary: "Export confirmation summary",
  exportContractRootReadiness: "Contract root readiness",
  exportCoveredFields: "Covered fields",
  exportIncludedFields: "Included fields",
  exportLocalPreviewOnly: "Local preview only",
  exportMissingFields: "Missing fields",
  exportPreviewModes: "CSV / JSON preview modes",
  exportProjectAcknowledgements: "Project acknowledgements",
  exportRealFile: "Real file",
  exportRequiredFields: "Required export fields",
  exportRootClaimBlocked: "Root and claim execution blockers",
  exportRowReasonCoverage: "Row reason coverage",
  exportSafeDefault: "Safe default: no contract root",
  exportTotalRows: "total rows",
  exportWorkspaceDecision: "Export Decision",
  exportWorkspaceDecisionSubtitle: "Seeded export preview for verified rows, CSV contract, evidence coverage, and reward responsibility.",
  providerEvidenceRegistry: "Provider evidence registry",
  providerEvidenceRegistrySubtitle: "Adapter readiness, feature gates, fallbacks, and launch blockers before live provider wiring.",
  providerRegistryTotalEntries: "Registry entries",
  providerRegistryMissingLiveEvidence: "Missing live evidence",
  providerRegistryLocalOnly: "Local-only paths",
  providerRegistryReviewRequired: "Review-required paths",
  providerRegistryUnavailable: "Unavailable paths",
  providerRegistryBlocked: "Blocked paths",
  providerRegistryLaunchBlockers: "Launch blockers",
  providerRegistryFeatureGate: "Feature gate",
  providerRegistryFallback: "Fallback",
  providerRegistryAdapterReadiness: "Adapter readiness",
  providerRegistryUnavailableReadiness: "Unavailable",
  providerRegistryBlockedReadiness: "Blocked",
  providerRegistryLocalOnlyBoundary: "Seeded/local provider evidence only",
  eligible: "Eligible",
  ineligible: "Ineligible",
  missingTask: "Missing task",
  open: "Open",
  approved: "Approved",
  published: "published",
  aiDraft: "AI draft",
  apiSkillReadinessBlocked: "Blocked",
  apiSkillReadinessLocalOnly: "Local only",
  apiSkillReadinessReady: "Ready",
  apiSkillReadinessReviewRequired: "Review required",
  reviewed: "reviewed",
  fallback: "fallback",
  formObjective: "Objective confirmed",
  formReward: "Reward plan confirmed",
  formTimeline: "Timeline confirmed",
  formWallet: "Wallet policy confirmed",
  serviceBoundaryDetail: "No live backend/API, wallet signature, secret storage, real export file, reward distribution, or contract root write.",
  serviceBoundaryTitle: "Seeded/local boundary",
  serviceCoverage: "Service coverage",
  serviceCoveredApiGroups: "Covered API groups",
  serviceCoveredFieldGroups: "Covered field groups",
  serviceFacade: "Local API Service Facade",
  serviceFacadeSubtitle: "Callable seeded/local service surface for v0.2 API and UI coverage.",
  serviceReadinessBlocked: "Blocked",
  serviceReadinessLocalOnly: "Local only",
  serviceReadinessReady: "Ready",
  serviceReadinessReviewRequired: "Review required",
  serviceSampleResponses: "Sample responses",
  serviceTotalServices: "Total services",
  verificationPipelineAffectedOutcomes: "Affected outcomes",
  verificationPipelineBlockedPaths: "Blocked paths",
  verificationPipelineCompleted: "Completed",
  verificationPipelineEligibilityImpact: "Eligibility impact",
  verificationPipelineFailed: "Failed",
  verificationPipelineFallbackReason: "Fallback reason",
  verificationPipelineLiveEvidence: "Live evidence",
  verificationPipelineLiveReady: "Live ready",
  verificationPipelineManualReviewPaths: "Manual review paths",
  verificationPipelineMissingLiveEvidence: "Missing live evidence",
  verificationPipelineMissingRequiredTasks: "Missing required tasks",
  verificationPipelineNextAction: "Operator next action",
  verificationPipelineNone: "None",
  verificationPipelinePending: "Pending",
  verificationPipelineReadiness: "Verification pipeline readiness",
  verificationPipelineReadinessSubtitle: "Provider readiness, task outcomes, eligibility impact, and non-live boundaries for launch review.",
  verificationPipelineReferralQualification: "Referral qualification",
  verificationPipelineReleaseImpact: "Release impact",
  verificationPipelineRiskFlags: "Risk flags",
  verificationPipelineSeededCoverage: "Seeded/local coverage",
  verificationPipelineSeededReady: "Seeded ready",
  verificationPipelineTaskOutcomeCoverage: "Task outcome coverage",
  verificationPipelineTotalPaths: "Total paths",
  projectWorkspace: "Project Console workspace",
  projectWorkspaceNavigation: "Project Console workspace navigation",
  templatesWorkspaceBoundary: "Template selection stays local and preserves wallet compatibility, verification type, and locale readiness signals.",
  verificationBoundary: "Verification boundary",
  verificationCoverage: "Verification coverage",
  verificationEvidenceCategories: "Evidence categories",
  verificationManualReview: "Manual review",
  verificationProviderReadiness: "Provider readiness",
  verificationRiskStates: "Risk-sensitive states",
  workspaceAiContent: "AI Content",
  workspaceAiContentSummary: "Review generated content, optimization recommendations, human approval state, and no-auto-publish boundaries.",
  workspaceAnalytics: "Analytics",
  workspaceAnalyticsSummary: "Inspect seeded KPIs, funnel drop-off, wallet split, locale split, and locale analytics readiness.",
  workspaceCampaigns: "Campaigns",
  workspaceCampaignsSummary: "Monitor portfolio state, active campaign metrics, risk, export readiness, and owner next actions.",
  workspaceCreate: "Create",
  workspaceCreateSummary: "Create and review campaign drafts through goal, task, reward, i18n, contract, and publish checkpoints.",
  workspaceExport: "Export",
  workspaceExportSummary: "Review verified export rows, CSV columns, evidence coverage, API contracts, and reward responsibility.",
  workspaceTemplates: "Templates",
  workspaceTemplatesSummary: "Choose wallet-aware task templates with verification and language readiness context.",
} satisfies Record<string, string>;

const zhCN = {
  active: "进行中",
  activeWorkspace: "当前工作区",
  apiSkillApiGroup: "API 分组",
  apiSkillBoundary: "Seeded/本地边界",
  apiSkillContracts: "API / Skill Contracts",
  apiSkillContractsSubtitle: "面向未来 agent 与 API 的只读 contract registry。",
  apiSkillCoveredGroups: "已覆盖 v0.2 字段",
  apiSkillEvidence: "Evidence",
  apiSkillExternalEvidence: "外部 evidence",
  apiSkillFields: "字段",
  apiSkillHighRisk: "高风险",
  apiSkillInputFields: "输入字段",
  apiSkillLocalOnly: "仅本地",
  apiSkillMissing: "缺失 skills",
  apiSkillNextAction: "下一步",
  apiSkillOutputFields: "输出字段",
  apiSkillReadiness: "Readiness",
  apiSkillReview: "需要审核",
  apiSkillRisk: "风险",
  apiSkillTotal: "Contract 总数",
  aiContent: "AI 内容",
  aiContentAiDrafts: "AI 草稿",
  aiContentArtifacts: "个内容",
  aiContentChannel: "渠道",
  aiContentCopyReady: "可复制",
  aiContentHumanApproved: "人工已批准",
  aiContentHumanReviewRequired: "需要人工审核",
  aiContentLifecycleAiDraft: "AI 草稿",
  aiContentLifecycleEdited: "已编辑",
  aiContentLifecycleHumanApproved: "人工已批准",
  aiContentLifecyclePublishIntent: "发布意图",
  aiContentLifecycleScheduleIntent: "排期意图",
  aiContentNextAction: "下一步",
  aiContentPack: "AI 内容包",
  aiContentPackSubtitle: "项目方审核生成文案、发布意图与质量门禁的工作区。",
  aiContentPublishBlocked: "发布已阻断",
  aiContentPublishReady: "可发布",
  aiContentQualityBlockers: "质量阻断",
  aiContentQualityGates: "质量门禁",
  aiContentReviewer: "审核人",
  aiContentRiskLevel: "风险等级",
  aiContentScheduleReady: "可排期",
  aiContentSummary: "AI 内容包摘要",
  aiContentTotalArtifacts: "内容总数",
  aiOptimizationLocalOnlyBoundary: "本地边界",
  aiOptimizationNoAutoExecution: "仅作为审核输入；不会执行实时 AI、自动风险评分、导出、发奖、钱包动作或合约执行。",
  aiOptimizationOwnerSafeNextAction: "项目方安全下一步",
  aiOptimizationRecommendedAction: "推荐动作",
  aiOptimizationReviewInput: "审核输入 / 不自动执行",
  aiOptimizationSubtitle: "来自 seeded/本地优化工作流的项目方安全建议。",
  aiOptimizationSummary: "AI 优化摘要",
  aiPlanner: "AI 活动策划",
  aiPlannerAction: "审核生成简报",
  aiPlannerBlocked: "阻断",
  aiPlannerBoundary: "Planner 边界",
  aiPlannerConfidence: "置信度",
  aiPlannerDecisionCounts: "决策统计",
  aiPlannerDefaultLocale: "默认语言",
  aiPlannerGroupList: "Planner 推荐分组",
  aiPlannerNextAction: "下一步",
  aiPlannerOwner: "负责人",
  aiPlannerReady: "就绪",
  aiPlannerRecommendation: "推荐",
  aiPlannerReviewRequired: "需要审核",
  aiPlannerState: "活动简报草稿已生成，等待项目方审核",
  aiPlannerSupportedLocales: "支持语言",
  aiPlannerWarning: "警告",
  analyticsExport: "数据分析与导出",
  analyticsExportAction: "预览 winners 导出",
  analyticsExportState: "导出预览包含钱包、语言、资格和风险字段",
  advancedAnalyticsActionFamily: "行为类型",
  advancedAnalyticsAudience: "受众",
  advancedAnalyticsBoundary: "高级分析边界",
  advancedAnalyticsCohorts: "Cohorts",
  advancedAnalyticsCohortSegments: "Cohort segments",
  advancedAnalyticsConversionSignal: "转化",
  advancedAnalyticsConverted: "已转化",
  advancedAnalyticsCostEfficiency: "成本效率",
  advancedAnalyticsCostPerVerifiedAction: "Cost per verified action",
  advancedAnalyticsCoverage: "覆盖",
  advancedAnalyticsDay7Retention: "Day 7 留存",
  advancedAnalyticsDay30Retention: "Day 30 留存",
  advancedAnalyticsEvidenceGap: "Evidence gap",
  advancedAnalyticsGap: "缺口",
  advancedAnalyticsNextAction: "下一步",
  advancedAnalyticsOwner: "负责人",
  advancedAnalyticsPremiumReadyReports: "Premium-ready reports",
  advancedAnalyticsPremiumReadiness: "Premium analytics readiness",
  advancedAnalyticsProductConversion: "产品转化",
  advancedAnalyticsProductConversionRows: "产品转化明细",
  advancedAnalyticsProductCoverage: "产品覆盖",
  advancedAnalyticsQualityNote: "质量备注",
  advancedAnalyticsReadiness: "高级分析 readiness",
  advancedAnalyticsReadinessSubtitle: "接入实时 analytics 前，展示 seeded cohort、留存、真实用户质量、成本、产品转化与 premium report readiness。",
  advancedAnalyticsReadyCohorts: "就绪 cohorts",
  advancedAnalyticsRealUserQuality: "真实用户质量",
  advancedAnalyticsRealUserQualityScore: "真实用户质量分",
  advancedAnalyticsRetentionSignal: "留存",
  advancedAnalyticsReviewCohorts: "需复核 cohorts",
  advancedAnalyticsRewardBudget: "奖励预算",
  advancedAnalyticsRiskReview: "风险审核",
  advancedAnalyticsSampleBasis: "样本依据",
  advancedAnalyticsSummary: "高级分析摘要",
  advancedAnalyticsRetentionWindows: "留存窗口",
  advancedAnalyticsVerifiedActions: "已验证行为",
  advancedAnalyticsWalletMix: "钱包组合",
  contractImpact: "合约影响审核",
  contractImpactAction: "打开审核备注",
  contractImpactState: "Off-chain MVP 模式；无需合约迁移",
  contractModeOffChain: "OFF CHAIN MVP",
  contractMode: "合约模式",
  countBlockers: "个阻断项",
  countPassed: "项通过",
  countWarnings: "个警告",
  completionRate: "完成率",
  connectedWallets: "已连接钱包",
  dashboardTitle: "项目控制台",
  dashboardSubtitle: "当前活动 shell 的运营快照。",
  exportReady: "可导出 winners",
  exportDisclaimer: "导出 winners 不等于发奖。",
  localeCoverage: "语言覆盖率",
  localeAnalyticsReadiness: "语言 analytics 就绪状态",
  localeAnalyticsReadinessSubtitle: "接入真实 analytics 前，按 MVP 语言展示 seeded readiness 行。",
  localeAnalyticsMetric: "指标",
  localeAnalyticsValue: "数值",
  localeAnalyticsBoundary: "仅本地准备度；未接入实时 analytics SDK、事件采集、crawler 服务或外部 dashboard。",
  lifecycleAllowed: "允许",
  lifecycleBlocked: "阻断",
  lifecycleBlockingChecks: "阻断检查",
  lifecycleCurrentStatus: "当前状态",
  lifecycleCurrentStatusDetail: "来自当前 seeded 活动 shell。",
  lifecycleExportSensitive: "导出敏感操作",
  lifecycleExportSensitiveDetail: "导出与归档意图保持先审核。",
  lifecycleGateGroup: "门禁分组",
  lifecycleLaunchBlockers: "上线阻断",
  lifecycleLocalOnlyBoundary: "Lifecycle 本地边界",
  lifecycleNotApplicable: "不适用",
  lifecycleOperationCount: "个 lifecycle 操作",
  lifecycleOperations: "Lifecycle 操作",
  lifecycleOperationsEyebrow: "活动 lifecycle",
  lifecycleOperationsSubtitle: "面向项目方的安全状态操作，用于上线、排期、导出与归档决策。",
  lifecycleOwner: "负责人",
  lifecycleOwnerAction: "项目方动作",
  lifecycleReviewRequired: "需要审核",
  lifecycleSummary: "Lifecycle 操作摘要",
  lifecycleTopNextAction: "首要下一步",
  launchConsoleAudience: "受众",
  launchConsoleBlocked: "阻断",
  launchConsoleBoundary: "非实时边界",
  launchConsoleCampaignIntent: "活动意图",
  launchConsoleGateEvidence: "门禁 evidence",
  launchConsoleHandoffRequired: "需要 handoff",
  launchConsoleHandoffs: "Skill handoff",
  launchConsoleLaunchBlocking: "上线阻断",
  launchConsoleLocalOnly: "本地预览",
  launchConsoleNextAction: "下一步",
  launchConsoleNoLiveBoundary: "仅 seeded/本地预览。不会连接真实 Launch Console，不会自动创建或发布活动，不会调用外部 API、钱包签名、合约写入、导出文件或奖励发放。",
  launchConsoleOwner: "负责人",
  launchConsoleReady: "就绪",
  launchConsoleRecommendedTiming: "时机",
  launchConsoleReviewRequired: "需要审核",
  launchConsoleStage: "阶段",
  launchConsoleSummary: "活动包摘要",
  launchConsoleTaskCategoryContentAnalytics: "内容 / 分析",
  launchConsoleTaskCategoryOnChainApi: "链上 / API",
  launchConsoleTaskCategorySocialManual: "社交 / 人工",
  launchConsoleTaskCategoryWallet: "钱包",
  launchConsoleTasks: "任务块",
  launchConsoleBundles: "Launch Console 活动包",
  launchConsoleBundlesSubtitle: "面向预热、上线与上线后三阶段审核的 seeded/本地 launch package；任何真实 Launch Console handoff 前都需要复核。",
  launchConsoleTotalBundles: "活动包总数",
  readiness: "发布 readiness",
  riskQueue: "风险审核队列",
  taskCount: "个已配置任务",
  rewardsEligibility: "奖励与资格",
  rewardsEligibilityAction: "检查参与者资格",
  rewardsEligibilityState: "资格预览区分缺失任务和风险标记",
  taskBuilder: "任务构建预览",
  taskBuilderAction: "审核钱包兼容性",
  taskBuilderState: "钱包感知任务覆盖 AA、EOA 与任意钱包参与",
  translationReview: "i18n 翻译审核",
  translationReviewAction: "审核中文草稿",
  translationReviewState: "英文已发布；中文仍为 AI 草稿/回退状态",
  walletSplit: "AA / EOA 占比",
  walletAdapterReadiness: "aelf-web-login adapter readiness",
  walletAdapterReadinessSubtitle: "接入真实 SDK 前的 AA 与 EOA 钱包 adapter readiness。",
  walletAdapterConfigured: "已配置 adapter",
  walletAdapterEnabledPreview: "预览启用",
  walletAdapterMaintenance: "维护中",
  walletAdapterMissingLiveEvidence: "缺失真实证据",
  walletAdapterReleaseBlockers: "发布阻断",
  walletAdapterFeatureGate: "功能门禁",
  walletAdapterFallback: "Fallback",
  walletAdapterNextAction: "下一步",
  walletAdapterBoundary: "无实时钱包 SDK 边界",
  zhFallbackWarning: "中文内容在审核前回退展示英文。",
  warning: "警告",
  blocker: "阻断",
  builderAiOutline: "AI 生成大纲",
  builderAiPrompt: "AI Prompt",
  builderAnyWalletDefault: "默认推荐",
  builderCompleteness: "草稿完整度",
  builderCompletenessSummary: "基础信息已完成；发布前仍展示合约与风险检查。",
  builderEntryAction: "打开活动草稿",
  builderEntryState: "草稿设置结合 AI 简报与结构化活动字段",
  builderEntryTitle: "活动构建器",
  builderFormState: "结构化表单状态",
  builderLocaleScope: "语言范围",
  builderLocaleScopeDetail: "默认与回退：en-US。支持：en-US、zh-CN 与 zh-TW 回退 readiness。",
  builderMissingBasics: "缺失必填基础信息",
  builderNoMissingBasics: "无缺失基础信息",
  builderOverview: "草稿概览",
  builderObjective: "目标",
  builderProject: "项目",
  builderTargetUsers: "目标用户",
  builderTimePeriod: "活动周期",
  builderWalletPolicy: "钱包策略",
  commandCenter: "活动指挥中心",
  commandCenterSubtitle: "面向项目方的活动状态、风险、导出准备度和下一步动作视图。",
  commandCenterSummary: "活动组合",
  commandCampaigns: "个活动",
  commandLive: "进行中",
  commandScheduledDraft: "已排期 / 草稿",
  commandEnded: "已结束",
  commandExported: "已导出",
  commandWarnings: "警告",
  commandBlockers: "阻断",
  commandNextAction: "项目方动作",
  commandPriority: "优先级",
  commandRisk: "风险",
  commandExport: "导出",
  commandTimeWindow: "活动周期",
  commandLocale: "语言",
  commandWallet: "钱包占比",
  createStepContract: "合约",
  createStepGoal: "目标",
  createStepI18n: "i18n",
  createStepPrefix: "步骤",
  createStepPublishReadiness: "发布准备度",
  createStepRewardsEligibility: "奖励与资格",
  createStepTasks: "任务",
  createWorkspaceStepper: "创建活动检查点",
  createWorkspaceStepperSummary: "项目方按目标、任务、奖励、语言、合约与发布准备度检查活动草稿。",
  analyticsExportDecision: "分析与导出决策",
  analyticsExportDecisionSubtitle: "批准 winners 导出前，项目方需要看的质量指标。",
  dropOffPoint: "最大流失点",
  readyRows: "就绪行",
  reviewRequiredRows: "需复核行",
  blockedRows: "阻断行",
  rowStatusCounts: "行状态统计",
  exportBatch: "导出批次",
  exportAcknowledgements: "确认项",
  csvColumns: "CSV 字段",
  evidenceCoverage: "证据覆盖",
  exportConfirmationReadiness: "导出确认 readiness",
  exportConfirmationReadinessEyebrow: "Seeded/本地导出门禁",
  exportConfirmationReadinessSubtitle: "项目方批准前检查预览模式、必需字段、行原因、确认项与 root 阻断。",
  exportConfirmationSummary: "导出确认摘要",
  exportContractRootReadiness: "合约 root readiness",
  exportCoveredFields: "已覆盖字段",
  exportIncludedFields: "包含字段",
  exportLocalPreviewOnly: "仅本地预览",
  exportMissingFields: "缺失字段",
  exportPreviewModes: "CSV / JSON 预览模式",
  exportProjectAcknowledgements: "项目方确认项",
  exportRealFile: "真实文件",
  exportRequiredFields: "必需导出字段",
  exportRootClaimBlocked: "Root 与 claim 执行阻断",
  exportRowReasonCoverage: "行原因覆盖",
  exportSafeDefault: "安全默认：不生成合约 root",
  exportTotalRows: "总行数",
  exportWorkspaceDecision: "导出决策",
  exportWorkspaceDecisionSubtitle: "基于 seeded 数据预览已验证行、CSV 合约、证据覆盖与奖励责任。",
  providerEvidenceRegistry: "Provider 证据登记表",
  providerEvidenceRegistrySubtitle: "接入真实 provider 前，审核 adapter readiness、配置门禁、fallback 与上线阻断。",
  providerRegistryTotalEntries: "登记条目",
  providerRegistryMissingLiveEvidence: "缺失真实 evidence",
  providerRegistryLocalOnly: "仅本地路径",
  providerRegistryReviewRequired: "需复核路径",
  providerRegistryUnavailable: "不可用路径",
  providerRegistryBlocked: "阻断路径",
  providerRegistryLaunchBlockers: "上线阻断",
  providerRegistryFeatureGate: "配置门禁",
  providerRegistryFallback: "Fallback",
  providerRegistryAdapterReadiness: "Adapter readiness",
  providerRegistryUnavailableReadiness: "不可用",
  providerRegistryBlockedReadiness: "阻断",
  providerRegistryLocalOnlyBoundary: "仅 seeded/本地 provider 证据",
  eligible: "符合资格",
  ineligible: "不符合资格",
  missingTask: "缺失任务",
  open: "待处理",
  approved: "已批准",
  published: "已发布",
  aiDraft: "AI 草稿",
  apiSkillReadinessBlocked: "阻断",
  apiSkillReadinessLocalOnly: "仅本地",
  apiSkillReadinessReady: "就绪",
  apiSkillReadinessReviewRequired: "需要审核",
  reviewed: "已审核",
  fallback: "回退",
  formObjective: "目标已确认",
  formReward: "奖励方案已确认",
  formTimeline: "周期已确认",
  formWallet: "钱包策略已确认",
  serviceBoundaryDetail: "不会调用 live backend/API、钱包签名、secret 存储、真实导出文件、奖励发放或合约 root 写入。",
  serviceBoundaryTitle: "Seeded/本地边界",
  serviceCoverage: "Service 覆盖",
  serviceCoveredApiGroups: "已覆盖 API 分组",
  serviceCoveredFieldGroups: "已覆盖字段分组",
  serviceFacade: "本地 API Service Facade",
  serviceFacadeSubtitle: "面向 v0.2 API 与 UI 覆盖的可调用 seeded/本地 service surface。",
  serviceReadinessBlocked: "阻断",
  serviceReadinessLocalOnly: "仅本地",
  serviceReadinessReady: "就绪",
  serviceReadinessReviewRequired: "需要审核",
  serviceSampleResponses: "示例响应",
  serviceTotalServices: "服务总数",
  verificationPipelineAffectedOutcomes: "影响结果",
  verificationPipelineBlockedPaths: "阻断路径",
  verificationPipelineCompleted: "已完成",
  verificationPipelineEligibilityImpact: "资格影响",
  verificationPipelineFailed: "失败",
  verificationPipelineFallbackReason: "Fallback 原因",
  verificationPipelineLiveEvidence: "实时 evidence",
  verificationPipelineLiveReady: "实时就绪",
  verificationPipelineManualReviewPaths: "人工审核路径",
  verificationPipelineMissingLiveEvidence: "缺失实时 evidence",
  verificationPipelineMissingRequiredTasks: "缺失必做任务",
  verificationPipelineNextAction: "运营下一步",
  verificationPipelineNone: "无",
  verificationPipelinePending: "待验证",
  verificationPipelineReadiness: "验证 pipeline readiness",
  verificationPipelineReadinessSubtitle: "用于发布审核的 provider readiness、任务结果、资格影响与非实时边界。",
  verificationPipelineReferralQualification: "邀请资格",
  verificationPipelineReleaseImpact: "发布影响",
  verificationPipelineRiskFlags: "风险标记",
  verificationPipelineSeededCoverage: "Seeded/本地覆盖",
  verificationPipelineSeededReady: "Seeded 就绪",
  verificationPipelineTaskOutcomeCoverage: "任务结果覆盖",
  verificationPipelineTotalPaths: "路径总数",
  projectWorkspace: "项目控制台工作区",
  projectWorkspaceNavigation: "项目控制台工作区导航",
  templatesWorkspaceBoundary: "模板选择保持本地预览，并保留钱包兼容性、验证方式与语言 readiness 信号。",
  verificationBoundary: "验证边界",
  verificationCoverage: "验证覆盖",
  verificationEvidenceCategories: "Evidence 分类",
  verificationManualReview: "人工审核",
  verificationProviderReadiness: "Provider readiness",
  verificationRiskStates: "风险敏感状态",
  workspaceAiContent: "AI 内容",
  workspaceAiContentSummary: "审核生成内容、优化建议、人工批准状态与不自动发布边界。",
  workspaceAnalytics: "分析",
  workspaceAnalyticsSummary: "查看 seeded KPI、漏斗流失、钱包占比、语言占比与语言 analytics readiness。",
  workspaceCampaigns: "活动",
  workspaceCampaignsSummary: "监控活动组合状态、当前活动指标、风险、导出准备度与项目方下一步动作。",
  workspaceCreate: "创建",
  workspaceCreateSummary: "按目标、任务、奖励、i18n、合约与发布检查点创建并审核活动草稿。",
  workspaceExport: "导出",
  workspaceExportSummary: "审核已验证导出行、CSV 字段、证据覆盖、API contracts 与奖励责任。",
  workspaceTemplates: "模板",
  workspaceTemplatesSummary: "选择钱包感知任务模板，并查看验证方式与语言 readiness 上下文。",
} satisfies typeof enUS;

export const projectConsoleCopy = {
  "en-US": enUS,
  "zh-CN": zhCN,
  "zh-TW": {
    ...zhCN,
    builderLocaleScopeDetail: "預設與回退：en-US。支援：en-US、zh-CN 與 zh-TW 回退 readiness。",
    createWorkspaceStepperSummary: "專案方依目標、任務、獎勵、語言、合約與發布準備度檢查活動草稿。",
    exportAcknowledgements: "確認項",
    exportConfirmationReadiness: "匯出確認 readiness",
    exportConfirmationReadinessEyebrow: "Seeded/本地匯出門禁",
    exportConfirmationReadinessSubtitle: "專案方批准前檢查預覽模式、必要欄位、行原因、確認項與 root 阻斷。",
    exportConfirmationSummary: "匯出確認摘要",
    exportContractRootReadiness: "合約 root readiness",
    exportCoveredFields: "已覆蓋欄位",
    exportIncludedFields: "包含欄位",
    exportLocalPreviewOnly: "僅本地預覽",
    exportMissingFields: "缺失欄位",
    exportPreviewModes: "CSV / JSON 預覽模式",
    exportProjectAcknowledgements: "專案方確認項",
    exportRealFile: "真實檔案",
    exportRequiredFields: "必要匯出欄位",
    exportRootClaimBlocked: "Root 與 claim 執行阻斷",
    exportRowReasonCoverage: "行原因覆蓋",
    exportSafeDefault: "安全預設：不生成合約 root",
    exportTotalRows: "總行數",
    exportWorkspaceDecisionSubtitle: "基於 seeded 資料預覽已驗證行、CSV contract、證據覆蓋與獎勵責任。",
    fallback: "回退",
    providerEvidenceRegistry: "Provider 證據登記表",
    providerEvidenceRegistrySubtitle: "接入真實 provider 前，審核 adapter readiness、配置門禁、fallback 與上線阻斷。",
    providerRegistryBlocked: "阻斷路徑",
    providerRegistryBlockedReadiness: "阻斷",
    providerRegistryFeatureGate: "配置門禁",
    providerRegistryFallback: "Fallback",
    providerRegistryLaunchBlockers: "上線阻斷",
    providerRegistryLocalOnly: "僅本地路徑",
    providerRegistryLocalOnlyBoundary: "僅 seeded/本地 provider 證據",
    providerRegistryMissingLiveEvidence: "缺失真實 evidence",
    providerRegistryReviewRequired: "需複核路徑",
    providerRegistryTotalEntries: "登記條目",
    providerRegistryUnavailable: "不可用路徑",
    providerRegistryUnavailableReadiness: "不可用",
    walletAdapterReadiness: "aelf-web-login adapter readiness",
    walletAdapterReadinessSubtitle: "接入真實 SDK 前的 AA 與 EOA 錢包 adapter readiness。",
    walletAdapterConfigured: "已配置 adapter",
    walletAdapterEnabledPreview: "預覽啟用",
    walletAdapterMaintenance: "維護中",
    walletAdapterMissingLiveEvidence: "缺失真實證據",
    walletAdapterReleaseBlockers: "發布阻斷",
    walletAdapterFeatureGate: "功能門禁",
    walletAdapterFallback: "Fallback",
    walletAdapterNextAction: "下一步",
    walletAdapterBoundary: "無即時錢包 SDK 邊界",
    lifecycleAllowed: "允許",
    lifecycleBlocked: "阻斷",
    lifecycleBlockingChecks: "阻斷檢查",
    lifecycleCurrentStatus: "目前狀態",
    lifecycleCurrentStatusDetail: "來自目前 seeded 活動 shell。",
    lifecycleExportSensitive: "匯出敏感操作",
    lifecycleExportSensitiveDetail: "匯出與歸檔意圖保持先審核。",
    lifecycleGateGroup: "門禁分組",
    lifecycleLaunchBlockers: "上線阻斷",
    lifecycleLocalOnlyBoundary: "Lifecycle 本地邊界",
    lifecycleNotApplicable: "不適用",
    lifecycleOperationCount: "個 lifecycle 操作",
    lifecycleOperations: "Lifecycle 操作",
    lifecycleOperationsEyebrow: "活動 lifecycle",
    lifecycleOperationsSubtitle: "面向專案方的安全狀態操作，用於上線、排期、匯出與歸檔決策。",
    lifecycleOwner: "負責人",
    lifecycleOwnerAction: "專案方動作",
    lifecycleReviewRequired: "需要審核",
    lifecycleSummary: "Lifecycle 操作摘要",
    lifecycleTopNextAction: "首要下一步",
    launchConsoleAudience: "受眾",
    launchConsoleBlocked: "阻斷",
    launchConsoleBoundary: "非即時邊界",
    launchConsoleCampaignIntent: "活動意圖",
    launchConsoleGateEvidence: "門禁 evidence",
    launchConsoleHandoffRequired: "需要 handoff",
    launchConsoleHandoffs: "Skill handoff",
    launchConsoleLaunchBlocking: "上線阻斷",
    launchConsoleLocalOnly: "本地預覽",
    launchConsoleNextAction: "下一步",
    launchConsoleNoLiveBoundary: "僅 seeded/本地預覽。不會連接真實 Launch Console，不會自動建立或發布活動，不會呼叫外部 API、錢包簽名、合約寫入、導出檔案或獎勵發放。",
    launchConsoleOwner: "負責人",
    launchConsoleReady: "就緒",
    launchConsoleRecommendedTiming: "時機",
    launchConsoleReviewRequired: "需要審核",
    launchConsoleStage: "階段",
    launchConsoleSummary: "活動包摘要",
    launchConsoleTaskCategoryContentAnalytics: "內容 / 分析",
    launchConsoleTaskCategoryOnChainApi: "鏈上 / API",
    launchConsoleTaskCategorySocialManual: "社交 / 人工",
    launchConsoleTaskCategoryWallet: "錢包",
    launchConsoleTasks: "任務區塊",
    launchConsoleBundles: "Launch Console 活動包",
    launchConsoleBundlesSubtitle: "面向預熱、上線與上線後階段審核的 seeded/本地 launch package；任何真實 Launch Console handoff 前都需要複核。",
    launchConsoleTotalBundles: "活動包總數",
    localeAnalyticsBoundary: "僅本地準備度；未接入即時 analytics SDK、事件採集、crawler 服務或外部 dashboard。",
    localeAnalyticsMetric: "指標",
    localeAnalyticsReadiness: "語言 analytics readiness",
    localeAnalyticsReadinessSubtitle: "接入真實 analytics 前，依 MVP 語言展示 seeded readiness 行。",
    localeAnalyticsValue: "數值",
    projectWorkspace: "專案控制台工作區",
    projectWorkspaceNavigation: "專案控制台工作區導航",
    templatesWorkspaceBoundary: "模板選擇保持本地預覽，並保留錢包相容性、驗證方式與語言 readiness 訊號。",
    translationReviewState: "英文已發布；繁中目前為 fallback/readiness lane，需人工審核後才可視為最終翻譯。",
    workspaceAiContentSummary: "審核生成內容、優化建議、人工批准狀態與不自動發布邊界。",
    workspaceAnalyticsSummary: "查看 seeded KPI、漏斗流失、錢包占比、語言占比與語言 analytics readiness。",
    workspaceCampaigns: "活動",
    workspaceCampaignsSummary: "監控活動組合狀態、目前活動指標、風險、導出準備度與專案方下一步動作。",
    workspaceCreateSummary: "依目標、任務、獎勵、i18n、合約與發布檢查點建立並審核活動草稿。",
    workspaceExportSummary: "審核已驗證導出行、CSV 欄位、證據覆蓋、API contracts 與獎勵責任。",
    workspaceTemplatesSummary: "選擇錢包感知任務模板，並查看驗證方式與語言 readiness 上下文。",
    zhFallbackWarning: "繁中內容目前回退展示英文或簡中草稿，需人工審核。",
  },
} satisfies Record<SupportedLocale, typeof enUS>;

export type ProjectConsoleCopy = (typeof projectConsoleCopy)["en-US"];
