import type { SupportedLocale } from "../../../domain";

export const projectConsoleCopy = {
  "en-US": {
    active: "Live",
    aiPlanner: "AI Campaign Planner",
    aiPlannerAction: "Review generated brief",
    aiPlannerState: "Draft brief ready for owner review",
    analyticsExport: "Analytics and Export",
    analyticsExportAction: "Preview winners export",
    analyticsExportState: "Export preview includes wallet, locale, eligibility, and risk fields",
    contractImpact: "Contract Impact Review",
    contractImpactAction: "Open review notes",
    contractImpactState: "Off-chain MVP mode; no contract migration required",
    contractModeOffChain: "OFF CHAIN MVP",
    contractMode: "Contract mode",
    countBlockers: "blockers",
    countPassed: "passed",
    countWarnings: "warnings",
    completionRate: "Completion rate",
    connectedWallets: "Connected wallets",
    dashboardTitle: "Project Console",
    dashboardSubtitle: "Operational snapshot for the active campaign shell.",
    exportReady: "Export-ready winners",
    exportDisclaimer: "Export winners does not distribute rewards.",
    localeCoverage: "Locale coverage",
    readiness: "Publish readiness",
    riskQueue: "Risk review queue",
    taskCount: "configured tasks",
    rewardsEligibility: "Rewards & Eligibility",
    rewardsEligibilityAction: "Check participant eligibility",
    rewardsEligibilityState: "Eligibility preview separates missing tasks and risk flags",
    taskBuilder: "Task Builder Preview",
    taskBuilderAction: "Review task compatibility",
    taskBuilderState: "Wallet-aware tasks cover AA, EOA, and any-wallet participation",
    translationReview: "i18n Translation Review",
    translationReviewAction: "Review Chinese draft",
    translationReviewState: "English is published; Chinese remains AI draft/fallback",
    walletSplit: "AA / EOA split",
    zhFallbackWarning: "Chinese content falls back to English until reviewed.",
    warning: "Warning",
    blocker: "Blocker",
    builderAiOutline: "AI generated outline",
    builderAiPrompt: "AI prompt",
    builderAnyWalletDefault: "Default recommended",
    builderCompleteness: "Draft completeness",
    builderCompletenessSummary: "Basics are complete; contract and risk checks remain visible before publish.",
    builderEntryAction: "Open builder draft",
    builderEntryState: "Draft setup combines AI brief and structured campaign fields",
    builderEntryTitle: "Campaign Builder",
    builderFormState: "Structured form state",
    builderLocaleScope: "Locale scope",
    builderLocaleScopeDetail: "Default and fallback: en-US. Supported: en-US and zh-CN.",
    builderMissingBasics: "Missing required basics",
    builderNoMissingBasics: "No missing basics",
    builderOverview: "Draft overview",
    builderObjective: "Objective",
    builderProject: "Project",
    builderTargetUsers: "Target users",
    builderTimePeriod: "Time period",
    builderWalletPolicy: "Wallet policy",
    eligible: "Eligible",
    ineligible: "Ineligible",
    missingTask: "Missing task",
    open: "Open",
    approved: "Approved",
    published: "published",
    aiDraft: "AI draft",
    reviewed: "reviewed",
    fallback: "fallback",
    formObjective: "Objective confirmed",
    formReward: "Reward plan confirmed",
    formTimeline: "Timeline confirmed",
    formWallet: "Wallet policy confirmed",
  },
  "zh-CN": {
    active: "进行中",
    aiPlanner: "AI 活动策划",
    aiPlannerAction: "审核生成简报",
    aiPlannerState: "活动简报草稿已生成，等待项目方审核",
    analyticsExport: "数据分析与导出",
    analyticsExportAction: "预览 winners 导出",
    analyticsExportState: "导出预览包含钱包、语言、资格和风险字段",
    contractImpact: "合约影响审核",
    contractImpactAction: "打开审核备注",
    contractImpactState: "Off-chain MVP 模式；无需合约迁移",
    contractModeOffChain: "OFF CHAIN MVP",
    contractMode: "合约模式",
    countBlockers: "个阻断项",
    countPassed: "项通过",
    countWarnings: "个警告",
    completionRate: "完成率",
    connectedWallets: "已连接钱包",
    dashboardTitle: "项目控制台",
    dashboardSubtitle: "当前活动 shell 的运营快照。",
    exportReady: "可导出 winners",
    exportDisclaimer: "导出 winners 不等于发奖。",
    localeCoverage: "语言覆盖率",
    readiness: "发布 readiness",
    riskQueue: "风险审核队列",
    taskCount: "个已配置任务",
    rewardsEligibility: "奖励与资格",
    rewardsEligibilityAction: "检查参与者资格",
    rewardsEligibilityState: "资格预览区分缺失任务和风险标记",
    taskBuilder: "任务构建预览",
    taskBuilderAction: "审核钱包兼容性",
    taskBuilderState: "钱包感知任务覆盖 AA、EOA 与任意钱包参与",
    translationReview: "i18n 翻译审核",
    translationReviewAction: "审核中文草稿",
    translationReviewState: "英文已发布；中文仍为 AI 草稿/回退状态",
    walletSplit: "AA / EOA 占比",
    zhFallbackWarning: "中文内容在审核前回退展示英文。",
    warning: "警告",
    blocker: "阻断",
    builderAiOutline: "AI 生成大纲",
    builderAiPrompt: "AI Prompt",
    builderAnyWalletDefault: "默认推荐",
    builderCompleteness: "草稿完整度",
    builderCompletenessSummary: "基础信息已完成；发布前仍展示合约与风险检查。",
    builderEntryAction: "打开活动草稿",
    builderEntryState: "草稿设置结合 AI 简报与结构化活动字段",
    builderEntryTitle: "活动构建器",
    builderFormState: "结构化表单状态",
    builderLocaleScope: "语言范围",
    builderLocaleScopeDetail: "默认与回退：en-US。支持：en-US 和 zh-CN。",
    builderMissingBasics: "缺失必填基础信息",
    builderNoMissingBasics: "无缺失基础信息",
    builderOverview: "草稿概览",
    builderObjective: "目标",
    builderProject: "项目",
    builderTargetUsers: "目标用户",
    builderTimePeriod: "活动周期",
    builderWalletPolicy: "钱包策略",
    eligible: "符合资格",
    ineligible: "不符合资格",
    missingTask: "缺失任务",
    open: "待处理",
    approved: "已批准",
    published: "已发布",
    aiDraft: "AI 草稿",
    reviewed: "已审核",
    fallback: "回退",
    formObjective: "目标已确认",
    formReward: "奖励方案已确认",
    formTimeline: "周期已确认",
    formWallet: "钱包策略已确认",
  },
} satisfies Record<SupportedLocale, Record<string, string>>;

export type ProjectConsoleCopy = (typeof projectConsoleCopy)["en-US"];
