import "@testing-library/jest-dom/vitest";
import { fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import { App } from "../../../app/App";
import { EXPORT_CSV_COLUMNS } from "../../../domain";

const exportColumnContract = EXPORT_CSV_COLUMNS.join(",");

const expectVisibleText = (text: string | RegExp) => {
  expect(screen.getAllByText(text).length).toBeGreaterThan(0);
};

describe("Admin/Ops shell", () => {
  afterEach(() => {
    window.localStorage.clear();
  });

  it("renders review gates, contract boundaries, and export preview", () => {
    render(<App />);

    fireEvent.click(screen.getByRole("button", { name: "Admin/Ops" }));

    expect(screen.getByRole("heading", { name: "Review queue" })).toBeInTheDocument();
    expectVisibleText("Chinese copy needs human review");
    expectVisibleText("Off-chain MVP: no contract migration required");
    expect(screen.getByRole("heading", { name: "Delivery Checklist Readiness" })).toBeInTheDocument();
    expectVisibleText("v0.2 delivery audit");
    expectVisibleText("Product Checklist");
    expectVisibleText("Architecture Checklist");
    expectVisibleText("UI Checklist");
    expectVisibleText("Contract Checklist");
    expectVisibleText("QA Checklist");
    expectVisibleText("Covered");
    expectVisibleText("Needs review");
    expectVisibleText("Deferred");
    expectVisibleText("AA + EOA wallet support");
    expectVisibleText("Wallet modal has Recommended, EOA, and Advanced sections");
    expectVisibleText("Normalized wallet session schema");
    expectVisibleText("Reward disclaimer per locale");
    expectVisibleText("Contract impact review before publish");
    expectVisibleText("Portkey AA connect tested");
    expectVisibleText("Wrong chain error tested");
    expectVisibleText("Export CSV columns tested");
    expectVisibleText("Contract claim mode requires admin approval");
    expectVisibleText("Reward custody excluded from MVP");
    expectVisibleText(/This console does not execute live wallet SDK/);
    expectVisibleText(/No live wallet SDK, API call, contract transaction, export file/);
    expectVisibleText("Admin Contract Review Center");
    expectVisibleText("V2 companion needed");
    expect(screen.getByText("No for MVP; recommended for P1 transparency.")).toBeInTheDocument();
    expectVisibleText("Metadata hash");
    expect(screen.getByText("Optional for MVP; planned for CampaignRegistryV2 metadata URI/hash.")).toBeInTheDocument();
    expectVisibleText("Verifier role");
    expect(screen.getByText("Backend verifier only; no contract write authority in MVP.")).toBeInTheDocument();
    expectVisibleText("Reward custody");
    expect(screen.getByText("Project-owned; None in Campaign OS.")).toBeInTheDocument();
    expectVisibleText("High-impact checklist");
    expectVisibleText("Contract claim gate");
    expectVisibleText("Blocked until high-impact manual review");
    expectVisibleText("Do not enable claim mode in the MVP shell.");
    expectVisibleText("Contract evolution");
    expectVisibleText("CampaignRegistryV2 metadata hash");
    expectVisibleText("Points and referral roots");
    expectVisibleText("Optional contract claim");
    expectVisibleText(/No live contract transaction/);
    expectVisibleText(/no reward custody/);
    expectVisibleText("Contract Interface Matrix Console");
    expectVisibleText("Companion contracts");
    expectVisibleText("Contract methods");
    expectVisibleText("Change matrix");
    expectVisibleText("Current MVP");
    expectVisibleText("Recommended V2");
    expectVisibleText("Priority / phase");
    expectVisibleText(/No ABI generation/);
    expectVisibleText(/No live contract transaction/);
    expectVisibleText(/No reward custody \/ no reward distribution/);
    expectVisibleText("CampaignRegistryV2");
    expectVisibleText("CampaignPointsLedgerV2");
    expectVisibleText("ReferralRegistryV2");
    expectVisibleText("EligibilityRootRegistryV2");
    expectVisibleText("CreateCampaign");
    expectVisibleText("CommitPointsBatch");
    expectVisibleText("BindReferral");
    expectVisibleText("SetEligibilityRoot");
    expectVisibleText("VerifyEligibilityProof");
    expectVisibleText("Rewards");
    expectVisibleText("Multilingual content");
    expectVisibleText("Wallet type");
    expectVisibleText("Risk flags");
    expectVisibleText(/Campaign OS does not custody or distribute rewards/);
    expectVisibleText("Chinese AI draft/fallback");
    expectVisibleText("No auto-publish: human review is required before Chinese draft can ship.");
    expect(screen.getByRole("heading", { name: "Template Governance" })).toBeInTheDocument();
    expectVisibleText("Template Manager");
    expectVisibleText("8 templates");
    expectVisibleText("Localization review");
    expectVisibleText("Risk review");
    expectVisibleText(/No live template registry/);
    expectVisibleText("Bridge with eBridge");
    expectVisibleText("Share campaign post");
    expectVisibleText("EOA only");
    expect(screen.getByRole("heading", { name: "AI Content Pack Workbench" })).toBeInTheDocument();
    expectVisibleText("7 artifacts");
    expectVisibleText("No auto-publish boundary");
    expectVisibleText("X / Twitter thread");
    expectVisibleText("Telegram announcement");
    expectVisibleText("Discord message");
    expectVisibleText("FAQ");
    expectVisibleText("Tutorial");
    expectVisibleText("Daily report");
    expectVisibleText("Winner report");
    expectVisibleText("Publish blocked");
    expectVisibleText("Copy ready");
    expectVisibleText("Reward responsibility");
    expectVisibleText("Winner rules");
    expectVisibleText("Localization readiness");
    expectVisibleText("Reviewer: legal_ops");
    expectVisibleText("Reviewer: community_ops");
    const telegramCard = screen.getByText("Telegram announcement").closest("article");
    expect(telegramCard).not.toBeNull();
    expect(within(telegramCard as HTMLElement).getAllByText("Human review required").length).toBeGreaterThan(0);
    expectVisibleText(/No live AI provider/);
    expectVisibleText("CONTRACT CLAIM");
    expectVisibleText("Contract claim is blocked pending high-impact manual review.");
    expectVisibleText("Analytics overview");
    expectVisibleText("Verified actions");
    expectVisibleText("Conversion funnel");
    expectVisibleText("Wallet connect");
    expectVisibleText("Wallet split");
    expectVisibleText("Locale split");
    expectVisibleText("Risk dashboard");
    expectVisibleText("Bot/sybil review");
    expectVisibleText("AI Ops reports");
    expectVisibleText("Daily AI Ops summary");
    expectVisibleText("Human review required");
    expectVisibleText("Ecosystem metrics");
    expectVisibleText("TMRWDAO");
    expectVisibleText("Export winners does not distribute rewards.");
    expectVisibleText(exportColumnContract);
    expectVisibleText("Campaign OS exports verified records only.");
    expectVisibleText("Final reward distribution is handled by the campaign project.");
    expect(screen.getByText("Risk flags and eligibility results are review inputs; Campaign OS does not distribute rewards.")).toBeInTheDocument();
    expectVisibleText("Export batch: export-awaken-sprint-preview");
    expectVisibleText("3E9...7cD");
    expectVisibleText("PORTKEY_EOA_EXTENSION");
    expectVisibleText("zh-CN");
    expectVisibleText("review_required");
    expectVisibleText("REF...3E9");
    expectVisibleText("referral_velocity_review");
    expectVisibleText(/task-bridge:pending:aelfscan/);
    expectVisibleText(/task-social:failed:social_api/);
    expectVisibleText(/demo-task-bridge-3E9/);
    expectVisibleText(/demo-task-social-3E9/);
    expect(screen.queryByText("zh-TW")).not.toBeInTheDocument();
  });

  it("switches Admin/Ops copy manually to zh-CN", () => {
    render(<App />);

    fireEvent.change(screen.getByLabelText("Language"), { target: { value: "zh-CN" } });
    fireEvent.click(screen.getByRole("button", { name: "管理员/Ops" }));

    expect(screen.getByRole("heading", { name: "审核队列" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "交付清单 Readiness" })).toBeInTheDocument();
    expectVisibleText("v0.2 交付审计");
    expectVisibleText("产品清单");
    expectVisibleText("架构清单");
    expectVisibleText("UI 清单");
    expectVisibleText("合约清单");
    expectVisibleText("QA 清单");
    expectVisibleText("已覆盖");
    expectVisibleText("需要复核");
    expectVisibleText("已后置");
    expectVisibleText("AA + EOA 钱包支持");
    expectVisibleText("钱包弹窗包含 Recommended、EOA 与 Advanced 分区");
    expectVisibleText("归一化钱包 session schema");
    expectVisibleText("每个语言的奖励免责声明");
    expectVisibleText("发布前合约影响审核");
    expectVisibleText("Portkey AA 连接测试");
    expectVisibleText("错误链错误状态测试");
    expectVisibleText("导出 CSV 字段测试");
    expectVisibleText("Contract claim 模式需要管理员批准");
    expectVisibleText("奖励托管排除在 MVP 外");
    expectVisibleText(/这个控制台不会执行实时钱包 SDK/);
    expectVisibleText(/不会执行实时钱包 SDK、API 调用、合约交易、导出文件/);
    expectVisibleText("AI 内容审核");
    expectVisibleText("分析概览");
    expectVisibleText("转化漏斗");
    expectVisibleText("钱包拆分");
    expectVisibleText("语言拆分");
    expectVisibleText("风险看板");
    expectVisibleText("机器人/女巫审核");
    expectVisibleText("AI Ops 报告");
    expectVisibleText("生态指标");
    expectVisibleText("禁止自动发布：中文草稿发布前必须经过人工审核。");
    expect(screen.getByRole("heading", { name: "模板治理" })).toBeInTheDocument();
    expectVisibleText("模板管理");
    expectVisibleText("8 个模板");
    expectVisibleText("本地化审核");
    expectVisibleText("风险审核");
    expectVisibleText(/不会连接实时模板 registry/);
    expectVisibleText("使用 eBridge 跨链");
    expectVisibleText("分享活动动态");
    expectVisibleText("仅 EOA");
    expect(screen.getByRole("heading", { name: "AI 内容包工作台" })).toBeInTheDocument();
    expectVisibleText("7 个内容");
    expectVisibleText("禁止自动发布边界");
    expectVisibleText("X / Twitter 长帖");
    expectVisibleText("Telegram 公告");
    expectVisibleText("Discord 消息");
    expectVisibleText("FAQ");
    expectVisibleText("教程");
    expectVisibleText("日报");
    expectVisibleText("Winner 报告");
    expectVisibleText("发布已阻断");
    expectVisibleText("可复制");
    expectVisibleText("奖励责任");
    expectVisibleText("Winner 规则");
    expectVisibleText("本地化准备度");
    expectVisibleText("审核人: legal_ops");
    expectVisibleText("审核人: community_ops");
    const zhTelegramCard = screen.getByText("Telegram 公告").closest("article");
    expect(zhTelegramCard).not.toBeNull();
    expect(within(zhTelegramCard as HTMLElement).getAllByText("需要人工审核").length).toBeGreaterThan(0);
    expectVisibleText(/不会连接实时 AI/);
    expectVisibleText("管理员合约审核中心");
    expectVisibleText("是否需要 V2 companion");
    expectVisibleText("MVP 不需要；建议 P1 用于透明度增强。");
    expectVisibleText("Metadata hash");
    expectVisibleText("MVP 可选；计划用于 CampaignRegistryV2 metadata URI/hash。");
    expectVisibleText("Verifier role");
    expectVisibleText("仅 backend verifier；MVP 没有合约写权限。");
    expectVisibleText("奖励托管");
    expectVisibleText("项目方持有；Campaign OS 不托管。");
    expectVisibleText("高影响审核清单");
    expectVisibleText("合约领取门禁");
    expectVisibleText("高影响人工审核前保持阻断");
    expectVisibleText("不要在 MVP shell 启用领取模式。");
    expectVisibleText("合约演进路线");
    expectVisibleText("CampaignRegistryV2 metadata hash");
    expectVisibleText("Points 与 referral roots");
    expectVisibleText("可选合约领取");
    expectVisibleText(/不执行真实合约交易/);
    expectVisibleText("合约接口矩阵控制台");
    expectVisibleText("Companion contracts");
    expectVisibleText("合约方法");
    expectVisibleText("变更矩阵");
    expectVisibleText("当前 MVP");
    expectVisibleText("建议 V2");
    expectVisibleText("优先级 / 阶段");
    expectVisibleText(/不会生成 ABI/);
    expectVisibleText(/不会执行真实合约交易/);
    expectVisibleText(/不托管奖励 \/ 不发奖/);
    expectVisibleText("CampaignRegistryV2");
    expectVisibleText("CampaignPointsLedgerV2");
    expectVisibleText("ReferralRegistryV2");
    expectVisibleText("EligibilityRootRegistryV2");
    expectVisibleText("CreateCampaign");
    expectVisibleText("CommitPointsBatch");
    expectVisibleText("BindReferral");
    expectVisibleText("SetEligibilityRoot");
    expectVisibleText("VerifyEligibilityProof");
    expectVisibleText("奖励");
    expectVisibleText("多语言内容");
    expectVisibleText("钱包类型");
    expectVisibleText("风险标记");
    expectVisibleText(/Campaign OS 不托管也不发放奖励/);
    expectVisibleText("合约影响审核");
    expectVisibleText("Contract claim 已阻断，等待高影响人工审核。");
    expectVisibleText("导出 winners 不等于发奖。");
    expectVisibleText(exportColumnContract);
    expectVisibleText("Campaign OS 仅导出已验证记录。");
    expectVisibleText("最终奖励发放由活动项目方处理。");
    expectVisibleText("风险标记与资格结果仅作为审核输入；Campaign OS 不执行发奖。");
    expect(screen.queryByText("zh-TW")).not.toBeInTheDocument();
  });
});
