import "@testing-library/jest-dom/vitest";
import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { App } from "../../../app/App";
import { EXPORT_CSV_COLUMNS } from "../../../domain";

const exportColumnContract = EXPORT_CSV_COLUMNS.join(",");

describe("Admin/Ops shell", () => {
  it("renders review gates, contract boundaries, and export preview", () => {
    render(<App />);

    fireEvent.click(screen.getByRole("button", { name: "Admin/Ops" }));

    expect(screen.getByRole("heading", { name: "Review queue" })).toBeInTheDocument();
    expect(screen.getByText("Chinese copy needs human review")).toBeInTheDocument();
    expect(screen.getByText("Off-chain MVP: no contract migration required")).toBeInTheDocument();
    expect(screen.getByText("Admin Contract Review Center")).toBeInTheDocument();
    expect(screen.getByText("V2 companion needed")).toBeInTheDocument();
    expect(screen.getByText("No for MVP; recommended for P1 transparency.")).toBeInTheDocument();
    expect(screen.getAllByText("Metadata hash").length).toBeGreaterThan(0);
    expect(screen.getByText("Optional for MVP; planned for CampaignRegistryV2 metadata URI/hash.")).toBeInTheDocument();
    expect(screen.getAllByText("Verifier role").length).toBeGreaterThan(0);
    expect(screen.getByText("Backend verifier only; no contract write authority in MVP.")).toBeInTheDocument();
    expect(screen.getAllByText("Reward custody").length).toBeGreaterThan(0);
    expect(screen.getByText("Project-owned; None in Campaign OS.")).toBeInTheDocument();
    expect(screen.getByText("High-impact checklist")).toBeInTheDocument();
    expect(screen.getByText("Contract claim gate")).toBeInTheDocument();
    expect(screen.getByText("Blocked until high-impact manual review")).toBeInTheDocument();
    expect(screen.getByText("Do not enable claim mode in the MVP shell.")).toBeInTheDocument();
    expect(screen.getByText("Contract evolution")).toBeInTheDocument();
    expect(screen.getByText("CampaignRegistryV2 metadata hash")).toBeInTheDocument();
    expect(screen.getByText("Points and referral roots")).toBeInTheDocument();
    expect(screen.getByText("Optional contract claim")).toBeInTheDocument();
    expect(screen.getByText(/No live contract transaction/)).toBeInTheDocument();
    expect(screen.getByText(/no reward custody/)).toBeInTheDocument();
    expect(screen.getByText("Chinese AI draft/fallback")).toBeInTheDocument();
    expect(screen.getAllByText("No auto-publish: human review is required before Chinese draft can ship.").length).toBeGreaterThan(0);
    expect(screen.getByRole("heading", { name: "AI Content Pack Workbench" })).toBeInTheDocument();
    expect(screen.getByText("7 artifacts")).toBeInTheDocument();
    expect(screen.getByText("No auto-publish boundary")).toBeInTheDocument();
    expect(screen.getByText("X / Twitter thread")).toBeInTheDocument();
    expect(screen.getByText("Telegram announcement")).toBeInTheDocument();
    expect(screen.getByText("Discord message")).toBeInTheDocument();
    expect(screen.getByText("FAQ")).toBeInTheDocument();
    expect(screen.getByText("Tutorial")).toBeInTheDocument();
    expect(screen.getByText("Daily report")).toBeInTheDocument();
    expect(screen.getByText("Winner report")).toBeInTheDocument();
    expect(screen.getAllByText("Publish blocked").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Copy ready").length).toBeGreaterThan(0);
    expect(screen.getByText("Reward responsibility")).toBeInTheDocument();
    expect(screen.getByText("Winner rules")).toBeInTheDocument();
    expect(screen.getByText("Localization readiness")).toBeInTheDocument();
    expect(screen.getByText(/No live AI provider/)).toBeInTheDocument();
    expect(screen.getByText("CONTRACT CLAIM")).toBeInTheDocument();
    expect(screen.getByText("Contract claim is blocked pending high-impact manual review.")).toBeInTheDocument();
    expect(screen.getByText("Analytics overview")).toBeInTheDocument();
    expect(screen.getByText("Verified actions")).toBeInTheDocument();
    expect(screen.getByText("Conversion funnel")).toBeInTheDocument();
    expect(screen.getByText("Wallet connect")).toBeInTheDocument();
    expect(screen.getByText("Wallet split")).toBeInTheDocument();
    expect(screen.getByText("Locale split")).toBeInTheDocument();
    expect(screen.getByText("Risk dashboard")).toBeInTheDocument();
    expect(screen.getByText("Bot/sybil review")).toBeInTheDocument();
    expect(screen.getByText("AI Ops reports")).toBeInTheDocument();
    expect(screen.getByText("Daily AI Ops summary")).toBeInTheDocument();
    expect(screen.getAllByText("Human review required").length).toBeGreaterThan(0);
    expect(screen.getByText("Ecosystem metrics")).toBeInTheDocument();
    expect(screen.getByText("TMRWDAO")).toBeInTheDocument();
    expect(screen.getAllByText("Export winners does not distribute rewards.").length).toBeGreaterThan(0);
    expect(screen.getByText(exportColumnContract)).toBeInTheDocument();
    expect(screen.getByText("Campaign OS exports verified records only.")).toBeInTheDocument();
    expect(screen.getByText("Final reward distribution is handled by the campaign project.")).toBeInTheDocument();
    expect(screen.getByText("Risk flags and eligibility results are review inputs; Campaign OS does not distribute rewards.")).toBeInTheDocument();
    expect(screen.getByText("Export batch: export-awaken-sprint-preview")).toBeInTheDocument();
    expect(screen.getByText("3E9...7cD")).toBeInTheDocument();
    expect(screen.getAllByText("PORTKEY_EOA_EXTENSION").length).toBeGreaterThan(0);
    expect(screen.getAllByText("zh-CN").length).toBeGreaterThan(0);
    expect(screen.getAllByText("review_required").length).toBeGreaterThan(0);
    expect(screen.getByText("REF...3E9")).toBeInTheDocument();
    expect(screen.getByText("referral_velocity_review")).toBeInTheDocument();
    expect(screen.getByText(/task-bridge:pending:aelfscan/)).toBeInTheDocument();
    expect(screen.getByText(/task-social:failed:social_api/)).toBeInTheDocument();
    expect(screen.getByText(/demo-task-bridge-3E9/)).toBeInTheDocument();
    expect(screen.getByText(/demo-task-social-3E9/)).toBeInTheDocument();
    expect(screen.queryByText("zh-TW")).not.toBeInTheDocument();
  });

  it("switches Admin/Ops copy manually to zh-CN", () => {
    render(<App />);

    fireEvent.change(screen.getByLabelText("Language"), { target: { value: "zh-CN" } });
    fireEvent.click(screen.getByRole("button", { name: "管理员/Ops" }));

    expect(screen.getByRole("heading", { name: "审核队列" })).toBeInTheDocument();
    expect(screen.getByText("AI 内容审核")).toBeInTheDocument();
    expect(screen.getByText("分析概览")).toBeInTheDocument();
    expect(screen.getByText("转化漏斗")).toBeInTheDocument();
    expect(screen.getByText("钱包拆分")).toBeInTheDocument();
    expect(screen.getByText("语言拆分")).toBeInTheDocument();
    expect(screen.getByText("风险看板")).toBeInTheDocument();
    expect(screen.getByText("机器人/女巫审核")).toBeInTheDocument();
    expect(screen.getByText("AI Ops 报告")).toBeInTheDocument();
    expect(screen.getByText("生态指标")).toBeInTheDocument();
    expect(screen.getAllByText("禁止自动发布：中文草稿发布前必须经过人工审核。").length).toBeGreaterThan(0);
    expect(screen.getByRole("heading", { name: "AI 内容包工作台" })).toBeInTheDocument();
    expect(screen.getByText("7 个内容")).toBeInTheDocument();
    expect(screen.getByText("禁止自动发布边界")).toBeInTheDocument();
    expect(screen.getByText("X / Twitter 长帖")).toBeInTheDocument();
    expect(screen.getByText("Telegram 公告")).toBeInTheDocument();
    expect(screen.getByText("Discord 消息")).toBeInTheDocument();
    expect(screen.getByText("FAQ")).toBeInTheDocument();
    expect(screen.getByText("教程")).toBeInTheDocument();
    expect(screen.getByText("日报")).toBeInTheDocument();
    expect(screen.getByText("Winner 报告")).toBeInTheDocument();
    expect(screen.getAllByText("发布已阻断").length).toBeGreaterThan(0);
    expect(screen.getAllByText("可复制").length).toBeGreaterThan(0);
    expect(screen.getByText("奖励责任")).toBeInTheDocument();
    expect(screen.getByText("Winner 规则")).toBeInTheDocument();
    expect(screen.getByText("本地化准备度")).toBeInTheDocument();
    expect(screen.getByText(/不会连接实时 AI/)).toBeInTheDocument();
    expect(screen.getByText("管理员合约审核中心")).toBeInTheDocument();
    expect(screen.getByText("是否需要 V2 companion")).toBeInTheDocument();
    expect(screen.getByText("MVP 不需要；建议 P1 用于透明度增强。")).toBeInTheDocument();
    expect(screen.getAllByText("Metadata hash").length).toBeGreaterThan(0);
    expect(screen.getByText("MVP 可选；计划用于 CampaignRegistryV2 metadata URI/hash。")).toBeInTheDocument();
    expect(screen.getAllByText("Verifier role").length).toBeGreaterThan(0);
    expect(screen.getByText("仅 backend verifier；MVP 没有合约写权限。")).toBeInTheDocument();
    expect(screen.getAllByText("奖励托管").length).toBeGreaterThan(0);
    expect(screen.getByText("项目方持有；Campaign OS 不托管。")).toBeInTheDocument();
    expect(screen.getByText("高影响审核清单")).toBeInTheDocument();
    expect(screen.getByText("合约领取门禁")).toBeInTheDocument();
    expect(screen.getByText("高影响人工审核前保持阻断")).toBeInTheDocument();
    expect(screen.getByText("不要在 MVP shell 启用领取模式。")).toBeInTheDocument();
    expect(screen.getByText("合约演进路线")).toBeInTheDocument();
    expect(screen.getByText("CampaignRegistryV2 metadata hash")).toBeInTheDocument();
    expect(screen.getByText("Points 与 referral roots")).toBeInTheDocument();
    expect(screen.getByText("可选合约领取")).toBeInTheDocument();
    expect(screen.getByText(/不执行真实合约交易/)).toBeInTheDocument();
    expect(screen.getByText("合约影响审核")).toBeInTheDocument();
    expect(screen.getByText("Contract claim 已阻断，等待高影响人工审核。")).toBeInTheDocument();
    expect(screen.getAllByText("导出 winners 不等于发奖。").length).toBeGreaterThan(0);
    expect(screen.getByText(exportColumnContract)).toBeInTheDocument();
    expect(screen.getByText("Campaign OS 仅导出已验证记录。")).toBeInTheDocument();
    expect(screen.getByText("最终奖励发放由活动项目方处理。")).toBeInTheDocument();
    expect(screen.getByText("风险标记与资格结果仅作为审核输入；Campaign OS 不执行发奖。")).toBeInTheDocument();
    expect(screen.queryByText("zh-TW")).not.toBeInTheDocument();
  });
});
