import type { SupportedLocale } from "../../../domain";

export const adminOpsCopy = {
  "en-US": {
    aiContent: "AI content review",
    autoPublishBlocked: "No auto-publish: human review is required before Chinese draft can ship.",
    blocker: "Blocker",
    blockersWarnings: "Blockers and warnings",
    contractClaim: "CONTRACT CLAIM",
    contractClaimBlocked: "Contract claim is blocked pending high-impact manual review.",
    contractImpact: "Contract impact review",
    contractModes: "Contract mode boundaries",
    defaultSafe: "Default safe mode",
    exportDisclaimer: "Export winners does not distribute rewards.",
    exportPreview: "Export preview",
    exportReady: "Export readiness",
    futurePlanned: "Future/planned",
    humanReviewGate: "Human review gate",
    localePreference: "Locale",
    missingTasks: "Missing tasks",
    offChain: "OFF CHAIN MVP",
    owner: "Owner",
    pointsRank: "Points / rank",
    readiness: "Publish readiness",
    reviewQueue: "Review queue",
    riskFlags: "Risk flags",
    status: "Status",
    title: "Admin/Ops",
    v2Companion: "V2 COMPANION",
    wallet: "Wallet",
    warning: "Warning",
    zhDraft: "Chinese AI draft/fallback",
    enPublished: "English source published",
  },
  "zh-CN": {
    aiContent: "AI 内容审核",
    autoPublishBlocked: "禁止自动发布：中文草稿发布前必须经过人工审核。",
    blocker: "阻断",
    blockersWarnings: "阻断与警告",
    contractClaim: "CONTRACT CLAIM",
    contractClaimBlocked: "Contract claim 已阻断，等待高影响人工审核。",
    contractImpact: "合约影响审核",
    contractModes: "合约模式边界",
    defaultSafe: "默认安全模式",
    exportDisclaimer: "导出 winners 不等于发奖。",
    exportPreview: "导出预览",
    exportReady: "导出就绪",
    futurePlanned: "未来/计划中",
    humanReviewGate: "人工审核门禁",
    localePreference: "语言",
    missingTasks: "缺失任务",
    offChain: "OFF CHAIN MVP",
    owner: "负责人",
    pointsRank: "积分 / 排名",
    readiness: "发布 readiness",
    reviewQueue: "审核队列",
    riskFlags: "风险标记",
    status: "状态",
    title: "管理员/Ops",
    v2Companion: "V2 COMPANION",
    wallet: "钱包",
    warning: "警告",
    zhDraft: "中文 AI 草稿/回退",
    enPublished: "英文源内容已发布",
  },
} satisfies Record<SupportedLocale, Record<string, string>>;
