import type { SupportedLocale } from "../../../domain";

export const adminOpsCopy = {
  "en-US": {
    aiContent: "AI content review",
    aiContentPackWorkbench: "AI Content Pack Workbench",
    aiOpsReports: "AI Ops reports",
    adminContractReviewCenter: "Admin Contract Review Center",
    analyticsOverview: "Analytics overview",
    accountType: "Account type",
    artifacts: "artifacts",
    autoPublishBlocked: "No auto-publish: human review is required before Chinese draft can ship.",
    blocker: "Blocker",
    blockersWarnings: "Blockers and warnings",
    confidence: "Confidence",
    contractClaim: "CONTRACT CLAIM",
    contractClaimBlocked: "Contract claim is blocked pending high-impact manual review.",
    contractEvolution: "Contract evolution",
    contractMode: "Contract mode",
    contractImpact: "Contract impact review",
    contractModes: "Contract mode boundaries",
    contractSurface: "Contract surface",
    conversion: "Conversion",
    conversionFunnel: "Conversion funnel",
    count: "Count",
    copyReady: "Copy ready",
    currentValue: "Current value",
    defaultSafe: "Default safe mode",
    detail: "Detail",
    ecosystemMetrics: "Ecosystem metrics",
    evidence: "Evidence",
    evidenceHashes: "Evidence hashes",
    evidenceSource: "Source",
    evidenceStatus: "Evidence status",
    exactColumnOrder: "Exact CSV column order",
    expectedImpact: "Expected impact",
    exportBatch: "Export batch",
    exportConfirmation: "Export confirmation",
    exportDisclaimer: "Export winners does not distribute rewards.",
    exportEvidence: "Export evidence",
    exportPreview: "Export preview",
    exportReady: "Export readiness",
    finalRewardOwner: "Final reward distribution is handled by the campaign project.",
    futurePlanned: "Future/planned",
    generatedAt: "Generated",
    highImpactChecklist: "High-impact checklist",
    humanReviewGate: "Human review gate",
    humanReviewRequired: "Human review required",
    humanApproved: "Human approved",
    localePreference: "Locale",
    localeSplit: "Locale split",
    metadataHash: "Metadata hash",
    missingTasks: "Missing tasks",
    nextAction: "Next action",
    noHumanReviewRequired: "No human gate",
    offChain: "OFF CHAIN MVP",
    owner: "Owner",
    ownerRole: "Owner role",
    phase: "Phase",
    pointsRank: "Points / rank",
    product: "Product",
    qualitySignal: "Quality signal",
    qualityGates: "Quality gates",
    readiness: "Publish readiness",
    publishBlocked: "Publish blocked",
    recommendation: "Recommendation",
    referrerAddress: "Referrer address",
    requiredFor: "Required for",
    rewardCustody: "Reward custody",
    reviewQueue: "Review queue",
    reviewer: "Reviewer",
    riskEligibilityBoundary: "Risk/eligibility boundaries are review inputs, not automated distribution.",
    riskDashboard: "Risk dashboard",
    riskFlags: "Risk flags",
    riskLevel: "Risk",
    rowCompleteness: "Row completeness",
    scheduleReady: "Schedule ready",
    seededBoundary: "Seeded/local review data. No live analytics, risk scoring, export file, reward distribution, wallet connection, or contract transaction is executed.",
    status: "Status",
    taskEvidence: "Task evidence",
    taskRecords: "Task records",
    templateGovernance: "Template Governance",
    templateGovernanceSubtitle: "Template Manager",
    templateGovernanceBoundary: "Seeded/local template governance",
    templateStatusReady: "Ready",
    templateStatusWarning: "Warning",
    templateStatusBlocked: "Blocked",
    templates: "templates",
    localizationReview: "Localization review",
    riskReview: "Risk review",
    strongVerification: "Strong verification",
    walletCoverage: "Wallet coverage",
    walletAny: "Any wallet",
    walletAaOnly: "AA only",
    walletEoaOnly: "EOA only",
    category: "Category",
    verification: "Verification",
    defaultPoints: "Default points",
    required: "Required",
    optional: "Optional",
    title: "Admin/Ops",
    v2Companion: "V2 COMPANION",
    v2CompanionNeeded: "V2 companion needed",
    verifierRole: "Verifier role",
    verifiedRecordsOnly: "Campaign OS exports verified records only.",
    wallet: "Wallet",
    walletSplit: "Wallet split",
    walletSource: "Wallet source",
    walletTypeVerified: "Wallet type verified",
    warning: "Warning",
    zhDraft: "Chinese AI draft/fallback",
    enPublished: "English source published",
  },
  "zh-CN": {
    aiContent: "AI 内容审核",
    aiContentPackWorkbench: "AI 内容包工作台",
    aiOpsReports: "AI Ops 报告",
    adminContractReviewCenter: "管理员合约审核中心",
    analyticsOverview: "分析概览",
    accountType: "账户类型",
    artifacts: "个内容",
    autoPublishBlocked: "禁止自动发布：中文草稿发布前必须经过人工审核。",
    blocker: "阻断",
    blockersWarnings: "阻断与警告",
    confidence: "置信度",
    contractClaim: "CONTRACT CLAIM",
    contractClaimBlocked: "Contract claim 已阻断，等待高影响人工审核。",
    contractEvolution: "合约演进路线",
    contractMode: "合约模式",
    contractImpact: "合约影响审核",
    contractModes: "合约模式边界",
    contractSurface: "合约面",
    conversion: "转化",
    conversionFunnel: "转化漏斗",
    count: "数量",
    copyReady: "可复制",
    currentValue: "当前值",
    defaultSafe: "默认安全模式",
    detail: "详情",
    ecosystemMetrics: "生态指标",
    evidence: "证据",
    evidenceHashes: "证据哈希",
    evidenceSource: "来源",
    evidenceStatus: "证据状态",
    exactColumnOrder: "精确 CSV 字段顺序",
    expectedImpact: "预期影响",
    exportBatch: "导出批次",
    exportConfirmation: "导出确认",
    exportDisclaimer: "导出 winners 不等于发奖。",
    exportEvidence: "导出证据",
    exportPreview: "导出预览",
    exportReady: "导出就绪",
    finalRewardOwner: "最终奖励发放由活动项目方处理。",
    futurePlanned: "未来/计划中",
    generatedAt: "生成时间",
    highImpactChecklist: "高影响审核清单",
    humanReviewGate: "人工审核门禁",
    humanReviewRequired: "需要人工审核",
    humanApproved: "人工已批准",
    localePreference: "语言",
    localeSplit: "语言拆分",
    metadataHash: "Metadata hash",
    missingTasks: "缺失任务",
    nextAction: "下一步",
    noHumanReviewRequired: "无需人工门禁",
    offChain: "OFF CHAIN MVP",
    owner: "负责人",
    ownerRole: "负责人角色",
    phase: "阶段",
    pointsRank: "积分 / 排名",
    product: "产品",
    qualitySignal: "质量信号",
    qualityGates: "质量门禁",
    readiness: "发布 readiness",
    publishBlocked: "发布已阻断",
    recommendation: "建议",
    referrerAddress: "推荐人地址",
    requiredFor: "适用阶段",
    rewardCustody: "奖励托管",
    reviewQueue: "审核队列",
    reviewer: "审核人",
    riskEligibilityBoundary: "风险/资格边界仅作为审核输入，不会自动发奖。",
    riskDashboard: "风险看板",
    riskFlags: "风险标记",
    riskLevel: "风险",
    rowCompleteness: "行完整度",
    scheduleReady: "可排期",
    seededBoundary: "Seeded/本地审核数据。不会执行实时分析、风险评分、导出文件、发奖、钱包连接或合约交易。",
    status: "状态",
    taskEvidence: "任务证据",
    taskRecords: "任务记录",
    templateGovernance: "模板治理",
    templateGovernanceSubtitle: "模板管理",
    templateGovernanceBoundary: "Seeded/本地模板治理",
    templateStatusReady: "就绪",
    templateStatusWarning: "警告",
    templateStatusBlocked: "阻断",
    templates: "个模板",
    localizationReview: "本地化审核",
    riskReview: "风险审核",
    strongVerification: "强验证",
    walletCoverage: "钱包覆盖",
    walletAny: "任意钱包",
    walletAaOnly: "仅 AA",
    walletEoaOnly: "仅 EOA",
    category: "类别",
    verification: "验证方式",
    defaultPoints: "默认积分",
    required: "必做",
    optional: "可选",
    title: "管理员/Ops",
    v2Companion: "V2 COMPANION",
    v2CompanionNeeded: "是否需要 V2 companion",
    verifierRole: "Verifier role",
    verifiedRecordsOnly: "Campaign OS 仅导出已验证记录。",
    wallet: "钱包",
    walletSplit: "钱包拆分",
    walletSource: "钱包来源",
    walletTypeVerified: "钱包类型已验证",
    warning: "警告",
    zhDraft: "中文 AI 草稿/回退",
    enPublished: "英文源内容已发布",
  },
} satisfies Record<SupportedLocale, Record<string, string>>;
