import type { SupportedLocale } from "../../../domain";

const enUS = {
    aiContent: "AI content review",
    aiContentPackWorkbench: "AI Content Pack Workbench",
    aiOptimizationActionQueue: "AI Optimization action queue",
    aiOpsReports: "AI Ops reports",
    adminContractReviewCenter: "Admin Contract Review Center",
    analyticsOverview: "Analytics overview",
    accountType: "Account type",
    actionStatus: "Action status",
    adoptedPreview: "Adopted preview",
    adoptedPreviewActions: "Adopted preview",
    artifacts: "artifacts",
    autoPublishBlocked: "No auto-publish: human review is required before Chinese draft can ship.",
    blocker: "Blocker",
    blockersWarnings: "Blockers and warnings",
    blocked: "Blocked",
    blockedActions: "Blocked",
    confidence: "Confidence",
    contractClaim: "CONTRACT CLAIM",
    contractClaimBlocked: "Contract claim is blocked pending high-impact manual review.",
    contractEvolution: "Contract evolution",
    contractInterfaceMatrixConsole: "Contract Interface Matrix Console",
    contractMode: "Contract mode",
    contractImpact: "Contract impact review",
    contractMethods: "Contract methods",
    contractModes: "Contract mode boundaries",
    covered: "Covered",
    deferred: "Deferred",
    deliveryChecklistReadiness: "Delivery Checklist Readiness",
    deliveryChecklistSubtitle: "v0.2 delivery audit",
    contractSurface: "Contract surface",
    companionContracts: "Companion contracts",
    changeMatrix: "Change matrix",
    conversion: "Conversion",
    conversionFunnel: "Conversion funnel",
    count: "Count",
    copyReady: "Copy ready",
    currentValue: "Current value",
    currentMvp: "Current MVP",
    defaultSafe: "Default safe mode",
    detail: "Detail",
    ecosystemMetrics: "Ecosystem metrics",
    evidence: "Evidence",
    evidenceHashes: "Evidence hashes",
    evidenceSource: "Source",
    evidenceStatus: "Evidence status",
    exactColumnOrder: "Exact CSV column order",
    expectedImpact: "Expected impact",
    exportBatch: "Export batch",
    exportConfirmation: "Export confirmation",
    exportDisclaimer: "Export winners does not distribute rewards.",
    exportEvidence: "Export evidence",
    exportPreview: "Export preview",
    exportReady: "Export readiness",
    finalRewardOwner: "Final reward distribution is handled by the campaign project.",
    futurePlanned: "Future/planned",
    generatedAt: "Generated",
    guardrail: "Guardrail",
    highImpactChecklist: "High-impact checklist",
    humanReviewGate: "Human review gate",
    humanReviewRequired: "Human review required",
    humanApproved: "Human approved",
    localePreference: "Locale",
    localeSplit: "Locale split",
    metadataHash: "Metadata hash",
    missingTasks: "Missing tasks",
    needsReview: "Needs review",
    nextAction: "Next action",
    noHumanReviewRequired: "No human gate",
    noAbiGeneration: "No ABI generation",
    noLiveContractTransaction: "No live contract transaction",
    noRewardCustodyDistribution: "No reward custody / no reward distribution",
    localOnlyBoundary: "Local-only boundary",
    onChainBoundary: "On-chain boundary",
    offChain: "OFF CHAIN MVP",
    owner: "Owner",
    ownerRole: "Owner role",
    phase: "Phase",
    priorityPhase: "Priority / phase",
    pointsRank: "Points / rank",
    product: "Product",
    qualitySignal: "Quality signal",
    qualityGates: "Quality gates",
    readiness: "Publish readiness",
    publishBlocked: "Publish blocked",
    recommendation: "Recommendation",
    recommendedV2: "Recommended V2",
    readyActions: "Ready",
    readyToReview: "Ready to review",
    referrerAddress: "Referrer address",
    requiredFor: "Required for",
    rewardCustody: "Reward custody",
    reviewQueue: "Review queue",
    reviewRequired: "Review required",
    reviewRequiredActions: "Review required",
    reviewer: "Reviewer",
    riskEligibilityBoundary: "Risk/eligibility boundaries are review inputs, not automated distribution.",
    riskDashboard: "Risk dashboard",
    riskFlags: "Risk flags",
    riskLevel: "Risk",
    rowCompleteness: "Row completeness",
    scheduleReady: "Schedule ready",
    seededBoundary: "Seeded/local review data. No live analytics, risk scoring, export file, reward distribution, wallet connection, or contract transaction is executed.",
    seededLocalReadinessBoundary: "Seeded/local readiness evidence. This console does not execute live wallet SDK, API calls, contract calls, export files, reward custody, or reward distribution.",
    sourceRequirement: "Source requirement",
    sourceMetrics: "Source metrics",
    status: "Status",
    totalContracts: "Contracts",
    totalActions: "Total actions",
    totalItems: "Total items",
    totalMethods: "Methods",
    taskEvidence: "Task evidence",
    taskRecords: "Task records",
    templateGovernance: "Template Governance",
    templateGovernanceSubtitle: "Template Manager",
    templateGovernanceBoundary: "Seeded/local template governance",
    templateStatusReady: "Ready",
    templateStatusWarning: "Warning",
    templateStatusBlocked: "Blocked",
    templates: "templates",
    localizationReview: "Localization review",
    riskReview: "Risk review",
    strongVerification: "Strong verification",
    walletCoverage: "Wallet coverage",
    walletAny: "Any wallet",
    walletAaOnly: "AA only",
    walletEoaOnly: "EOA only",
    category: "Category",
    verification: "Verification",
    defaultPoints: "Default points",
    required: "Required",
    optional: "Optional",
    title: "Admin/Ops",
    v2Companion: "V2 COMPANION",
    v2CompanionNeeded: "V2 companion needed",
    verifierRole: "Verifier role",
    verifiedRecordsOnly: "Campaign OS exports verified records only.",
    wallet: "Wallet",
    walletProviderQaReadiness: "Wallet Provider QA Readiness",
    walletProviderQaSubtitle: "Live provider evidence gate",
    totalScenarios: "Total scenarios",
    seededReady: "Seeded ready",
    liveEvidenceReady: "Live evidence ready",
    missingLiveEvidence: "Missing live evidence",
    releaseBlockers: "Release blockers",
    seededEvidence: "Seeded evidence",
    liveEvidence: "Live evidence",
    releaseImpact: "Release impact",
    matchedSessions: "Matched sessions",
    missing: "Missing",
    notApplicable: "Not applicable",
    releaseBlocker: "Release blocker",
    informational: "Informational",
    linkedSurface: "Linked surface",
    walletSplit: "Wallet split",
    walletSource: "Wallet source",
    walletTypeVerified: "Wallet type verified",
    warning: "Warning",
    zhDraft: "Chinese AI draft/fallback",
    enPublished: "English source published",
} satisfies Record<string, string>;

const zhCN = {
    aiContent: "AI 内容审核",
    aiContentPackWorkbench: "AI 内容包工作台",
    aiOptimizationActionQueue: "AI Optimization 动作队列",
    aiOpsReports: "AI Ops 报告",
    adminContractReviewCenter: "管理员合约审核中心",
    analyticsOverview: "分析概览",
    accountType: "账户类型",
    actionStatus: "动作状态",
    adoptedPreview: "Seeded 预览采纳",
    adoptedPreviewActions: "预览采纳",
    artifacts: "个内容",
    autoPublishBlocked: "禁止自动发布：中文草稿发布前必须经过人工审核。",
    blocker: "阻断",
    blockersWarnings: "阻断与警告",
    blocked: "已阻断",
    blockedActions: "已阻断",
    confidence: "置信度",
    contractClaim: "CONTRACT CLAIM",
    contractClaimBlocked: "Contract claim 已阻断，等待高影响人工审核。",
    contractEvolution: "合约演进路线",
    contractInterfaceMatrixConsole: "合约接口矩阵控制台",
    contractMode: "合约模式",
    contractImpact: "合约影响审核",
    contractMethods: "合约方法",
    contractModes: "合约模式边界",
    covered: "已覆盖",
    deferred: "已后置",
    deliveryChecklistReadiness: "交付清单 Readiness",
    deliveryChecklistSubtitle: "v0.2 交付审计",
    contractSurface: "合约面",
    companionContracts: "Companion contracts",
    changeMatrix: "变更矩阵",
    conversion: "转化",
    conversionFunnel: "转化漏斗",
    count: "数量",
    copyReady: "可复制",
    currentValue: "当前值",
    currentMvp: "当前 MVP",
    defaultSafe: "默认安全模式",
    detail: "详情",
    ecosystemMetrics: "生态指标",
    evidence: "证据",
    evidenceHashes: "证据哈希",
    evidenceSource: "来源",
    evidenceStatus: "证据状态",
    exactColumnOrder: "精确 CSV 字段顺序",
    expectedImpact: "预期影响",
    exportBatch: "导出批次",
    exportConfirmation: "导出确认",
    exportDisclaimer: "导出 winners 不等于发奖。",
    exportEvidence: "导出证据",
    exportPreview: "导出预览",
    exportReady: "导出就绪",
    finalRewardOwner: "最终奖励发放由活动项目方处理。",
    futurePlanned: "未来/计划中",
    generatedAt: "生成时间",
    guardrail: "防护栏",
    highImpactChecklist: "高影响审核清单",
    humanReviewGate: "人工审核门禁",
    humanReviewRequired: "需要人工审核",
    humanApproved: "人工已批准",
    localePreference: "语言",
    localeSplit: "语言拆分",
    metadataHash: "Metadata hash",
    missingTasks: "缺失任务",
    needsReview: "需要复核",
    nextAction: "下一步",
    noHumanReviewRequired: "无需人工门禁",
    noAbiGeneration: "不会生成 ABI",
    noLiveContractTransaction: "不会执行真实合约交易",
    noRewardCustodyDistribution: "不托管奖励 / 不发奖",
    localOnlyBoundary: "本地边界",
    onChainBoundary: "链上边界",
    offChain: "OFF CHAIN MVP",
    owner: "负责人",
    ownerRole: "负责人角色",
    phase: "阶段",
    priorityPhase: "优先级 / 阶段",
    pointsRank: "积分 / 排名",
    product: "产品",
    qualitySignal: "质量信号",
    qualityGates: "质量门禁",
    readiness: "发布 readiness",
    publishBlocked: "发布已阻断",
    recommendation: "建议",
    recommendedV2: "建议 V2",
    readyActions: "可审核",
    readyToReview: "可审核",
    referrerAddress: "推荐人地址",
    requiredFor: "适用阶段",
    rewardCustody: "奖励托管",
    reviewQueue: "审核队列",
    reviewRequired: "需要审核",
    reviewRequiredActions: "需要审核",
    reviewer: "审核人",
    riskEligibilityBoundary: "风险/资格边界仅作为审核输入，不会自动发奖。",
    riskDashboard: "风险看板",
    riskFlags: "风险标记",
    riskLevel: "风险",
    rowCompleteness: "行完整度",
    scheduleReady: "可排期",
    seededBoundary: "Seeded/本地审核数据。不会执行实时分析、风险评分、导出文件、发奖、钱包连接或合约交易。",
    seededLocalReadinessBoundary: "Seeded/本地 readiness 证据。这个控制台不会执行实时钱包 SDK、API 调用、合约调用、导出文件、奖励托管或发奖。",
    sourceRequirement: "来源要求",
    sourceMetrics: "来源指标",
    status: "状态",
    totalContracts: "合约",
    totalActions: "总动作",
    totalItems: "总条目",
    totalMethods: "方法",
    taskEvidence: "任务证据",
    taskRecords: "任务记录",
    templateGovernance: "模板治理",
    templateGovernanceSubtitle: "模板管理",
    templateGovernanceBoundary: "Seeded/本地模板治理",
    templateStatusReady: "就绪",
    templateStatusWarning: "警告",
    templateStatusBlocked: "阻断",
    templates: "个模板",
    localizationReview: "本地化审核",
    riskReview: "风险审核",
    strongVerification: "强验证",
    walletCoverage: "钱包覆盖",
    walletAny: "任意钱包",
    walletAaOnly: "仅 AA",
    walletEoaOnly: "仅 EOA",
    category: "类别",
    verification: "验证方式",
    defaultPoints: "默认积分",
    required: "必做",
    optional: "可选",
    title: "管理员/Ops",
    v2Companion: "V2 COMPANION",
    v2CompanionNeeded: "是否需要 V2 companion",
    verifierRole: "Verifier role",
    verifiedRecordsOnly: "Campaign OS 仅导出已验证记录。",
    wallet: "钱包",
    walletProviderQaReadiness: "钱包 Provider QA Readiness",
    walletProviderQaSubtitle: "真实 provider 证据门禁",
    totalScenarios: "场景总数",
    seededReady: "Seeded 就绪",
    liveEvidenceReady: "真实证据就绪",
    missingLiveEvidence: "缺失真实证据",
    releaseBlockers: "发布阻断",
    seededEvidence: "Seeded 证据",
    liveEvidence: "真实证据",
    releaseImpact: "发布影响",
    matchedSessions: "匹配会话",
    missing: "缺失",
    notApplicable: "不适用",
    releaseBlocker: "发布阻断",
    informational: "信息项",
    linkedSurface: "关联界面",
    walletSplit: "钱包拆分",
    walletSource: "钱包来源",
    walletTypeVerified: "钱包类型已验证",
    warning: "警告",
    zhDraft: "中文 AI 草稿/回退",
    enPublished: "英文源内容已发布",
} satisfies typeof enUS;

export const adminOpsCopy = {
  "en-US": enUS,
  "zh-CN": zhCN,
  "zh-TW": {
    ...zhCN,
    autoPublishBlocked: "禁止自動發布：繁中目前為 fallback/readiness lane，發布前必須經過人工審核。",
    localeSplit: "語言拆分",
    localePreference: "語言",
    zhDraft: "繁中 fallback/readiness",
  },
} satisfies Record<SupportedLocale, typeof enUS>;
